### ISSUE TITLE
Tutorial OpenSpiel KuhnOpenNSFP fails

### ISSUE THREAD

**Issue by finmod** [JuliaReinforcementLearning/ReinforcementLearning.jl#1024]
Trying to run this example: https://juliareinforcementlearning.org/docs/experiments/experiments/NFSP/JuliaRL_NFSP_OpenSpiel/#JuliaRL\\_NFSP\\_OpenSpiel(kuhn_poker) on WSL Ubuntu 2204 Julia 1.10.2. 

It fails as follows:

LoadError: MethodError: no method matching information_state_tensor(::CxxWrap.StdLib.UniquePtrAllocated{State}, ::Int64)

Closest candidates are:
  information_state_tensor(::Union{State, CxxWrap.CxxWrapCore.CxxRef{<:State}}, ::Integer)
   @ OpenSpiel [~/.julia/packages/CxxWrap/5IZvn/src/](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/~/.julia/packages/CxxWrap/5IZvn/src/)CxxWrap.jl:624

in expression starting at In[8]:121

Stacktrace:
 [1] _state(env::OpenSpielEnv{CxxWrap.StdLib.UniquePtrAllocated{State}, CxxWrap.StdLib.SharedPtrAllocated{Game}}, ::InformationSet{Array}, player::Int64)
   @ ReinforcementLearningEnvironments [~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/3rd_party/open_spiel.jl:141](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/3rd_party/open_spiel.jl:141)
 [2] state(env::OpenSpielEnv{CxxWrap.StdLib.UniquePtrAllocated{State}, CxxWrap.StdLib.SharedPtrAllocated{Game}}, ss::InformationSet{Array}, player::Int64)
   @ ReinforcementLearningEnvironments [~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/3rd_party/open_spiel.jl:135](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/3rd_party/open_spiel.jl:135)
 [3] state
   @ [~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/wrappers/wrappers.jl:21](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/wrappers/wrappers.jl:21) [inlined]
 [4] state(env::DefaultStateStyleEnv{InformationSet{Array}(), ActionTransformedEnv{var"#21#25"{OpenSpielEnv{CxxWrap.StdLib.UniquePtrAllocated{State}, CxxWrap.StdLib.SharedPtrAllocated{Game}}}, var"#20#24"{OpenSpielEnv{CxxWrap.StdLib.UniquePtrAllocated{State}, CxxWrap.StdLib.SharedPtrAllocated{Game}}}, OpenSpielEnv{CxxWrap.StdLib.UniquePtrAllocated{State}, CxxWrap.StdLib.SharedPtrAllocated{Game}}}}, player::Int64)
   @ ReinforcementLearningEnvironments [~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/wrappers/DefaultStateStyle.jl:20](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/wrappers/DefaultStateStyle.jl:20)
 [5] Experiment(::Val{:JuliaRL}, ::Val{:NFSP}, ::Val{:OpenSpiel}, game::SubString{String}; seed::Int64)
   @ Main [./In](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/In)[8]:35
 [6] Experiment
   @ [./In](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/In)[8]:17 [inlined]
 [7] Experiment(s::String)
   @ ReinforcementLearningCore [~/.julia/packages/ReinforcementLearningCore/yeRLW/src/core/experiment.jl:46](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/~/.julia/packages/ReinforcementLearningCore/yeRLW/src/core/experiment.jl:46)
 [8] var"@E_cmd"(__source__::LineNumberNode, __module__::Module, s::Any)
   @ ReinforcementLearningCore [~/.julia/packages/ReinforcementLearningCore/yeRLW/src/core/experiment.jl:36](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/denismichelrichard/~/.julia/packages/ReinforcementLearningCore/yeRLW/src/core/experiment.jl:36)

**Comment by finmod** [comment]
Same problem with KuhnOpenEDHook. Perhaps this issue should be raised in OpenSpiel since it has to do with CxxWrap?

**Comment by jeremiahpslewis** [comment]
this should / may fix it https://github.com/JuliaReinforcementLearning/OpenSpiel.jl/pull/21

**Comment by jeremiahpslewis** [comment]
Try OpenSpiel.jl v0.2.2

**Comment by finmod** [comment]
Test OpenSpiel v0.2.2 Ok, Test ReinforcementLearning v0.10.2 Ok . 

It continues to fail:

{
	"name": "LoadError",
	"message": "LoadError: MethodError: no method matching information_state_tensor_shape(::CxxWrap.StdLib.SharedPtrAllocated{Game})

Closest candidates are:
  information_state_tensor_shape(::Union{Ptr{Nothing}, CxxWrap.CxxWrapCore.ConstCxxPtr{<:Game}, CxxWrap.CxxWrapCore.CxxPtr{<:Game}})
   @ OpenSpiel ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:624
  information_state_tensor_shape(::Union{Game, CxxWrap.CxxWrapCore.ConstCxxRef{<:Game}, CxxWrap.CxxWrapCore.CxxRef{<:Game}})
   @ OpenSpiel ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:624

in expression starting at In[2]:69",
	"stack": "LoadError: MethodError: no method matching information_state_tensor_shape(::CxxWrap.StdLib.SharedPtrAllocated{Game})

Closest candidates are:
  information_state_tensor_shape(::Union{Ptr{Nothing}, CxxWrap.CxxWrapCore.ConstCxxPtr{<:Game}, CxxWrap.CxxWrapCore.CxxPtr{<:Game}})
   @ OpenSpiel ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:624
  information_state_tensor_shape(::Union{Game, CxxWrap.CxxWrapCore.ConstCxxRef{<:Game}, CxxWrap.CxxWrapCore.CxxRef{<:Game}})
   @ OpenSpiel ~/.julia/packages/CxxWrap/5IZvn/src/CxxWrap.jl:624

in expression starting at In[2]:69

Stacktrace:
 [1] _state(env::OpenSpielEnv{CxxWrap.StdLib.UniquePtrAllocated{State}, CxxWrap.StdLib.SharedPtrAllocated{Game}}, ::InformationSet{Array}, player::Int64)
   @ ReinforcementLearningEnvironments ~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/3rd_party/open_spiel.jl:141
 [2] state(env::OpenSpielEnv{CxxWrap.StdLib.UniquePtrAllocated{State}, CxxWrap.StdLib.SharedPtrAllocated{Game}}, ss::InformationSet{Array}, player::Int64)
   @ ReinforcementLearningEnvironments ~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/3rd_party/open_spiel.jl:135
 [3] state
   @ ~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/wrappers/wrappers.jl:21 [inlined]
 [4] state
   @ ~/.julia/packages/ReinforcementLearningEnvironments/Pzsys/src/environments/wrappers/DefaultStateStyle.jl:20 [inlined]
 [5] Experiment(::Val{:JuliaRL}, ::Val{:ED}, ::Val{:OpenSpiel}, game::SubString{String}; seed::Int64)
   @ Main ./In[2]:40
 [6] Experiment(::Val{:JuliaRL}, ::Val{:ED}, ::Val{:OpenSpiel}, game::SubString{String})
   @ Main ./In[2]:22
 [7] Experiment(s::String)
   @ ReinforcementLearningCore ~/.julia/packages/ReinforcementLearningCore/yeRLW/src/core/experiment.jl:46
 [8] var\"@E_cmd\"(__source__::LineNumberNode, __module__::Module, s::Any)
   @ ReinforcementLearningCore ~/.julia/packages/ReinforcementLearningCore/yeRLW/src/core/experiment.jl:36"
}

**Comment by jeremiahpslewis** [comment]
https://github.com/JuliaReinforcementLearning/OpenSpiel.jl/pull/22

**Comment by jeremiahpslewis** [comment]
Try OpenSpiel.jl v0.2.3
