### ISSUE TITLE
CI: Should spell check be dropped or fixed?

### ISSUE THREAD

**Issue by joelreymont** [JuliaReinforcementLearning/ReinforcementLearning.jl#1026]
Every spell check run I've seen so far [has failed](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/actions/runs/8172229646). 

Should there be a spell check run?

**Comment by jeremiahpslewis** [comment]
Want to fix this? It's a combination of expanding the Julia dict, https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/main/.cspell/julia_words.txt and fixing the actual typos

**Comment by joelreymont** [comment]
Will fix!
