### ISSUE TITLE
Website: A practical introduction to RL: Does not introduce, source code is broken

### ISSUE THREAD

**Issue by joelreymont** [JuliaReinforcementLearning/ReinforcementLearning.jl#1036]
Can't run the example code in the [Practical introduction to RL](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/docs/homepage/blog/a_practical_introduction_to_RL.jl/index.html) blog post since the source code is largely broken.

**Comment by jeremiahpslewis** [comment]
Replaced with https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/1036
