### ISSUE TITLE
Website: How do implement a new algorithm is outdated 

### ISSUE THREAD

**Issue by joelreymont** [JuliaReinforcementLearning/ReinforcementLearning.jl#1037]
Compare the [website version](https://juliareinforcementlearning.org/docs/How_to_implement_a_new_algorithm/) with the actual [docs](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/main/docs/src/How_to_implement_a_new_algorithm.md).

**Comment by HenriDeh** [comment]
Yes this is because the website version shows the released version, while the docs in the source code show the latest version. That's why I linked that latter to you, they are not outdated. With v0.11 the website will update.
