### ISSUE TITLE
Base.convert method for DiscreteSpace

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#104]
In the line [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/6ee52166339e82a85aac152065a995c73c040601/src/implementations/spaces/discrete_space.jl#L59)

```
Base.convert(
    ::Type{AbstractSpace},
    s::Union{<:Integer,<:UnitRange,<:Vector,<:Tuple,<:Set},
) = DiscreteSpace(s)
```

Should we have `Type{DiscreteSpace}` instead of `Type{AbstractSpace}`? Since `s` can only be an iterable (or an `Integer`) and iterables could only form a `DiscreteSpace`.

Also, suppose if we have an `s` that is an `Int64`, then it feels a little unintuitive that `DiscreteSpace(s)` should convert it to the range `1:s`? We already have `UnitRange` for that purpose. Instead, what if we just wanted to operate with the integer `s` like union that new integer action to the an existing `DiscreteSpace`, for example?

**Comment by findmyway** [comment]
AbstractSpace is now removed.
