### ISSUE TITLE
Base.in method for EmptySpace

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#105]
Currently, we have the following from [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/00125d67da2d0a07afffed0dee45b56e4e53e4e2/src/implementations/spaces/empty_space.jl#L12)
```
Base.in(x, s::EmptySpace) = x isa Nothing
```

I was wondering why should `Base.in(nothing, s)` be equal to `true`?

It seems more intuitive to me to not have any element belonging to an `EmptySpace` object, that is, to have something like:
```
Base.in(x, s::EmptySpace) = false
```

**Comment by findmyway** [comment]
EmptySpace will be replaced with `()` simply.
