### ISSUE TITLE
Renaming get_terminal to isterminated

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#106]
`get_terminal` returns a `Bool` and corresponds to the information about whether an environment has terminated or not.

Following convention, maybe we can rename it to something like `isterminated` instead.

**Comment by findmyway** [comment]
Fixed in https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/pull/107
