### ISSUE TITLE
Suggestion: More informative name for FullActionSet & MinimalActionSet

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#107]
This is a suggestion to consider more informative names in place of `FullActionSet` and `MinimialActionSet`.

If I understand correctly, then `MinimalActionSet` provides a fixed set of valid actions at each step, whereas, with `FullActionSet`, the set of valid actions at each step is given by a "legal action set" that may vary depending upon some context, usually the current state.

In order to make this a little more intuitive from the name of the traits, I suggest using something simple like `FixedActionSet` vs. `VariableActionSet`. Another candidate could be `UniformActionSet` vs. `NonUniformActionSet`.

Personally, I like `FixedActionSet` vs. `VariableActionSet`. It is simple, and instantly brings across the main distinction between the two action styles.

**Comment by findmyway** [comment]
I prefer to keep these names as they were. But feel free to re-open if they are still too confusing.
