### ISSUE TITLE
Algorithm implementations

### ISSUE THREAD

**Issue by johannes-fischer** [JuliaReinforcementLearning/ReinforcementLearning.jl#1070]
With v0.11 all existing algorithms disappeared since they are not compatible with the updated package. Are some of them already being worked on and can be expected to be back soon?
And is there a comprehensive overview with the package changes that illustrates what would need to be updated in the old existing algorithms to work with the new package design? I.e. some guidelines how to get them working again?

**Comment by jeremiahpslewis** [comment]
1. Algorithms on earlier version are not only (as a result of various changes) no longer compatible, they also were not unit tested so it was not possible to maintain correctness across versions
2. There are example / template policies in the v0.11 package, eg qpolicy, tabularapproximator, which can be used as examples of how to implement new algorithms which are compatible
3. The v0.11 release was blocked for over a year by a problematic work-to-contributor ratio, as a result the decision was made to reduce the scope of the v0.11 release by dropping most algorithms from the initial version (‘rip the bandaid off’ approach); (unit tested) algorithm contributions are highly welcome.
