### ISSUE TITLE
No method matching iterate ArrayProductDomain

### ISSUE THREAD

**Issue by ZdM87** [JuliaReinforcementLearning/ReinforcementLearning.jl#1074]
This happens when trying to train an agent for the `StockTradingEnv` environment

    env = StockTradingEnv()
    
    ns, na = size(state_space(env))[1], size(action_space(env))[1]
    
    policy = Agent(
        QBasedPolicy(;
            learner = TDLearner(
                TabularQApproximator(n_state = ns, n_action = na),
                :SARS;
            ),
            explorer = EpsilonGreedyExplorer(ϵ_stable=0.01),
        ),
        Trajectory(
            CircularArraySARTSTraces(;
                capacity = 10,
                state = Float64 => (ns,),
                action = Float64 => (na,),
                reward = Float64 => (),
                terminal = Bool => (),
            ),
            DummySampler(),
            InsertSampleRatioController(),
        ),
    )
    
    run(
        policy,
        env,
        StopAfterNSteps(10_000),
    )

**Comment by jeremiahpslewis** [comment]
Hey! This error is confusing and I've opened a PR #1075 so that things error in the 'correct' spot, but the problem is straightforward: you are using a tabular algorithm to solve a continuous problem; your action space is not discrete, but the `TabularQApproximator` algorithm requires a discrete action space to learn on.

**Comment by ZdM87** [comment]
Thank you. So, there is no support for continuous problem yet?

**Comment by jeremiahpslewis** [comment]
Your example works now with the latest version, it’s even been added as a unit test
