### ISSUE TITLE
Why are wrapper environments a part of RLBase instead of RLCore (say)?

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#109]
I am trying to understand why wrapper environments (given [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/master/src/implementations/environments.jl)) are a part of `RLBase`. Is there a strong reason to keep them as part of the core API?

Furthermore, the directory in which the `environments.jl` file resides is called `implementations`, and as the name suggests aptly, the contents within seem more like a part of implementation rather than the core API. For example, we are already discussing to move out `AbstractSpace` related things from `RLBase` into a separate package at JuliaReinforcementLearning/ReinforcementLearning.jl#108 

Wrapper environments feel more like tools, as in, they help "prepare" an environment for the final experiment by aiding minor feature additions to existing environments rather than having users rewrite entire environments separately. Maybe we could consider moving them to something like `RLCore`, perhaps? Also, removing wrapper environments from `RLBase` also strips away their "privileged" status (whose reason I don't understand). Personally, I feel that this, in turn, might also encourage users to create, use, experiment with, and potentially contribute their own clever wrapper environments more freely :)

**Comment by findmyway** [comment]
I'm going to move environment wrapper related code from `RLBase` into `RLEnvs` and move `RandomPolicy` related code into `RLCore`, leaving only interface definitions in `RLBase`.

**Comment by Sid-Bhatia-0** [comment]
>move `RandomPolicy` related code into `RLCore`, leaving only interface definitions in `RLBase`.

Sounds good.

>I'm going to move environment wrapper related code from `RLBase` into `RLEnvs`

I was thinking maybe we could put the environment wrappers into `RLCore`. This is because environment wrappers are more like reusable tools to aid environment creation. One need not have to import the entire "zoo of environments" (`RLEnvs`) just to be able to reuse these tools to help create their own environments.

As an example, imagine if we wanted to reuse these wrappers in `GridWorlds.jl`, for example. Then adding a dependency on `RLCore` is much lighter than adding a dependency on `RLEnvs`. What do you think?

**Comment by findmyway** [comment]
> Then adding a dependency on RLCore is much lighter than adding a dependency on RLEnvs. 

RLCore has much more dependencies then RLenvs.

People will never want to load Flux.jl to use those wrappers……😬

**Comment by Sid-Bhatia-0** [comment]
>`RLCore` has much more dependencies than `RLenvs`.

You are absolutely right!
Earlier, I somehow thought it had more dependencies, just like `RLZoo` does... But now I confirmed that it is pretty light actually.

`RLEnvs` is a good idea.

**Comment by findmyway** [comment]
Hi @Sid-Bhatia-0 ,

After thinking for a while, I prefer to keep environment wrappers in `RLBase`. The main reasons are:

1. Environment wrappers are highly tight with interfaces defined in `RLBase`.
2. They are lightweight enough and do not have other dependencies.
3. Moving them into `RLEnvs` will introduce many unnecessary dependencies in it.

**Comment by Sid-Bhatia-0** [comment]
>1. Environment wrappers are highly tight with interfaces defined in `RLBase`.
>1. They are lightweight enough and do not have other dependencies.
>1. Moving them into `RLEnvs` will introduce many unnecessary dependencies in it.

Yes. I agree with you on all of the above reasons, especially the second one.
We can let wrappers stay in `RLBase`.

**Comment by findmyway** [comment]
Moved into `RLCore` 

https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/pull/103

**Comment by Sid-Bhatia-0** [comment]
>Moved into `RLCore`

You mean `RLEnvs`, right?

**Comment by findmyway** [comment]
Yeah, I mean `RLEnvs`. Sorry.
