### ISSUE TITLE
Requesting more informative field names for SharedTrajectory

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#113]
Inside `SharedTrajectory`, how about having a field name like `window` or `range` in place of `meta`? Something that provides more information about the purpose of the field.

Similarly in place of `x`, maybe we could use something like `buffer`?

**Comment by findmyway** [comment]
`SharedTrajectory` is now removed to make the code easier to understand.
