### ISSUE TITLE
Requesting explanation for better performance at ...

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#115]
[Here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/a9fcedc25d0c1e98a2ed671bfeed822b850bb14a/src/utils/base.jl#L58), it is mentioned that
 
```
reshape(x, (size(x) |> reverse |> Base.tail |> Base.tail |> reverse)..., :)
```
is much faster than 
```
reshape(x, size(x)[1:end-2]..., :)
```

A brief explanation as to why that is so would be really appreciated! Thanks.

**Comment by findmyway** [comment]
Confirmed. This is not necessary anymore at least with Julia@v1.5
