### ISSUE TITLE
Behaviour for hooks for RewardOverridenEnv

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#119]
I am trying to use `RewardOverridenEnv` for a per-step penalty to be added in addition to the regular reward of the underlying environment.

The reward related hooks, like `TotalRewardPerEpisode`, for example, explicitly override the behavior to record the original reward (without penalty). This means that while logging reward information (using `TensorBoardLogger`, say), I am unable to view the intended reward, which feels a little unintuitive and misleading, because it is ultimately the final reward after all the transformations that I care about, which is why I used the `RewardOverridenEnv` wrapper in the first place.

**Comment by findmyway** [comment]
Fixed in https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/pull/188
