### ISSUE TITLE
Add Highway env

### ISSUE THREAD

**Issue by rbange** [JuliaReinforcementLearning/ReinforcementLearning.jl#120]
https://github.com/eleurent/highway-env looks like very interesting environments. The Maintainer also released the "[first stable release](https://github.com/eleurent/highway-env/releases/tag/v1.0)".

Implementation should not be too hard as it uses the `gym` api?

**Comment by findmyway** [comment]
I just made a quick test. It seems to work as expected with `GymEnv`

Running in the Julia side with `PyCall.jl` for 100 random steps cost about 58 seconds, while it is about 52.1 in Python.
