### ISSUE TITLE
Classic environments in separate package?

### ISSUE THREAD

**Issue by darsnack** [JuliaReinforcementLearning/ReinforcementLearning.jl#123]
Opening this up because of https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/18#issuecomment-647616237. This package has some classic environments implemented, as well as a lot of wrapped environments. In that sense, this package does function as a "glue" package (a one-stop shop as mentioned in the README).

As discussed in the linked comment, there are some features that could be added to the classic environments here. I was considering doing that as a PR, but then I thought it might make more sense to split that into its own package. I could do that in FluxML/Gym.jl (I think we can also take ownership of this repo if preferred), since it already supported the rendering logic which is the most involved part. Then this package could just be a "glue"/wrapper package.

What are folks thoughts on this approach?

**Comment by findmyway** [comment]
In the latest version of ReinforcementLearningEnvironments.jl, only some very simple environments which are typical enough are included. So I think we can just keep them as they are now.
