### ISSUE TITLE
Add procgen

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#126]
https://github.com/openai/procgen

Should be relatively easy to support with Clang.jl

**Comment by AlexLewandowski** [comment]
This is completed?

**Comment by findmyway** [comment]
No. But after looking into its implementation recently, I found it's not that easy as I thought. It has an independent repo for VecEnv. And some code logic are written in Python. 

Plus, it doesn't seem to be maintained anymore.

**Comment by kir0ul** [comment]
> Plus, it doesn't seem to be maintained anymore.

FYI there's a community maintained fork here: https://github.com/Farama-Foundation/procgen2
