### ISSUE TITLE
Migrate to Pluto

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#148]

**Comment by findmyway** [comment]
Hi @DhruvaSambrani 

Last week, I made some initial work on migrating code in ReinforcementLearningAnIntroduction.jl:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/pull/144
https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/pull/200
https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/pull/119
https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/pull/23

It's **much** more complicated than I thought. (This means that the original code is really not well designed. 😢 ) So I decide to make my hands dirty and work on it myself in the next several days.

**Comment by DhruvaSambrani** [comment]
Anywhere I can help? I'm learning RL, so I thought this would be a good way to learn!☺️

**Comment by findmyway** [comment]
> Anywhere I can help? I'm learning RL, so I thought this would be a good way to learn!☺️

That's great!

So the current progress is that in https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/pull/23 I've finished chapter01 and 02. And I hope you can easily pick things up by reading these two notebooks. (If anything is confusing to you, feel free to add comments there and we can improve them further.)

I think Chapter 3 ~ 5 are relatively independent and easy to implement. Maybe you can take an attempt and try to migrate some of them? In the meanwhile, I'll start from Chapter 6.

To set up the environment, you need to checkout the draft PRs I linked above. And in the PR of https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/pull/23 , you need to do the following changes:

1. `cd /path/to/ReinforcementLearningAnIntroduction.jl/`
2. `]activate .`
2. `]dev /path/to/ReinforcementLearningEnvironments.jl`
3. `]dev /path/to/ReinforcementLearningCore.jl`
4. `]dev /path/to/ReinforcementLearningZoo.jl`
5. `]dev /path/to/ReinforcementLearning.jl`  (https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/177)
5. Install `Pluto.jl`
    1. `using Pluto; Pluto.run()`
    2. Open `notebooks/Chapter01_Tic_Tac_Toe.jl` and test if it works.

**Comment by findmyway** [comment]
Current progress:

- [x] Chapter01_Tic_Tac_Toe
- [x] Chapter02_Ten_Armed_Testbed
- [ ] Chapter03_Grid_World
- [ ] Chapter04_Car_Rental
- [ ] Chapter04_Gambler_Problem
- [ ] Chapter04_Grid_World
- [ ] Chapter05_Black_Jack_Fig_5_1
- [ ] Chapter05_Black_Jack_Fig_5_2
- [ ] Chapter05_Black_Jack_Fig_5_3
- [ ] Chapter05_Left_Right
- [x] Chapter06_Cliff_Walking
- [x] Chapter06_Maximization_Bias
- [ ] Chapter06_Random_Walk
- [ ] Chapter06_Windy_Grid_World
- [ ] Chapter07_Random_Walk
- [ ] Chapter08_Expectation_VS_Sample
- [ ] Chapter08_Maze
- [ ] Chapter08_Trajectory_Sampling
- [ ] Chapter09_Random_Walk
- [ ] Chapter10_Access_Control
- [ ] Chapter10_Mountain_Car
- [ ] Chapter11_Counter_Example
- [ ] Chapter12_Random_Walk
- [ ] Chapter13_Short_Corridor

**Comment by rishabhvarshney14** [comment]
@findmyway Can I help in migrating to Pluto? Thanks

**Comment by findmyway** [comment]
Sure. Just follow the steps I mentioned above and make PRs to correspond branches. I'm in hospital since last week so I really need someone else's help to move forward. My review may be late but do let me know if you need any help.

**Comment by DhruvaSambrani** [comment]
I'm caught up in college work too. Please go ahead!

**Comment by rishabhvarshney14** [comment]
@findmyway @DhruvaSambrani I have my exams in a few days so I can only work on this after that.

**Comment by findmyway** [comment]
That's fine. The good news is I'm back and I will continue working on it slowly.

**Comment by findmyway** [comment]
Thank you all for your interest in this issue. I've finished the migration on the master branch of [ReinforcementLearningAnIntroduction.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl).

Your feedback is still very important. So feel free to create an issue if you have any problem in understanding those notebooks.
