### ISSUE TITLE
Update dependency to the latest version of ReinforcementLearning.jl

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#149]

**Comment by DhruvaSambrani** [comment]
I'd like to take this up with #148
Can you list out what may go wrong, what may need to be changed

**Comment by findmyway** [comment]
Hey @DhruvaSambrani ,

Glad to have your help!

Be prepared that this is not a relatively easy issue to fix. Actually we are going to rewrite [ReinforcementLearningAnIntroduction.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl). But no worry. I'll work on it with you together 🤗 .

I'll list the current status of some packages related here to make sure we're on the same page.

- [ ] [RLBase](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl) recently merged an important [PR](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/pull/107). It clearly defined two main concepts, `AbstractPolicy` and `AbstractEnv`. One thing left is to tag a new release.
- [ ] [RLCore](https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl) needs to change its dependency to the next release of `RLBase` above.
  - [ ] Rename API
  - [ ] Move old `RandomPolicy` and `TabularRandomPolicy` into RLCore
- [ ] Changes to `RLIntro`
  - [Environments](https://github.com/JuliaReinforcementLearning/ReinforcementLearningAnIntroduction.jl/tree/master/src/environments) referred in the book need a rewrite. Some of them are already implemented in `RLBase`, like `TicTacToeEnv`, `RandomWalk1D`, `MultiArmBanditsEnv`. This should be relative easy, since many of them are only API related changes.
  - Some trajectories are removed from RLCore, `EpisodicTrajectory`.
  - [ ] A `Base.run` dispatched on a multi agent environment must be implemented.
  - [ ] `DyraAgent` is removed in RLCore, it needs to be implemented.
  - [ ] `OffPolicy` is removed. Need to be implemented.

My suggestions are:

1. Wait for me to tag a new release of RLBase (This should happen in the next several days. I'll ping you here when it's ready)
1. In the meanwhile, you can take a look at `RLBase` and try to modify environments in RLIntro to use the new API.
1. Start with the first Chapter and make a draft PR. So that I can provide some early feedback.
