### ISSUE TITLE
add time stamp in load & save function, in file src\components\agents\agent.jl

### ISSUE THREAD

**Issue by norci** [JuliaReinforcementLearning/ReinforcementLearning.jl#158]
I'd like to save multiple agents during training, in order to pick the best one.

but the save function overwrites the previous one.
I think this can be solved by adding a suffix in the file name, such as use a time stamp.

ref:
[keras's ModelCheckpoint](https://keras.io/api/callbacks/model_checkpoint/)
[Flux's Checkpointing](https://fluxml.ai/Flux.jl/stable/saving/#Checkpointing-1)

**Comment by findmyway** [comment]
Load/Save related functions are removed from RLCore to keep things simple and concise.

> but the save function overwrites the previous one.
> I think this can be solved by adding a suffix in the file name, such as use a time stamp.

One can manually implement it as a customized hook.

**Comment by norci** [comment]
agree.
we can save the weights of the model only, and load it into the policy.
