### ISSUE TITLE
AbstractStage docstring doesn't render correctly in docs.

### ISSUE THREAD

**Issue by adrhill** [JuliaReinforcementLearning/ReinforcementLearning.jl#160]
Shown in docs [here](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_core/#ReinforcementLearningCore.AbstractStage).

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/4b6c68cd618b8be25837cfb799943144b9552278/src/components/agents/abstract_agent.jl#L38-L52

**Comment by findmyway** [comment]
Thanks!

I'll add a GIF to describe it later.

XRef: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/92#issuecomment-725459400

**Comment by findmyway** [comment]
The doc is removed now.
