### ISSUE TITLE
Moving example environments from RLBase to RLEnvs?

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#167]
I was wondering why do the [example environments](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/tree/master/src/examples) currently belong in `RLBase` instead of `RLEnvs`.

**Comment by findmyway** [comment]
Yeah I should have document this in the README.

They are just examples to demonstrate how to write different kinds of environments and serve as test cases of interfaces.

They were not to be exposed. But then I realized that someof them may be reused in RLIntro. So I exported them all.

I intend to make RLenvs a wrapper of many 3-rd party envs, which may have some large dependencies, like gr, makie, CxxWrap

**Comment by Sid-Bhatia-0** [comment]
>I intend to make `RLenvs` a wrapper of many 3-rd party envs, which may have some large dependencies, like gr, makie, CxxWrap

Are you suggesting that this should be the only purpose of `RLEnvs`, to provide wrappers for other environments rather than contain implementations of environments?

There are simple environments, classic control ones like `CartPole`, that are implemented within `RLEnvs` itself. My question is why can't the example environments currently present in `RLBase` be moved to a place like `RLEnvs` or into a package of their own containing simple environments that don't have any large dependencies?

Mainly for the purpose of keeping `RLBase.jl` as minimal as possible.

**Comment by findmyway** [comment]
> Are you suggesting that this should be the only purpose of RLEnvs, to provide wrappers for other environments rather than contain implementations of environments?

Yes, see also https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/123

> My question is why can't the example environments currently present in RLBase be moved to a place like RLEnvs or into a package of their own containing simple environments that don't have any large dependencies?

Like I said above, one important role of these environments is to test the expressiveness of APIs defined in `RLBase`. And I do not plan to add more in `RLBase`, unless it enriches the APIs. They serve as a golden guideline for how to write customized environments so I want to keep them updated on the master branch and easy for people to find. Splitting them into an independent package is also fine but I think no one else would use it given that they are just toy examples.

**Comment by Sid-Bhatia-0** [comment]
> one important role of these environments is to test the expressiveness of APIs defined in `RLBase`
> They serve as a golden guideline for how to write customized environments so I want to keep them updated on the master branch and easy for people to find.

What if we clearly state in the README to check out these simple environments as examples, and provide a link to this package. `RLBase` README isn't cluttered with too much info. I don't think people can miss this.

>Splitting them into an independent package is also fine but I think no one else would use it given that they are just toy examples.

Why? Don't you think a simple implementation of something like `MultiArmedBandits` won't be useful to anyone?
Since it has already been implemented, we might as well provide it as a package that a user can use off the shelf.

Also, exporting these environment names through `RLBase` seems to clash with its minimalism, and the core purpose of only providing an API. Wrapper environments are allowed since we don't have a better place for them right now, but these environments can easily be put in a package of their own.

A package that uses `RLBase` heavily (like `GridWorlds.jl`) does not need variables like `TicTackToeEnv` entering its namespace.
Moreover, if one is to actually implement `TicTacToeEnv` in `GridWorlds.jl` (just saying), then there would also be unnecessary name clashing.

**Comment by findmyway** [comment]
I see. Let me have a think. Thanks for your suggestions.

**Comment by findmyway** [comment]
Examples are now moved into `RLEnvs`
