### ISSUE TITLE
Keeping prefix `get_` in method names like `get_reward`

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#168]
I was wondering why not keep the prefix `get_` in methods like `get_state` and `get_reward`? https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/pull/107

I believe the prefix `get_` plays an important role in distinguishing the quantity `reward` from the method to fetch that quantity.

The name `reward` might become a little too overloaded if we use it to represent the field name `reward`, the method name `reward` to acquire that field, and often also the variable name `reward` to which this entity would be stored at the calling site of such a method (like `reward = reward(env)`). @findmyway  What do you think?

I think the name `get_reward` already clearly indicates that it is a method, as well as the purpose of the method. Plus the prefixes like `get_` and `set_` are fairly standard conventions as getters and setters.

**Comment by findmyway** [comment]
This is a follow up of https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/13 

I don't have a strong preference beteeen the two. But I admit that `get_` is kind of verbose. And it may be kind of strange that we only have `get_` but not `set_` .

> The name reward might become a little too overloaded if we use it to represent the field name reward, the method name reward to acquire that field, and often also the variable name reward to which this entity would be stored at the calling site of such a method (like reward = reward(env))

I think it's a convension that people usually use the fieldname as the function name to access some inner values.

**Comment by Sid-Bhatia-0** [comment]
From JuliaReinforcementLearning/CommonRLInterface.jl#13

>Let's say we want to define a state(env) function to get state from an environment. But state itself is just a noun and people (including me) may write
>```
>state = batch.state  # init the state
>Q(state, action)
># now I want to get the state in env, bang, error...
>next_state = state(env)
>```

As you already pointed out, this can lead to some serious bugs, right? This also leads to confusion about the type of entity a name binds to (method or quantity).
Thus, I think it is very much helpful to distinguish the quantity (noun) from the method (verb). And `get_` / `set_` is a useful and standard technique for achieving this.

>And it may be kind of strange that we only have `get_` but not `set_` .

We don't require a `set_` method corresponding to every `get_` method. There are some things (like the environment state) that obviously cannot be set arbitrarily by an outsider and so we do not have a `set_state!` method. But having a `get_state` method nevertheless keeps things consistent in this case.

>But I admit that `get_` is kind of verbose.
>I think it's a convension that people usually use the fieldname as the function name to access some inner values.

I agree with you that this is slightly verbose. It might be my lack of experience in Julia, but I would still like to express a strong concern and question the convention here. I'm afraid we might be gaining conciseness at the cost of losing clarity in this case.

I may be wrong and would be happy to get enlightened upon this, but apart from conciseness (that comes at the cost of clarity) and sticking to the convention (whose reasons I fail to grasp), I don't see any real advantage of deprecating `get_`. On the other hand, the disadvantages are already stated above.

**Comment by findmyway** [comment]
> As you already pointed out, this can lead to some serious bugs, right? 

Yes, but they are easy to detect and I decide to fix them all 😃 

> We don't require a set_ method corresponding to every get_ method.

Yes of course. But it tends to indicate that there's also a `set_*` method and actually we don't have...

> I'm afraid we might be gaining conciseness at the cost of losing clarity in this case.

Thanks for pointing this out. I think it's still worth making this change.

**Comment by Sid-Bhatia-0** [comment]
>Yes, but they are easy to detect and I decide to fix them all

I meant bugs on the user's side too 😅 

>But it tends to indicate that there's also a set_* method and actually we don't have...

Hmm... By the way, what about when we actually want to set the field? For example, I often need to set the reward in `GridWorlds.jl`. There `get_reward(env)` and `set_reward!(env)` seem to be intuitive and consistent. Whereas `reward(env)` and `set_reward!(env)` maybe not as much.

>I think it's still worth making this change.

Haha.. We have a disagreement here. But no problem. If you still feel that this change is worth it, go ahead. I'm with you 😊

**Comment by findmyway** [comment]
> I meant bugs on the user's side too 😅

Apologize in advance if these changes are too aggressive...

> Hmm... By the way, what about when we actually want to set the field? For example, I often need to set the reward in GridWorlds.jl. There get_reward(env) and set_reward!(env) seem to be intuitive and consistent. Whereas reward(env) and set_reward!(env) maybe not as much.

Well, in that case `set_reward!` is part of `GridWorlds.jl`, but `reward` is part of `RLBase`, so I think there's no conflicting here. You can always have a pair of `get_reward` and `set_reward!` in `GridWorlds.jl` and define a `RLBase.reward(env::GridWorld) = GridWorlds.get_reward(env)`.

>  If you still feel that this change is worth it, go ahead. I'm with you 😊

Thanks for your understanding. I'm open to all the suggestions. But we just have to make a decision and move on.

**Comment by Sid-Bhatia-0** [comment]
> You can always have a pair of `get_reward` and `set_reward!` in `GridWorlds.jl` and define a `RLBase.reward(env::GridWorld) = GridWorlds.get_reward(env)`.

Yes. Will do that. Thank you.

> Apologize in advance if these changes are too aggressive...
> But we just have to make a decision and move on.

No worries. We'll face it and see how it goes 👍🏽 

> I'm open to all the suggestions.

Let's keep this issue open for now, until the new release.
