### ISSUE TITLE
Train policy with GymEnv

### ISSUE THREAD

**Issue by rlrs** [JuliaReinforcementLearning/ReinforcementLearning.jl#175]
I'm having some issues training a policy (specifically using DDPG but it doesn't really matter to me) with GymEnv. Well, the first issue is that the environments expect vector actions and not scalars, but fixing this is likely more involved than just outputting a vector action from the policy (e.g. RLBase.update! needs to be changed?).

Is there an example of this working? I think Zoo doesn't have one.

**Comment by findmyway** [comment]
Unfortunately, we don't have an example of it yet. Though it has been discussed a long time ago https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/138

> but fixing this is likely more involved than just outputting a vector action from the policy (e.g. RLBase.update! needs to be changed?

Yes, the `gradient` part also needs to be changed. These are the only two places if you want to start from existing algorithms.

**Comment by findmyway** [comment]
DDPG should support mult action space now
