### ISSUE TITLE
Travis CI Credits

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/ReinforcementLearning.jl#178]
Hey @findmyway it seems like we are very out of build credits for travis: https://travis-ci.com/organizations/JuliaReinforcementLearning/plan Should I email them and request some OSS credits? https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

**Comment by findmyway** [comment]
Yeah I was planning to replace Travis with github actions. https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/151 (I used to hear the granted credit is still limited after requesting)

**Comment by zsunberg** [comment]
OK, I'll switch CommonRLInterface over to github actions
