### ISSUE TITLE
Unrecognized symbols

### ISSUE THREAD

**Issue by rcnlee** [JuliaReinforcementLearning/ReinforcementLearning.jl#180]
I'm seeing a number of unrecognized symbols in, for example, `RLZoo/ddpg.jl` `update!` function.  They are also not displaying properly on github: [ddpg.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/algorithms/policy_gradient/ddpg.jl)

Thanks!

**Comment by findmyway** [comment]
Hi @rcnlee  I can’t see any unrecognized symbols. 

![image](https://user-images.githubusercontent.com/5612003/103962440-e8a27200-5191-11eb-8bc5-02e0f42df7f1.jpeg)

I guess you may consider updating the fonts you're using. Or you can ask this question on stackoverflow or discourse instead.

@Sid-Bhatia-0 Do you remember how you fixed this problem last time?

**Comment by rcnlee** [comment]
Oh weird, the github page looks like this for me on Chrome (OSX).

![image](https://user-images.githubusercontent.com/7119868/103977646-8b290980-512e-11eb-9fef-b45ba845110c.png)

Macvim is also not showing it properly for me:

![image](https://user-images.githubusercontent.com/7119868/103977869-05f22480-512f-11eb-89ca-852c2e17d126.png)

**Comment by findmyway** [comment]
Give [JuliaMono](https://cormullion.github.io/pages/2020-07-26-JuliaMono/#installation) a try? 😉

**Comment by Sid-Bhatia-0** [comment]
> Do you remember how you fixed this problem last time?

I didn't 😅. I was facing it only with certain Unicode characters, most of which I didn't encounter too much.

By the way, this one shows up properly for me.

I am using:
```
julia> versioninfo(verbose = true)
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
      Ubuntu 18.04.3 LTS
  uname: Linux 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz: 
              speed         user         nice          sys         idle          irq
       #1  2717 MHz      23802 s         56 s       7402 s     116674 s          0 s
       #2  2724 MHz      24168 s        182 s       8584 s     115013 s          0 s
       #3  2768 MHz      23886 s         16 s       7752 s     117860 s          0 s
       #4  2765 MHz      23803 s         64 s       7546 s     116238 s          0 s
       
  Memory: 7.6693115234375 GB (1214.27734375 MB free)
  Uptime: 1593.0 sec
  Load Avg:  1.9365234375  2.5068359375  2.11669921875
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = /usr/bin/vim
  HOME = /home/sid
  WINDOWPATH = 2
  TERM = xterm-256color
  PATH = /home/sid/anaconda3/condabin:/home/sid/.local/bin:/home/sid/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sid/julia/julia-1.5.0/bin
```

On the Firefox browser:

![Screenshot from 2021-01-08 13-46-48](https://user-images.githubusercontent.com/32610387/103991326-8315ac00-51b8-11eb-837a-aa25714783ac.png)

And in vim:

![Screenshot from 2021-01-08 13-48-44](https://user-images.githubusercontent.com/32610387/103991344-87da6000-51b8-11eb-933b-dd28b818ad3a.png)

**Comment by rcnlee** [comment]
OK, thanks.  It is not showing up properly on my mac or android phone, but it's working on my ubuntu box.  I'm guessing the default fonts for those platforms are not adequate and I need to install a font with extended unicode support.

**Comment by rcnlee** [comment]
I solve it.  The issue is that the default Mac fonts, even though they support unicode in general, are missing those latin subscript unicode characters.  The solution is to install a font that does support it, such as Deja Vu.
