### ISSUE TITLE
define environment of FULL_ACTION_SET

### ISSUE THREAD

**Issue by dmteams** [JuliaReinforcementLearning/ReinforcementLearning.jl#184]
Hello,

I am currently trying to implement an environment FULL_ACTION_SET. 

Could you elaborate a bit about what these functions are supposed to return? How they interact with the trajectory? Or anything different in the implementation from MINIMAL_ACTION_SET?

`RLBase.get_legal_actions`
`RLBase.get_legal_actions_mask`

As far as I understood, get_legal_actions is simply another version of get_actions while get_legal_actions_mask is supposed to return an abstract array corresponding to the feasible actions. But as I do it, it seems like my trajectory CircularCompactSALRTSALTrajectory is asking for storing a boolean value. 

![image](https://user-images.githubusercontent.com/75791502/104858914-b7107000-5922-11eb-8b15-9e8dbded6148.png)

Many thanks in advance!

**Comment by findmyway** [comment]
Hi @dmteams ,

It seems you're using an old version of ReinforcementLearningEnvironments.jl. 

For environments of `FULL_ACTION_SET`, you can take a look at the implementation of [MontyHallEnv](https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/src/environments/examples/MontyHallEnv.jl)

If you want to understand when and how is the trajectory updated, then you can refer the source code:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/882d1025a5b6f84cbcfa6b758c2c44d9f86a5854/src/policies/agents/agent.jl#L40-L66

> Here we extend the definition of `(p::AbstractPolicy)(::AbstractEnv)` in
`RLBase` to accept an `AbstractStage` as the first argument. Algorithm designers
may customize these behaviors respectively by implementing:
> - `(p::YourPolicy)(::AbstractStage, ::AbstractEnv)`
> - `(p::YourPolicy)(::PreActStage, ::AbstractEnv, action)`
> The default behaviors for `Agent` are:
> 1. Update the inner `trajectory` given the context of `policy`, `env`, and
   `stage`.
>   1. By default we do nothing.
>   2. In `PreActStage`, we `push!` the current **state** and the **action** into
     the `trajectory`.
>   3. In `PostActStage`, we query the `reward` and `is_terminated` info from
     `env` and push them into `trajectory`.
>   4. For `CircularSARTTrajectory`:
>      1. In the `PosEpisodeStage`, we push the `state` at the end of an episode
        and a dummy action into the `trajectory`.
>      1. In the `PreEpisodeStage`, we pop out the lastest `state` and `action`
        pair (which are dummy ones) from `trajectory`.
> 2. Update the inner `policy` given the context of `trajectory`, `env`, and
   `stage`.
>   1. By default, we only `update!` the `policy` in the `PreActStage`. And it's
     despa


## Example

```julia
(test) pkg> add ReinforcementLearning#master

julia> agent = Agent(;
           policy = RandomPolicy(),
           trajectory = CircularArraySLARTTrajectory(;capacity=100, legal_actions_mask=Vector{Bool}=>(length(action_space(env)),))
       );

julia> env = MontyHallEnv();

julia> run(agent, env, StopAfterEpisode(1))
```

Well, I just found a bug when trying the example above. 😢 

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/185

Anyway, I think you can find your answer in the [agent.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/master/src/policies/agents/agent.jl) file. Let me know if you still have any problems.

**Comment by dmteams** [comment]
Great, thank you for the quick response. I will come back to you if it keeps being wrong

**Comment by dmteams** [comment]
Do you have any clue why I am using an old version of the package? I cannot access the trajectory that you are using in the example as well (I have only CircularCompact trajectories). I tried to reinstall the package but nothing has changed...

**Comment by dmteams** [comment]
Hi, so I followed your advice and had a look at the MontyHall example. 

Although, I keep having issues with the trajectory. :terminal and :reward is stored correctly but not :state, :action and :terminal. It was the same when I was running the RandomPolicy for my example (even though I suspect in this case that it is because we actually do not need to store :S, :A, :T). 

If I switch my environment to MINIMAL_ACTION_SET, then the SARTTrajectory works just as usual. 

Do you have any advice?
