### ISSUE TITLE
CircularArraySLARTTrajectory instance is not of type CircularArraySLARTTrajectory

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#185]
```julia
julia> trajectory = CircularArraySLARTTrajectory(;capacity=100, legal_actions_mask=Vector{Bool}=>(length(action_space(env)),))
Trajectory of 5 traces:
:state 0-element CircularArrayBuffers.CircularArrayBuffer{Int64,1}
:action 0-element CircularArrayBuffers.CircularArrayBuffer{Int64,1}
:legal_actions_mask 3×0 CircularArrayBuffers.CircularArrayBuffer{Bool,2}
:reward 0-element CircularArrayBuffers.CircularArrayBuffer{Float32,1}
:terminal 0-element CircularArrayBuffers.CircularArrayBuffer{Bool,1}


julia> trajectory isa CircularArraySLARTTrajectory
false
```

Should be fixed by switching the two lines:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/882d1025a5b6f84cbcfa6b758c2c44d9f86a5854/src/policies/agents/trajectories/trajectory.jl#L103-L104

**Comment by dmteams** [comment]
Are you sure that it is enough? Because it is still not working after modification in my case...

**Comment by dmteams** [comment]
![image](https://user-images.githubusercontent.com/75791502/105411365-9a7e7b80-5c33-11eb-815f-3cf8138a84d7.png)

**Comment by findmyway** [comment]
No, I haven't tested it yet.

PR is welcomed if you find the solution.

**Comment by dmteams** [comment]
A small mistake in the definition of the type SLART. See

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/882d1025a5b6f84cbcfa6b758c2c44d9f86a5854/src/policies/agents/trajectories/abstract_trajectory.jl#L63[](url)

:next_state has to be removed.
I let you change this since I don't know yet how to PR.

**Comment by dmteams** [comment]
A small mistake in the definition of the type SLART. See

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/882d1025a5b6f84cbcfa6b758c2c44d9f86a5854/src/policies/agents/trajectories/abstract_trajectory.jl#L63[](url)

:next_state has to be removed.

**Comment by findmyway** [comment]
💯 

Would you mind opening a PR and also add a test case?

**Comment by dmteams** [comment]
Yes, I will do it a bit later today

**Comment by ilancoulon** [comment]
I am glad I just found this issue! I have been struggling with this for way too long!
I will do a PR later today
