### ISSUE TITLE
loadenvironment error

### ISSUE THREAD

**Issue by tejank10** [JuliaReinforcementLearning/ReinforcementLearning.jl#19]
Hi! I was playing with the package, trying out the usage [examples](https://juliareinforcementlearning.github.io/ReinforcementLearning.jl/latest/usage/) from the docs. I am getting `UndefVarError` for example 2 on line 3, which says `loadenvironment("cartpole")`
```
ERROR: UndefVarError: loadenvironment not defined
Stacktrace:
 [1] top-level scope at none:0
```
I also could not find any reference to `loadenvironment` function in the codebase, except for in docs. Is it replaced with new function? Any hints?

**Comment by findmyway** [comment]
Hi @tejank10 

Glad to see you here :smile: 

@jbrea  made some modifications recently. The document seems also need to be updated(but I guess he is really busy in the next few days.). AFAIK @jbrea just updated the examples of each supported environment yesterday, you may take a look at the example folder of each environment project there.

Notice that @jbrea 's PR are not merged yet. I'll update those PR and merge them soon.

1. https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironmentClassicControl.jl/pull/2/files

**Comment by jbrea** [comment]
The docs were outdated, thanks @tejank10. They are updated now, but the examples don't work with master until PRs #17, #18 are resolved.

**Comment by findmyway** [comment]
Closing this issue since `loadenvironment` is now deprecated.
