### ISSUE TITLE
Is hook the same thing as "callback"?

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#190]
Looking at the new docs (which are very nice btw!) I see you use "hook":
https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_core/#ReinforcementLearningCore.AbstractHook

Is that the same thing as "callback" or is it more powerful somehow?

**Comment by findmyway** [comment]
As I explained [here](https://juliareinforcementlearning.org/get_started/#hook),  I think they are the same with the [two way callbacks](https://www.fast.ai/2020/02/13/fastai-A-Layered-API-for-Deep-Learning/#callback) in fastai. The name `AbstractHook` is kept only for historical reasons.

**Comment by drozzy** [comment]
I see, that makes sense. 
Not sure a callback needs a special name. 
But I'm not a fan of fastai, so take my opinion with a grain of salt. 

I'll close this since it sounds like I'm just bikeshedding.
