### ISSUE TITLE
Blog custom env link typo

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#192]
In the [custom env blog post](https://juliareinforcementlearning.org/blog/how_to_write_a_customized_environment/), just under "The Minimal Interfaces to Implement" the link probably didn't link properly:

`[ReinforcementLearningBase.jl][] `

**Comment by findmyway** [comment]
Thanks. Updated in https://github.com/JuliaReinforcementLearning/JuliaReinforcementLearning.github.io/pull/23

**Comment by findmyway** [comment]
@all-contributors add @drozzy  for doc
