### ISSUE TITLE
Why "examples"?

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#198]
Just curious why some environments are categorized as "3rd-party" and some are "examples"?

https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/tree/master/src/environments/3rd_party
https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/tree/master/src/environments/examples

**Comment by findmyway** [comment]
Environments under the *examples* folder are meant to be

- Written in pure Julia with minimal dependencies
- Easy to understand
- Typical to cover some specific characteristics (traits defined in RLBase)

On the contrary, environments under the 3-rd party

- May be written in Julia with large dependencies or even other languages (python, c/c++, ...)
- Only workable on some platforms
- Just wrappers around some other existing environment.

**Comment by drozzy** [comment]
Perhaps `simple`?

Yeah it's pretty hard to come up with a good name for this. Nvm haha.
