### ISSUE TITLE
Support alternative deep learning libraries

### ISSUE THREAD

**Issue by jbrea** [JuliaReinforcementLearning/ReinforcementLearning.jl#20]
Is it easy to write the RL part such that each user can still choose the favorite DL framework?
Currently DQN is expects a [Flux](https://github.com/FluxML/Flux.jl) model. But it could be interesting to support also [Tensorflow](https://github.com/malmaud/TensorFlow.jl) or [Knet](https://github.com/denizyuret/Knet.jl) models.

**Comment by findmyway** [comment]
I think users can just add a customized model from now on. But I'll investigate it later.
