### ISSUE TITLE
Add default implementations for AbstractEnvWrapper

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#202]
So that we can remove those `for ... @eval ...` loops in each environment wrapper.

**Comment by kamalojasv181** [comment]
Hi, I would like to take this. @findmyway. Can you please elaborate the task and the motivation a little more?

**Comment by findmyway** [comment]
Hi @kamalojasv181 ,

That's great! I add more details below.

# Motivation

Under the [wrappers subfolder of ReinforcementLearningEnvironments.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/tree/master/src/environments/wrappers), each concrete subtype of `AbstractEnvWrapper` has some duplicate code like this:

```julia
for f in vcat(RLBase.ENV_API, RLBase.MULTI_AGENT_ENV_API)
    if f ∉ (:action_space, :legal_action_space)
        @eval RLBase.$f(x::ActionTransformedEnv, args...; kwargs...) =
            $f(x.env, args...; kwargs...)
    end
end
```

Copied from [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/4b3d39e68c87e5b4add1bd526671801a65193550/src/environments/wrappers/ActionTransformedEnv.jl#L24-L29)

The idea behind is to make the wrapper behaves like an `AbstractEnv`, so that interfaces like `is_terminated(wrapper)` automatically fallbacks to the underlying `AbstractEnv`. But it is tedious to write such a  `for` loop for each wrapper. We can add some default implementations for the `AbstractEnvWrapper` so that for each concrete subtype of `AbstractEnvWrapper`, we only need to implement the more specific methods.

# How?

First, we have to add a new method for `AbstractEnvWrapper` to get the underlying `AbstractEnv`. By following the suggestions [here](https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/40), we can implement the `Base.getindex(wrapper::AbstractEnvWrapper) = wrapper.env`. 

Then we can write a similar `for` loop like the above one of `AbstractEnvWrapper` instead of the `ActionTransformedEnv`.

One last thing is to remove existing `for` loops for each wrapper and make sure tests pass.

**Comment by findmyway** [comment]
Fixed in https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/pull/127
