### ISSUE TITLE
"Getting Started" too long imo

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#210]
I think getting started section is way too long. 
It should be a piece of code that is self explanatory:
https://stable-baselines3.readthedocs.io/en/master/guide/quickstart.html

I think the docs should be of two types: 
1. quick-reference so people can come. look. copy and paste.
2. deep, insightful architectural descriptions - so people can read how to change things.

I find acme is too much of number 2, for example.
Feel free to close this, just random thoughts.

**Comment by zsunberg** [comment]
To build on this "two types" idea, I have found the following categorization useful: https://documentation.divio.com/

**Comment by findmyway** [comment]
Hi @drozzy ,

Thanks for your feedback! I'll consider making it more concise later.



> To build on this "two types" idea, I have found the following categorization useful: https://documentation.divio.com/

@zsunberg  Thanks for sharing this link. Coincidently, @jbrea also recommended it to me some time ago 😄 . To be honest I'm really not very good at writing documentations...

**Comment by drozzy** [comment]
I like the @zsunberg link, I think those 4 sections make sense.
We can fill them up as they come.

I think current sections can be renamed:
1. "Blog" -> "Tutorials"
2. "Getting Started" -> "Tutorials > Getting Started" (also under tutorials)
3. "Guide" -> "Guides" (plural)
4. The [thoughts](https://juliareinforcementlearning.org/blog/an_introduction_to_reinforcement_learning_jl_design_implementations_thoughts/) page should go under "Information"
5. The [how to write custom env](https://juliareinforcementlearning.org/blog/how_to_write_a_customized_environment/) page should go under "Guides -> How to write customized environment" guide.

I would move things around but I don't want to mess things up haha.
