### ISSUE TITLE
What's a "trace"?

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#213]
Just reading the [docs](https://juliareinforcementlearning.org/blog/an_introduction_to_reinforcement_learning_jl_design_implementations_thoughts/) and just below the pretty animation figure for trajectories there is a sentence:

>  It contains four traces: state, action, reward and terminal. Each trace simply use a Vector as the container.

What are "traces"? I think I missed it as there was no description of this term earlier.

**Comment by drozzy** [comment]
Is there any relation to "Eligibility Traces"?

**Comment by drozzy** [comment]
Don't think so.

**Comment by findmyway** [comment]
A *trace* to *Trajectory* is similar to a *column* to a *DataFrame*, I think.

**Comment by drozzy** [comment]
I've never heard that to be honest, but you know better.

**Comment by findmyway** [comment]
In most papers, `trace` is used to name a sequence like `s, a, s, a, ... , `. So maybe `subtract is a better word here.

<hr>

To make a comparison with the [deepmind/reverb](https://github.com/deepmind/reverb)

![image](https://user-images.githubusercontent.com/5612003/111038260-ff4f9880-8462-11eb-84c2-46c2cc5d6c85.png)

In reverb, `data` and `table` are separated. `data` is close to most common `Trajectory` in `RL.jl`. The whole `ReverbServer` is represented as some specialized `Trajectory` in RL.jl (for example, `CircularPSARTTrajectory`).

**Comment by drozzy** [comment]
I see here distinction between EpisodeAdder and SequenceAdder - but I'm not sure that's the same.

So would a whole trajectory also be a trace?

I am not against the terminology, just think the docs should explain it.

**Comment by findmyway** [comment]
> So would a whole trajectory also be a trace?

Yes, that's possible. An example will be provided later.
