### ISSUE TITLE
Docs looks ugly in dark mode

### ISSUE THREAD

**Issue by JinraeKim** [JuliaReinforcementLearning/ReinforcementLearning.jl#217]
Hi,
the Docs of this package looks ugly in dark mode.
Note that I'm working on m1 MacbookAir with BigSur.

- Example

![image](https://user-images.githubusercontent.com/43136096/111702245-4ed8fe80-887f-11eb-8b5a-2fdef3e026b3.png)

**Comment by findmyway** [comment]
It seems to be fixed now.

**Comment by JinraeKim** [comment]
@findmyway Sorry but I don't think so.
Please see [this page](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_envs/#ReinforcementLearningEnvironments.MultiArmBanditsEnv-Tuple{}).

Screenshot that I just took:
![Uploading image.png…]()

**Comment by findmyway** [comment]
Sorry, the link hasn't been updated yet. (WIP: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/270)

See the new link to the doc:

https://juliareinforcementlearning.org/docs
