### ISSUE TITLE
Add Discrete Batch-Constrained Deep Q-learning

### ISSUE THREAD

**Issue by Mobius1D** [JuliaReinforcementLearning/ReinforcementLearning.jl#226]
This offline RL algorithm performs much better than many existing RL algorithms and it would be good to have it implemented in the RLZoo.jl 

<img width="957" alt="image" src="https://user-images.githubusercontent.com/49596933/113263254-2a553b80-92ef-11eb-979e-9c36d4f93335.png">

I would like to take up this issue and the implementation will be based on: https://arxiv.org/pdf/1910.01708.pdf

**Comment by findmyway** [comment]
Cool. Just go ahead and raise any questions here.

**Comment by pilgrimygy** [comment]
I am also very interested in offline reinforcement learning, which is a very promising field. Can I ask you more?
