### ISSUE TITLE
The components of Rainbow

### ISSUE THREAD

**Issue by pilgrimygy** [JuliaReinforcementLearning/ReinforcementLearning.jl#229]
The composition of Rainbow contains the following:
1.Double DQN
2.Prioritized Experience Replay
3.Dueling Network
4.Noisy Network
5.Categorical DQN
6.N-step Learning
Actually, only 2, 5, and 6 have been completed. Do you think other implementations are necessary? If yes, I can help implement it.

**Comment by findmyway** [comment]
Yes, that would be useful.

**Comment by Mobius1D** [comment]
If I am not wrong, 1 is also implemented isn't it?

It's just a small change in the target value.

I would also like to implement some of the other algorithms and write some experiments, if it's possible.

I will sure post what I would be working on so that we don't simultaneously work on the same thing.

**Comment by pilgrimygy** [comment]
Yes, you are right. It did in DQN, it doesn't seem to have in Rainbow.

We can all share our ideas in advance and help each other. What have you been doing lately?

**Comment by Mobius1D** [comment]
Sure mate, it's easier to implement if we collaborate. Been busy as of now, would be able to contribute within 2-3 days. 

What about you, I saw your work in REM online version, pretty impressive. Amazing work.

**Comment by pilgrimygy** [comment]
In Rainbow, are there any components you would like to implement?

**Comment by Mobius1D** [comment]
I would like to take up duelling and double now if its fine with you.

**Comment by pilgrimygy** [comment]
I would also like to try to implement the Dueling network, which is very interesting. Maybe we can implement it first and push it on our GitHub.

**Comment by Mobius1D** [comment]
Are you suggesting that we both implement it independently and upload it on our GitHub forks?

**Comment by pilgrimygy** [comment]
Yes, I'd love to see how you implement it. We can compare performance and learn from each other.

**Comment by Mobius1D** [comment]
Would be good. It would take some time for me tho, kinda held up, but would be a fun exercise 😋.

Btw, are you in the slack channel?

**Comment by pilgrimygy** [comment]
Yes, what your name in the slack?

**Comment by Mobius1D** [comment]
Great, name's Prasidh Srikumar, what's urs?

**Comment by pilgrimygy** [comment]
@findmyway I implemented a dueling network. The performance is similar in DQN, but the performance in Rainbow is very poor. I can't figure out the reason, can you help me?

**Comment by findmyway** [comment]
> @findmyway I implemented a dueling network. The performance is similar in DQN, but the performance in Rainbow is very poor. I can't figure out the reason, can you help me?

Sorry, but how could I help you without seeing your code?

**Comment by pilgrimygy** [comment]
> > @findmyway I implemented a dueling network. The performance is similar in DQN, but the performance in Rainbow is very poor. I can't figure out the reason, can you help me?
> 
> Sorry, but how could I help you without seeing your code?

I finish it (dueling network) and test the performance:
![avatar](https://www.hualigs.cn/image/6070159f5e3d9.jpg)
Blue curve: add dueling network.
Can I make a PR?
