### ISSUE TITLE
Source links in documentation directs to julia repo

### ISSUE THREAD

**Issue by albheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#231]
The links when clicking source on `ActorCritic` or `Agent` in [this](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_core/#ReinforcementLearningCore.ActorCritic) list will direct to some weird [place](https://github.com/JuliaLang/julia/tree/788b2c77c10c2160f4794a4d4b6b81a95a90940c/base#L0-L4) in the julia repo. 

I assume this is not supposed to work like this. Seems like most entries in the list does not have the source link, so maybe they are not supposed to be there? Though having a button to jump to the source is very nice in my opinion if it is easy to link everything automatically.

**Comment by findmyway** [comment]
This is a known bug reported here https://github.com/JuliaDocs/Documenter.jl/issues/1251

**Comment by findmyway** [comment]
However, maybe we can genetated the doc for each package independently and put them together.

**Comment by findmyway** [comment]
The source links are correct now.
