### ISSUE TITLE
SAC and GaussianNetwork

### ISSUE THREAD

**Issue by albheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#236]
Saw that SAC reimplements its own version of gaussian network, thought it was a bit unnecessary.

SACPolicyNetwork:
https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/d53a017827d346a0cbfbda8e2ea9080aec54c086/src/algorithms/policy_gradient/sac.jl#L4-L10

GaussianNetwork:
https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/bc64e422fe720b5040fbeb8f27cc62f45b1e894a/src/algorithms/policy_gradient/vpg.jl#L8-L19

Was going to replace it when I realised that I thought the notation for the GaussianNetwork was confusing. 

Creating a GaussianNetwork looks something like this
```julia
policy = GaussianNetwork(
    pre = Chain(
        Dense(ns, 64, relu),
        Dense(64, 64, relu),
    ),
    μ = Chain(Dense(64, 1, tanh)),
    σ = Chain(Dense(64, 1, x -> clamp(x, low, high))),
)
```
where σ is not really the standard deviation if you would like to apply some final transformation like clamping, but rather the log of the standard deviation. But what you get out from the network is the standard deviation because when `policy(state)` is called it returns the exponentiated value. My first thought is that the easiest would be to call the field logσ instead and not automatically apply exponentiation, just let people do that afterwards instead.

**Comment by findmyway** [comment]
> My first thought is that the easiest would be to call the field logσ instead and not automatically apply exponentiation, just let people do that afterwards instead.

👍  That would be more clear.

cc @rbange

**Comment by rbange** [comment]
Absolutely agree. Both implementations make sense, but i would prefer the `logσ` style.

This probably relates to this issue too https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/139.
