### ISSUE TITLE
Precompilation prohibitively long

### ISSUE THREAD

**Issue by AlexLewandowski** [JuliaReinforcementLearning/ReinforcementLearning.jl#237]
Precompilation for ReinforcementLearningEnvironments is long - longer than other, more complex, packages like Flux. I'm not sure if this is due to the sparsely used dependencies, like OrdinaryDiffEqs and GR, or maybe due to the @require statements for the optional envs. In any case, I think some of these dependencies can be removed. The ODE package is used only once to solve runge-kutta equations in acrobot and GR is used to plot mountaincar and cartpole. While these featuers are useful, I am not sure if it warrants such long precompilation times.

**Comment by findmyway** [comment]
Thanks for pointing this out. This has been a headache to me for a long time and I was intended to tackle it after Julia@v1.6
Let me investigate all the dependencies first. 
Personally, I prefer to move some parts of them (like ODE and GR) into lazy loading.

**Comment by findmyway** [comment]
The precompile time is reduced to ~2s now.
