### ISSUE TITLE
[Call for Contributors] Summer 2021 of Open Source Promotion Plan

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#242]
I get some fundings from [Summer 2021 of Open Source Promotion Plan](https://summer.iscas.ac.cn/help/en/) recently and would like to have more students contribute to this org. It works more or less the same with GSoC, except that it's more flexible (with a slightly lower stipend). Please contact me if you are interested in this program.

**Comment by ashwani-rathee** [comment]
I saw this project on "Implement Multi-Agent Reinforcement Learning Algorithms in Julia" in OSPP and it interests me because you know in games agents fight. I have fiddled around with this in past(https://www.linkedin.com/posts/ashwani-rathee-0b7594192_backtobasics-interestingusecases-activity-6691363925855936513-DCq5)  and also being a taekwondo student it's pretty meaningful to me. I wanted to ask what you are looking for the potential mentee for this particular project.

**Comment by findmyway** [comment]
Hi @ashwani-rathee ,

Thanks for reaching out.

For the project [Implement Multi-Agent Reinforcement Learning Algorithms in Julia](https://summer.iscas.ac.cn/#/org/prodetail/210370190?lang=en) , we're looking for students to have some common benchmarks in multi-agent reinforcement learning implemented. Although I've put some typical algorithms there, we can still adjust the project goal based on the student's interest and familiarity with RL and Julia. So it would be better for you to put forward some algorithms you'd like to work on first. Then I'll help to evaluate the workload and discuss more detailed work items with you.

**Comment by ashwani-rathee** [comment]
Algorithms you mentioned in the project proposal are all top notch. I find MADDPG and MAPPO to be interesting to me and have enough conversation around them, so there's lot of help I guess 😄 .

**Comment by findmyway** [comment]
Cool, [the registration](https://portal.summer-ospp.ac.cn/summer/login?lang=en_US) system will open the next Monday. You can start working on a draft proposal first and we can keep improving it before the deadline (Jun 13th).

**Comment by findmyway** [comment]
Please aware that the registration is open now. The deadline to submit a proposal is Jun 13th.

https://portal.summer-ospp.ac.cn/summer/login?lang=en_US

**Comment by findmyway** [comment]
I'm closing this now since the application deadline has passed.
Some details can be found here: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/discussions/324
