### ISSUE TITLE
ReinforcementLearningZoo.jl experiments

### ISSUE THREAD

**Issue by luigiannelli** [JuliaReinforcementLearning/ReinforcementLearning.jl#245]
Some experiment listed in "List of built-in experiments" are not in the source code folder https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/tree/master/src/experiments, like for example E`JuliaRL_VPG_Pendulum` , where can i find them?

**Comment by findmyway** [comment]
That experiment seems to be removed at some time and the README is not updated. Thanks for reporting.

**Comment by findmyway** [comment]
@all-contributors please add @luigiannelli for bug.
