### ISSUE TITLE
PPO and multi dimensional actions spaces

### ISSUE THREAD

**Issue by luigiannelli** [JuliaReinforcementLearning/ReinforcementLearning.jl#251]
`::PPOPolicy` always returns a scalar, also if it is defined for multi dimensional actions:
```
julia> policy(inner_env)
-0.6246452f0
```
That's a bug in https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/022c1fd433911dcaedf3ff38b4bfb6351c544497/src/algorithms/policy_gradient/ppo.jl#L176
Previously that code only supports single dimension action space.

**Comment by findmyway** [comment]
Not sure whether @albheim would be interested in fixing this bug 🤔
If not, I may come to fix it after https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/252 .

**Comment by albheim** [comment]
Woops, miss by me. I use a MultiThreadEnv for my own research experiments and used that to test against so this one slipped by untested. Can absolutely have a look, seems like it should be a rather quick fix.

**Comment by findmyway** [comment]
When applying PPO on general environments (the one wrapped in the MultiThreadEnv), we simply return the action instead of `EnrichedActions`. `EnrichedActions` will only be useful during training.

**Comment by albheim** [comment]
Oh, so we assume that training will always be done with `MultiThreadEnv`, and if called with other envs it is just for eval. Seems reasonable, then it should be much easier.

**Comment by findmyway** [comment]
> Oh, so we assume that training will always be done with `MultiThreadEnv`, and if called with other envs it is just for eval. Seems reasonable, then it should be much easier.

Exactly
