### ISSUE TITLE
[RLEnvs] easy access of the length of an action vector (dimension of action space)

### ISSUE THREAD

**Issue by JinraeKim** [JuliaReinforcementLearning/ReinforcementLearning.jl#257]
As in [JuliaRL_BC_CartPole.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/17c9d195f583582ca918e4e185e86f0526f248d4/src/experiments/rl_envs/JuliaRL_BC_CartPole.jl#L20),
we often need the length of an action vector.
However, for some continuous-action environments, it seems not straightforward to obtain the length of an action vector.

How about specifying the dimension of action spaces by adding a field of each environment?
Or, providing a method for getting it.

**Comment by findmyway** [comment]
The return of `action_space` is undefined in `RLBase`. Sometimes, the result may be of a composite type, making functions like `length` or `size` meaningless.

So I prefer to extract necessary information based on the return of the `action_space` instead of providing a dedicated function.

**Comment by JinraeKim** [comment]
I agree with you.
However, when using [IntervalSets](https://github.com/JuliaMath/IntervalSets.jl), it may be annoying to get the dimension of action space. I mean, it seems hard to get the dimension of action space in a consistent way.

For example, one would define (`d`-dimensional) action space with `d` > 1 as, for example, `action_space = Space(ClosedInterval.(_action_min, _action_max))` with vectors `_action_min` and `_action_max`.
In this case, one may be able to get the dimension as `length(endpoints.(action_space(env)))`.
However, when `d` = 1, it doesn't work.

Or, do you have a good idea to resolve the issue? Please share your ideas :)

**Comment by zsunberg** [comment]
Is a vector of ClosedIntervals really the best way to represent a multidimensional action space? Then you have `rand(action_space(env))` returning a `ClosedInterval`. Surely that is not what we want.

I think we need a dedicated multi-dimensional space type. It is probably worth creating a package for this if it does not already exist somewhere. It would be useful for POMDPs.jl also for instance

**Comment by JinraeKim** [comment]
@zsunberg Yes, I totally agree with you :)

**Comment by findmyway** [comment]
I created a new issue to track it: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/268
