### ISSUE TITLE
What's the `checkpoints`?

### ISSUE THREAD

**Issue by JinraeKim** [JuliaReinforcementLearning/ReinforcementLearning.jl#261]
When running predefined experiments such as [JuliaRL_DDPG_Pendulum](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/experiments/rl_envs/JuliaRL_DDPG_Pendulum.jl), I realised that it automatically creates directory `checkpoints` and save some logs.

What's it? And how to use it?

**Comment by findmyway** [comment]
https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/17c9d195f583582ca918e4e185e86f0526f248d4/src/experiments/rl_envs/JuliaRL_DDPG_Pendulum.jl#L14

It's used to save the tf log data currently. (Previously we also save model parameters here)
