### ISSUE TITLE
Model based reinforcement learning

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#262]
After taking a look into [facebookresearch/mbrl-lib](https://github.com/facebookresearch/mbrl-lib) . I think our current design is flexible enough to implement most algorithms in it. It's just that we need to standardize some interfaces.

- [A SURVEY ON MODEL-BASED REINFORCEMENT LEARNING](https://arxiv.org/pdf/2206.09328.pdf)

**Comment by albheim** [comment]
Just mentioning that I have started looking at this a little. Not promising anything or saying that anyone else shouldn't try to make it, but might have a PR for at least one of the algorithms soon and I'm interested in the other stuff too so might have a go when there is time.

I had some question about organization of the stuff, but I think we can tackle that in the PR when I have also thought through it a bit more.
