### ISSUE TITLE
Lack of reproducibility of QRDQN CartPole Experiment.

### ISSUE THREAD

**Issue by Mobius1D** [JuliaReinforcementLearning/ReinforcementLearning.jl#281]
![Screenshot from 2021-05-12 18-46-12](https://user-images.githubusercontent.com/49596933/117982921-1b34c500-b354-11eb-8031-8673d3a6426a.png)
![Screenshot from 2021-05-12 18-48-05](https://user-images.githubusercontent.com/49596933/117982929-1cfe8880-b354-11eb-9fc3-ed2b915413db.png)

**Comment by findmyway** [comment]
The `rng` is not passed to the initializer. A PR is welcomed.

**Comment by ashwani-rathee** [comment]
I would like to take this up

**Comment by findmyway** [comment]
Note that the file is now moved here: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningExperiments/deps/experiments/experiments/DQN/JuliaRL_QRDQN_Cartpole.jl
