### ISSUE TITLE
Reinforcement Learning.jl in a RTS

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaReinforcementLearning/ReinforcementLearning.jl#291]
Hey @findmyway, I want to ask if there are any existing projects that use ReinforcementLearning.jl in a real game like Minecraft, 0 a.d., dota2 etc. I am quite interested in this topic and would love to explore this.
For mincraft, there is proper malmo project: https://github.com/microsoft/malmo , project is under MIT license but mincraft itself isn't itself open source. Malmo has like some pieces of mincraft to create scenarios.
There is none for 0 a.d. but its kind of an equivalent of  AOE and it has clean nice scenario editor. And it's open source, so worth a look imo.

I wanted to ask about your thoughts on this topic 😄

**Comment by findmyway** [comment]
Hi @ashwani-rathee ,

Until now, I'm not aware of any projects that use this package to play games as you listed above.
I've investigated malmo about a year ago. TBH, I really didn't know how to write a native julia wrapper for it. (Just take a look at it again, I'm wondering if it is still been maintained?)
So generally, if we can communicate with those games in Julia, them we can always apply algorithms in this package somehow.
