### ISSUE TITLE
Plotting CartPole environment in Jupyter 

### ISSUE THREAD

**Issue by jamblejoe** [JuliaReinforcementLearning/ReinforcementLearning.jl#306]
```
cartpole_env = ReinforcementLearningEnvironments.CartPoleEnv()
plot(cartpole_env)
plot()
```
Last `plot()` is needed to invoke plotting. `GR.plot(env::CartPoleEnv)` does return `nothing`, so no plot is shown in the notebook, I would fix but I dont know how `GR` works.

**Comment by findmyway** [comment]
You can simply call `RLEnvs.plot(cartpole_env)`.

I'll work on https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/246 soon.
