### ISSUE TITLE
Local development environment setup tips causing error

### ISSUE THREAD

**Issue by albheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#320]
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/dc54ba44ea955d0d50c23be7c5d06912a0900a86/docs/src/tips.md#L10-L16

Running `dev .` in the folder of the currently active project seems a bit odd, seems like it would create some recursive dependency, and it generates an error for me. 

Was the intention to add the cloned folder to some other environment (i.e. same instructions without the `--project`)? Why not just do `dev ReinforcementLearning` and then you get the whole repo in .julia/dev/ReinforcementLearning and can edit it as you want there?

**Comment by albheim** [comment]
Ahh, read the line above about the dependents not being in development mode if done as I mentioned. But then you can just run

```julia
pkg> dev ReinforcementLearning ReinforcementLearningZoo ReinforcementLearningBase # Add more if you want more
```
And it will install it in `.julia/dev/ReinforcementLearning` and the sub packages will find this install and use it so you have one central location. And I guess the same can work if you prefer to clone the repo yourself and place it somewhere else.

Also spotted a few spelling mistakes in the same file
* favourate -> favourite/favorite
* usuall -> usual
* Node that this file -> Note that this file

**Comment by findmyway** [comment]
> Ahh, read the line above about the dependents not being in development mode if done as I mentioned. But then you can just run
> 
> ```julia
> pkg> dev ReinforcementLearning ReinforcementLearningZoo ReinforcementLearningBase # Add more if you want more
> ```
> 
> And it will install it in `.julia/dev/ReinforcementLearning` and the sub packages will find this install and use it so you have one central location. And I guess the same can work if you prefer to clone the repo yourself and place it somewhere else.

Yes, you're absolutely right here. Thanks for pointing this out.

> Also spotted a few spelling mistakes in the same file
> 
> * favourate -> favourite/favorite
> * usuall -> usual
> * Node that this file -> Note that this file

❤️ 
I'll fix them later tonight.

**Comment by findmyway** [comment]
@all-contributors please add @albheim for doc
