### ISSUE TITLE
Rename some functions to help beginners navigate source code

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#326]
I only realize this problem very recently. Multiple dispatch seems to be overused here in this package. For example, the `update!` function. I thought it was quite straightforward. When we want to update a policy during interactions with environments, we collect all the necessary information and then narrow them down layer by layer. Just like peeling the onions. And `update!(x, y, z...)` is usually read as *please update `x` given `y` and `z`*. Unfortunately different implementations are split accross many different files, which makes it hard for beginners to understand the code structure.

So before we have a smarter IDE to jump between such function calls, we'd better name them more clearly.

**Comment by JinraeKim** [comment]
For me, it's a kind of entry barrier for Julia packages (due to multiple dispatch); hard to navigate the source codes.
So it would be quite helpful for beginners although people who are already familiar with this concept may not need it.
