### ISSUE TITLE
Question about PER

### ISSUE THREAD

**Issue by oysteinsolheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#328]
In  for example 
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningZoo/src/algorithms/dqns/prioritized_dqn.jl
only the β_priority is assigned and used as in section 3.4 in https://arxiv.org/pdf/1511.05952.pdf and in the code:
```
w = 1.0f0 ./ ((batch.priority .+ 1f-10) .^ β)
w ./= maximum(w)
```
However, the α-paramter (Eq. 1 in the above paper) is not included at all. But from the code,
`updated_priorities .= send_to_host(vec((batch_losses .+ 1f-10) .^ β))`
 it seems also that the β_priority is thus used both for the importance weights and also as the α . Is this correct?

Best regards,
Oystein

**Comment by findmyway** [comment]
Yes, you're right. The implementation here is to align with that in dopamine:

https://github.com/google/dopamine/blob/90527f4eaad4c574b92df556c02dea45853ffd2e/dopamine/jax/agents/rainbow/rainbow_agent.py#L26-L30

https://github.com/google/dopamine/blob/90527f4eaad4c574b92df556c02dea45853ffd2e/dopamine/jax/agents/rainbow/rainbow_agent.py#L378-L385

So to reproduce the exact same result, you may need to modify that part to take the alpha into account.

**Comment by oysteinsolheim** [comment]
Thank you! I wasn't aware of that dopamine implementation. Nice to know! :-)
