### ISSUE TITLE
Docs error in code output

### ISSUE THREAD

**Issue by albheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#332]
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/89fa6704e653f66c93ca6456998db1b99b0152e9/docs/src/How_to_write_a_customized_environment.md#L235-L237

Gives the output `ERROR: UndefVarError: subtypes not defined`
https://juliareinforcementlearning.org/docs/How_to_write_a_customized_environment/#[StateStyle](@ref)

**Comment by findmyway** [comment]
Thanks!
