### ISSUE TITLE
Problem with running initial tutorial. Using `TabularPolicy()` generates an `UndefinedKeyword` error for `n_action`

### ISSUE THREAD

**Issue by 00krishna** [JuliaReinforcementLearning/ReinforcementLearning.jl#354]
I was just trying out the Reinforcement Learning package and doing some of the inital tutorials. I was I trying out the `TabularPolicy` example below, but I am getting a confusing error. 

Here is the code. 

```
julia> NS, NA = length(S), length(A)
(7, 2)

julia> policy = TabularPolicy(;table=Dict(zip(1:NS, fill(2, NS))))
typename(TabularPolicy)
├─ table => typename(Dict)
└─ n_action => typename(Nothing)
```

The stacktrace for the error I am getting is:
```
julia> policy = TabularPolicy(;table=Dict(zip(1:NS, fill(2, NS))))
ERROR: UndefKeywordError: keyword argument n_action not assigned
Stacktrace:
 [1] top-level scope
   @ REPL[12]:1
```

That isall the detail provided. 

I am using Julia version 1.6.1 on ubuntu linux 20.04.

**Comment by findmyway** [comment]
Hi @00krishna ,

It seems you have an old version of RL.jl installed.

Could you provide more details by following https://juliareinforcementlearning.org/docs/FAQ/#I-get-an-error-when-trying-examples-in-the-doc

**Comment by findmyway** [comment]
@all-contributors please add @00krishna for bug

**Comment by 00krishna** [comment]
Thanks all. Yes, I just tried this and it works. Thanks for the help with fixing it.
