### ISSUE TITLE
prob question for QBasedPolicy

### ISSUE THREAD

**Issue by peterchen96** [JuliaReinforcementLearning/ReinforcementLearning.jl#360]
I find that when computing [prob(p::QBasedPolicy, env::AbstractEnv, action)](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/c7b66e47e939592045326485b9c89b1486df165d/src/ReinforcementLearningCore/src/policies/q_based_policies/q_based_policy.jl#L37), it will use [prob(s::GreedyExplorer, values)](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/c7b66e47e939592045326485b9c89b1486df165d/src/ReinforcementLearningCore/src/policies/q_based_policies/explorers/epsilon_greedy_explorer.jl#L205), which use `Categorical` to wrap the `prob` in the end. So that it would raise `AssertionError: length(A) == length(P)`, just like the following example:

```julia
using Flux
using ReinforcementLearning

# Wrap the AbstractEnv for inputting the NeuralNetworkApproximator
env = KuhnPokerEnv()
states = [
    (), (:J,), (:Q,), (:K,),
    (:J, :bet), (:J, :pass), (:Q, :bet), (:Q, :pass), (:K, :bet), (:K, :pass),
    (:J, :pass, :bet), (:J, :bet, :bet), (:J, :bet, :pass), (:J, :pass, :pass),
    (:Q, :pass, :bet), (:Q, :bet, :bet), (:Q, :bet, :pass), (:Q, :pass, :pass),
    (:K, :pass, :bet), (:K, :bet, :bet), (:K, :bet, :pass), (:K, :pass, :pass),
    (:J, :pass, :bet, :pass), (:J, :pass, :bet, :bet), (:Q, :pass, :bet, :pass),
    (:Q, :pass, :bet, :bet), (:K, :pass, :bet, :pass), (:K, :pass, :bet, :bet),
] # all states for players 1 & 2

states_indexes_Dict = Dict((i, j) for (j, i) in enumerate(states))

wrapped_env = StateTransformedEnv(
        env;
        state_mapping = s -> 
            current_player(env) == chance_player(env) ? s : [states_indexes_Dict[s]]
    )

# ignore the chance_player
while current_player(env) == chance_player(env)
    env |> action_space |> rand |> env
end

policy = QBasedPolicy(
    learner = BasicDQNLearner(
        approximator = NeuralNetworkApproximator(
            model = Dense(1, 2),
            optimizer = Descent(0.01),
        )
    ),
    explorer = GreedyExplorer(),
)

prob(policy, wrapped_env, 1)
```

In this example, 

```julia
julia> A = action_space(wrapped_env)
Base.OneTo(2)

julia> P = prob(policy, wrapped_env)
Distributions.Categorical{Float64, Vector{Float64}}(support=Base.OneTo(2), p=[1.0, 0.0])

julia> length(A), length(P)
(2, 1)
```

**Comment by findmyway** [comment]
You get it. That assertion is not valid now. It's better to add another checking for `Categorical` distribution.

**Comment by peterchen96** [comment]
Thank you for responding. I am still confused about the function of the `Categorical` distribution here. Is it necessary to wrap `prob` with `Categorical`?

**Comment by findmyway** [comment]
Yes, this is explicitly specified in `RLBase`:

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/c7b66e47e939592045326485b9c89b1486df165d/src/ReinforcementLearningBase/src/interface.jl#L52
