### ISSUE TITLE
Can `evaluate` function be used as a component of RLcore?

### ISSUE THREAD

**Issue by pilgrimygy** [JuliaReinforcementLearning/ReinforcementLearning.jl#369]
@findmyway 
In SAC, we use a GaussianNetwork as an actor and define a `evaluate` function:
```julia
function evaluate(p::SACPolicy, state)
    μ, logσ = p.policy(state)
    π_dist = Normal.(μ, exp.(logσ))
    z = rand.(p.rng, π_dist)
    logp_π = sum(logpdf.(π_dist, z), dims = 1)
    logp_π -= sum((2.0f0 .* (log(2.0f0) .- z - softplus.(-2.0f0 * z))), dims = 1)
    return tanh.(z), logp_π
end
```
This function is actually not related to SAC. In many continuous control tasks, GaussianNetwork can be used as an actor, and we need to define a similar function. We can define this function as a component in the RLcore package for reuse.

**Comment by Mobius1D** [comment]
Hmm, makes sense. Felt the same. But even as common would do. But since most of this would be used in offline as well it can be added as a part of RLCore.

The same can be said for other components like quantile huber loss since, a standard implementation of CQL for discrete actions is built on top of qrdqn.

**Comment by findmyway** [comment]
>  In many continuous control tasks, GaussianNetwork can be used as an actor, and we need to define a similar function. We can define this function as a component in the RLcore package for reuse.

Yeah, just do it.

**Comment by pilgrimygy** [comment]
> The same can be said for other components like quantile huber loss since, a standard implementation of CQL for discrete actions is built on top of qrdqn.

Well. Distributional RL components are applied in different algorithms.

**Comment by Mobius1D** [comment]
> Distributional RL components are applied in different algorithms. 

To be frank I know IQN implements this. Anything else?
