### ISSUE TITLE
problem about precompiling the forked package

### ISSUE THREAD

**Issue by peterchen96** [JuliaReinforcementLearning/ReinforcementLearning.jl#377]
when I want to use the latest forked `ReinforcementLearning.jl` package, it would raise error when precompiling just like following:

```julia
julia> using ReinforcementLearning
[ Info: Precompiling ReinforcementLearning [158674fc-8238-5cab-b5ba-03dfc80d1318]
ERROR: LoadError: LoadError: UndefVarError: with_workspace not defined
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:386
 [2] include(x::String)
   @ NNlibCUDA ~/.julia/packages/NNlibCUDA/806f6/src/NNlibCUDA.jl:1
 [3] top-level scope
   @ ~/.julia/packages/NNlibCUDA/806f6/src/NNlibCUDA.jl:15
 [4] include
   @ ./Base.jl:386 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1213
 [6] top-level scope
   @ none:1
 [7] eval
   @ ./boot.jl:360 [inlined]
 [8] eval(x::Expr)
   @ Base.MainInclude ./client.jl:446
 [9] top-level scope
   @ none:1
in expression starting at /home/pchen/.julia/packages/NNlibCUDA/806f6/src/cudnn/cudnn.jl:1
in expression starting at /home/pchen/.julia/packages/NNlibCUDA/806f6/src/NNlibCUDA.jl:1
```

**Comment by findmyway** [comment]
I can't reproduce this error. How did you run it?

**Comment by peterchen96** [comment]
Looks like my `Manifest.toml` was out of date, sorry to bother you. By the way, after adding the experiment like #375 in the forked package, how can I run it? 

```julia
 ➜ julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using ReinforcementLearningExperiments

julia> run(E`JuliaRL_NFSP_KuhnPoker`)
ERROR: LoadError: MethodError: no method matching Experiment(::Val{:JuliaRL}, ::Val{:NFSP}, ::Val{:KuhnPoker}, ::Nothing)
```

**Comment by findmyway** [comment]
Did you run `] build`?

Take a look at the `src/ReinforcementLearningExperiments/src/experiments` to confirm `JuliaRL_NFSP_KuhnPoker.jl` is there.

Usually, I'd simply run the following code to test the experiments:

```julia
] activate /path/to/ReinforcementLearning.jl
include("/path/to/your/new/experiment.jl")
run(E`Your_Experiment`)
```

**Comment by peterchen96** [comment]
I add my experiment in the `./docs/experiments/experiments/NFSP/` for now and can run the experiment by `include("docs/experiments/experiments/NFSP/JuliaRL_NFSP_KuhnPoker.jl")`. 

Is it the right way to add the experiment or I should add my experiment in the `src/ReinforcementLearningExperiments/src/experiments`?

By the way, I use `WeightedSoftmaxExplorer` as my sl_agent explorer, however, when running the experiment, it would raise `UndefVarError: WeightedSoftmaxExplorer not defined`. I found [WeightedSoftmaxExplorer](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/639717388fb41199c98b90406bea76232bc6294d/src/ReinforcementLearningCore/src/policies/q_based_policies/explorers/weighted_softmax_explorer.jl#L1) here.

**Comment by findmyway** [comment]
> I add my experiment in the `./docs/experiments/experiments/NFSP/` for now and can run the experiment by `include("docs/experiments/experiments/NFSP/JuliaRL_NFSP_KuhnPoker.jl")`.
> 
> Is it the right way to add the experiment or I should add my experiment in the `src/ReinforcementLearningExperiments/src/experiments`?

Yes, that's the right way. I'll take a close look into your PR later tonight and provide some suggestions.

> By the way, I use `WeightedSoftmaxExplorer` as my sl_agent explorer, however, when running the experiment, it would raise `UndefVarError: WeightedSoftmaxExplorer not defined`. I found [WeightedSoftmaxExplorer](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/639717388fb41199c98b90406bea76232bc6294d/src/ReinforcementLearningCore/src/policies/q_based_policies/explorers/weighted_softmax_explorer.jl#L1) here.

That shouldn't be. You'd check whether you've run `using ...` or not.

**Comment by peterchen96** [comment]
> That shouldn't be. You'd check whether you've run `using ...` or not.

Looks like there is a lack of `include("weighted_softmax_explorer.jl")` in the `explorers.jl`. I'll create a PR for it.
