### ISSUE TITLE
Question: Can we use packages like `DifferentialEquations.jl` to evolve or model the environment in `ReinforcementLearning.jl`

### ISSUE THREAD

**Issue by 00krishna** [JuliaReinforcementLearning/ReinforcementLearning.jl#378]
Just a simple question I wanted to check. Can I use packages like `DifferentialEquations.jl` to model the environment in a Reinforcement learning simulation. Now is the `ReinforcementLearning.jl` package able to handle that?

What I mean is, I can write a simple differential equation model for the evolution of environment--say some physics based model. But then I push that model into the `run()` function, I probably just need to make sure that the `env()` function will take in the current state and action information and then `solve()` the differential equation system for the subsequent state. I don't think I would need anything special from the `ReinforcementLearning.jl` package from this. 

So just wanted to check if my interpretation is correct in terms of how to implement this integration of `DifferentialEquations.jl` with the `ReinforcementLearning.jl` package. 
Thanks.

**Comment by findmyway** [comment]
Yes, almost right. See also https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/discussions/293
