### ISSUE TITLE
MultiAgentManager does not select correct action space for RockPaperScissorsEnv

### ISSUE THREAD

**Issue by pkienscherf** [JuliaReinforcementLearning/ReinforcementLearning.jl#393]
When using the MultiAgentManager (e.g., with random policies) in, e.g, the RockPaperScissorsEnv, it does not choose from the action spaces of the individual players, but from the action space of the simultaneous player (for each player!):

```julia> using ReinforcementLearning

julia> rps = RockPaperScissorsEnv();

julia> ma_policy = MultiAgentManager(
                         (
                             NamedPolicy(p=>RandomPolicy())
                             for p in players(rps)
                         )...
                     )
typename(MultiAgentManager)
└─ agents => typename(Dict)


julia> ma_policy(rps)
2-element Vector{Tuple{Char, Char}}:
 ('💎', '📃')
 ('💎', '💎')
```

This is a problem in the example as the error is not caught (the action profile is still a tuple). But more importantly, it is an issue when users create multi-agent environments based on the example.

**Comment by findmyway** [comment]
Thanks for raising this problem.

Actually the MultiAgentManager has a limited usage scope. It is designed to play with environments of Sequential instead of Simultaneous (and it’s mostly for educational purpose on how to write a multi agent algorithms ). And the Rock-Paper-Scissor game is defined to be Simultaneous in RLEnvs. (Though it can be switched to a Sequential style )

But I agree we should check such constraints in code.

**Comment by pkienscherf** [comment]
I see. Let me know if/how I could help; I wasn't sure about your design goals there (and obviously I misunderstood parts of the MAManager). I am interested in simultaneous multi-agent environments, so if there is work to be done in that direction I am happy to help!

**Comment by findmyway** [comment]
Great. I think you may need to design your own agent manager like what `MultiAgentManager` do. @peterchen96 is working on some multiagent RL algorithms. He will add some other kinds of multi agent managers soon. But I guess simultaneous multi-agent environments are not covered in his plan. So contributions are always welcomed 🤗 .

**Comment by findmyway** [comment]
@all-contributors please add @pkienscherf for bug
