### ISSUE TITLE
Add ReinforcementLearningDatasets.jl

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#397]
Although @Mobius1D has done some work on it recently in https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/384 , it seems to deviate from what I thought. So I'd write down some key points here.

## Goal

This package is to provide some utils to **load** standard datasets and **generate** new offline datasets.

## Requirements

1. `ReinforcementLearningDatasets.jl` should be relatively independent. This means that we shouldn't rely on other packages in `RL.jl` or some other python dependencies.
2. Lazy loading. Only load required data when necessary.
3. Leverage multi-threading when possible

## Data Sources

We can support [d4rl](https://github.com/rail-berkeley/d4rl/blob/6d654f017ddc477d18166ed60f9f5f2636adb693/d4rl/infos.py) first.

## Basic Interfaces

- `dataset("d4rl-maze2d-umaze-v1", style=SARTS, is_sequential=false, batch_size=256, is_shuffle=true, is_normalize_score=false, rng=GLOBAL_RNG)`
  Return an iterable sequence of batches with each element of a `NamedTuple{style}`. Note that data in Julia are column major.
- ``D`d4rl-maze2d-umaze-v1` ``
  Return the dataset with default keyword arguments
- `gen_dataset("JuliaRL-CartPole-BasicDQN", policy, env)`
  Since we need some RL.jl here. This part should be loaded only when RL.jl is used. (By using Requires.jl)

Feel free to add more details here. @Mobius1D @pilgrimygy

**Comment by pilgrimygy** [comment]
Why `gen_dataset` need the parameter `env`?

**Comment by Mobius1D** [comment]
I think that feature is to build the dataset given an env and policy.

**Comment by Mobius1D** [comment]
That should ofc have other arguments like is_random, is_training, is_expert, number of time_steps, etc.

**Comment by findmyway** [comment]
Yes, `env` is still required for evaluation.

**Comment by pilgrimygy** [comment]
> That should ofc have other arguments like is_random, is_training, is_expert, number of time_steps, etc.

I couldn't agree more.
