### ISSUE TITLE
AbstractActionSelector not exported

### ISSUE THREAD

**Issue by oysteinsolheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#41]
In src/components/action_selectors/abstract_action_selector.jl only the AbstractDiscreteActionSelector are exported. However, it if useful to be able to use the AbstractActionSelector for creating my own action selectors, as is done for the other abstract structs. Would it be possible to include an export for AbstractActionSelector?

**Comment by jbrea** [comment]
I have not yet made my mind up, what should be exported and what not - @findmyway certainly knows better right now - but you can always use also non-exported features by just prepending the package name, e.g.
```julia
struct MyActionSelector <: ReinforcementLearning.AbstractActionSelector
end
```

**Comment by oysteinsolheim** [comment]
Thx! 

I was just noticing that most other abstract structs where exported so I wasn't sure if this was intended or not for this particular one.

**Comment by findmyway** [comment]
Ah, my bad. `AbstractActionSelector` should be exported.

I'll take a look at all the exported identifiers and resolve it soon.
