### ISSUE TITLE
Add pre-training hook

### ISSUE THREAD

**Issue by pilgrimygy** [JuliaReinforcementLearning/ReinforcementLearning.jl#411]
In `RLCore/src/core/run.jl`, `run` function includes a `hook(PRE_EXPERIMENT_STAGE, policy, env)` function. Now, this hook is not actually used. I think that this hook can be used to make the pre-training. In fact, in PLAS, we need to pre-train a CVAE.

@findmyway Do you have any advice?

**Comment by findmyway** [comment]
Just go ahead and use it if you think it's useful.
