### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by Krastanov** [JuliaReinforcementLearning/ReinforcementLearning.jl#418]
Hello,

I was trying to figure out the different between different trajectory storage objects, but ` VectorSARTTrajectory` link in the Tutorial is dead and the trajectory links in the blog point to old archived repositories. There does not seem to be a general API documentation either, so I am a bit lost how to even see what is implemented. Any "first steps" directions would be appreciated. Maybe I am just looking at the incorrect documentation? https://juliareinforcementlearning.org/docs/

**Comment by Krastanov** [comment]
There are actually a ton of links to https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl in the documentation which is archived, so I am a bit lost where to look for the up-to-date instructions and API.

**Comment by Krastanov** [comment]
and most `show nbview` links in the experiments are broken (sorry I am reporting these as I find them hence the separate comments)

**Comment by findmyway** [comment]
@johnnychen94 It seems the link of the `show nbview` button is hardcoded? I can see those generated `ipynb` files under https://github.com/JuliaReinforcementLearning/JuliaReinforcementLearning.github.io/tree/master/docs/experiments/experiments/DQN

**Comment by findmyway** [comment]
> Hello,

Hello~

> I was trying to figure out the different between different trajectory storage objects, but ` VectorSARTTrajectory` link in the Tutorial is dead and the trajectory links in the blog point to old archived repositories. There does not seem to be a general API documentation either, so I am a bit lost how to even see what is implemented. Any "first steps" directions would be appreciated. Maybe I am just looking at the incorrect documentation? https://juliareinforcementlearning.org/docs/

The link is right. It's just that many docs in trajectories are missing. Added some in #420 .

> There are actually a ton of links to https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl in the documentation which is archived, so I am a bit lost where to look for the up-to-date instructions and API.

I tried to fix some of them. Let me know if there are still any other old links.



> and most `show nbview` links in the experiments are broken (sorry I am reporting these as I find them hence the separate comments)

This is another issue. Let's track it in a separate issue.

**Comment by findmyway** [comment]
@all-contributors please add @Krastanov  for doc
