### ISSUE TITLE
Problem accessing public google cloud storage bucket for RLDatasets.jl

### ISSUE THREAD

**Issue by Mobius1D** [JuliaReinforcementLearning/ReinforcementLearning.jl#424]
Making publicly available datasets usable directly for offline reinforcement learning is crucial for RLDatasets.jl. Recently we have added support for d4rl datasets and d4rl-pybullet datasets.

Now our goal is to expand to RL Unplugged and [google-research/batch_rl ](https://github.com/google-research/batch_rl) datasets. The datasets are available in [RL Unplugged GCP bucket](https://console.cloud.google.com/storage/browser/rl_unplugged) and [batch_rl](https://console.cloud.google.com/storage/browser/atari-replay-datasets) respectively. 

We have a problem of accessing these datasets using the [GoogleCloud.jl](https://github.com/JuliaCloud/GoogleCloud.jl) available in Julia which provides support for Cloud Storage. For other languages the API allows the use of anonymous clients and therefor access the buckets. GoogleCloud.jl rather needs us to create a session with credentials. 

`Pkg.add("GoogleCloud")`
`using GoogleCloud`
`creds = GoogleCredentials(expanduser("~/credentials.json"))`
`session = GoogleSession(creds, ["devstorage.full_control"])`
`set_session!(storage, session)`

After these we would be able to access the buckets `bkts = storage(:Bucket, :list)` and there is no feature for anonymous clients in GC.jl as far as I know. 

I am also not planning to go with gsutil because the user would have to install it first before we would be able to access it. I am not aware of accessing using HTTP.jl in Julia.

I have very limited knowledge of GCP and GoogleCloud.jl. So it would be great if someone shed some light on this matter so that I would be able to implement it.

We are planning to keep the package dependencies to the minimum. So we are looking for mostly native Julia methods rather than using gsutil. Using GC.jl or HTTP is welcomed. 

@findmyway If you are aware of any solutions, please do help out.

Thanks a lot in advance.

**Comment by findmyway** [comment]
Let's simply assume `gsutil` is installed on user's OS first to push forward our development on RLDatasets.jl. We can run external commands like `gsutil cp ...` to download the dataset. When `gsutil` is not found, just inform users to install it first.
