### ISSUE TITLE
Function to access base env through multiple wrapper layers

### ISSUE THREAD

**Issue by albheim** [JuliaReinforcementLearning/ReinforcementLearning.jl#425]
Something I have found myself wanting is an easy access to the base environment through arbitrary wrapper layers so I can inspect what is going on with all the variables in the environment (for logging and understanding). I have made it locally but I thought it might be something more people would like and it could maybe be useful to have in the package.

It could be added as simple as
```julia
getinner(env::AbstractEnvWrapper) = getinner(env[])
getinner(env::AbstractEnv) = env
```

or maybe it could be tied in with the current `getindex` version that gets the next layer for you.

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/ffada88441274daed3a5ab8a387b58fe4a83004c/src/ReinforcementLearningEnvironments/src/environments/wrappers/wrappers.jl#L7

I also found myself including the `MultiThreadEnv` so I could consistently get access to a single one of them, but I'm not sure I think this should be default.
```julia
getinner(env::MultiThreadEnv) = env[1]
```

**Comment by findmyway** [comment]
Good suggestion!

Just one minor suggestion. The function name `getinner` seems to be a bit unclear to me, is it just one step inner or the most inner one? How about just use `env_wrapper[!]` 😄 . Anyway, feel free to add `getinner` if you already used it in your code.

**Comment by albheim** [comment]
> Good suggestion!
> 
> Just one minor suggestion. The function name `getinner` seems to be a bit unclear to me, is it just one step inner or the most inner one? How about just use `env_wrapper[!]`  . Anyway, feel free to add `getinner` if you already used it in your code.

I agree that `getinner` might not be the best, just what I had in my code. I think it would be nicer with something like you suggest, can make a PR.
