### ISSUE TITLE
StopAfterEpisode with progress meter

### ISSUE THREAD

**Issue by Martyn-R** [JuliaReinforcementLearning/ReinforcementLearning.jl#51]
Following the quick example, I experimented with two consecutive calls to `run`. This resulted in total rewards per episode larger than 200 for some episodes in the second call. This cannot be correct and I contribute this to the stop condition which is based on number of steps and therefore might fire at a moment when an episode is till ongoing thus confusing `TotalRewardPerEpisode` in the second call.

Therefore I switched to `StopAfterEpisode` as stopping criterium. In this setting I do not see rewards above 200 anymore at subsequent calls to `run`, but it seems that the progress meter is not working correctly in this case.

I am on v0.4.0 #master.

**Comment by findmyway** [comment]
> This resulted in total rewards per episode larger than 200 for some episodes in the second call. 

Yes, I think I've also experienced something similar before. Your analysis is pretty correct! One solution is  to add another two `Stage`: `StartExperimentStage` and `ExitExperimentStage`. And we can flush `TotalRewardPerEpisode` at the `ExitExperimentStage`.

> but it seems that the progress meter is not working correctly in this case.

This is strange. I'll investigate it later.

**Comment by findmyway** [comment]
Just found that there's a bug in the implementation of `StopAfterEpisode`. Will fix it soon.

**Comment by findmyway** [comment]
fixed in https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/pull/27
