### ISSUE TITLE
Knet backend does not work on gpu

### ISSUE THREAD

**Issue by ngphuoc** [JuliaReinforcementLearning/ReinforcementLearning.jl#52]
I tried the quick example in the documentation with Knet and gpu. It seems to_device does not work for Knet_gpu: 

```
backend  = :Knet
device = :Knet_gpu

ERROR: MethodError: no method matching *(::Array{Float32,2}, ::KnetArray{Float32,2})```

**Comment by findmyway** [comment]
Try `device = :gpu`. See the [doc](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/components/approximators/#ReinforcementLearning.NeuralNetworkQ)

Also notice that only dense layers are supported for now.

**Comment by ngphuoc** [comment]
Same error! I guess you miss a similar line for Knet_gpu, like Zygote_gpu, in ```src/Utils/devices.jl```

```
    to_device(::Val{:Knet_gpu}, x) = Flux.fmap(a -> adapt(KnetArray{Float32}, a), x)

```

**Comment by findmyway** [comment]
Ah, you are right!

I may have deleted that line by accident.

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/38/files#diff-7345d6a8292c525152db8d843b799eb2R19

PR is welcome!

In the future, we'd better to add some GPU related test cases.

**Comment by findmyway** [comment]
To ease the burden of maintenance, the support for Knet is dropped now.
