### ISSUE TITLE
Small performance improvement

### ISSUE THREAD

**Issue by Mo8it** [JuliaReinforcementLearning/ReinforcementLearning.jl#558]
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/84a374ef261d9d6584ec45555ef37caa69c2c635/src/ReinforcementLearningCore/src/policies/agents/agent.jl#L142

Why not just take the first action as a dummy action?
```julia
a = policy isa NamedPolicy ? action_space(env, nameof(policy))[1] : action_space(env)[1]
```
This should be slightly faster than the current version.

**Comment by findmyway** [comment]
Nice catch. You're right here.

Actually, it was intentional to catch any unexpected bugs that rely on this action.

As you can see in all the built-in experiments, we've set the seed to make them reproduciable. So if any algorithm implementation relies on the dummy action (a common bug based on my experience), then it won't be reproduciable.

**Comment by findmyway** [comment]
Well, I just realize that, simply taking the first action will only work on environments of discrete action space.

Really sorry that I have to revert #559

**Comment by Mo8it** [comment]
Are continous action spaces defined as intervals from IntervalSets.jl? Then I can fix it with calling action_space.left for an interval.

**Comment by findmyway** [comment]
Yes, but also note that it may be changed later. We'd better not to reply on this underlying implementation details.

**Comment by Mo8it** [comment]
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/562

Does this solve it? For a general case we take rand, but for abstract vectors we get the first one. This would also work for static vectors for example.

**Comment by findmyway** [comment]
Merged 👍🏻 Thanks!

**Comment by Mo8it** [comment]
I did just try rand(ClosedInterval(-1.0, 1.0)) and it did give me an error. This is used for example in the environment ContinuousMountainCar. Shouldn't we take care of this case? Or how do you train this environment?

**Comment by findmyway** [comment]
I added a patch here 😃 : 

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/f04b2b648c5cc14c415a38968be66f1bea866be6/src/ReinforcementLearningEnvironments/src/base.jl#L9

So it will only work when you've imported `ReinforcementLearningEnvironments.jl`
