### ISSUE TITLE
action_space not defined in tutorial

### ISSUE THREAD

**Issue by blegat** [JuliaReinforcementLearning/ReinforcementLearning.jl#569]
In the tutorial, the last command shows
```julia
julia> run(agent, env, StopAfterEpisode(10), TotalRewardPerEpisode())
ERROR: UndefVarError: action_space not defined
```
on the website: https://juliareinforcementlearning.org/docs/tutorial/

**Comment by findmyway** [comment]
It's very likely you have an old version installed.

https://juliareinforcementlearning.org/docs/FAQ/#Downgrade-happens-when-using-this-package

**Comment by findmyway** [comment]
Ah, I get it. Indeed.  That's pretty strange though. Let me have a check first.

**Comment by findmyway** [comment]
That might be related https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/572

**Comment by findmyway** [comment]
Also, most experiments are not running correctly https://juliareinforcementlearning.org/docs/experiments/
