### ISSUE TITLE
Strange Bug with examples CartPoleEnv and RLBase.test_runnable!(RandomWalk1D)

### ISSUE THREAD

**Issue by ryan-o-c** [JuliaReinforcementLearning/ReinforcementLearning.jl#579]
Hi, I'm new to this so apologies if my questions are silly!

I'm trying to code up a custom environment, but test_runnable threw up this error. I tried creating the example Random Walk 1D environment copied from this github too to double check that test_runnable was working correctly, but it spat the same error as pictured. (Basically, both cited that the reset! function wasn't working)

![image](https://user-images.githubusercontent.com/91661064/151405564-0c71fb24-e463-4ce2-9f83-606abd768014.png)

I then tried to run the example given in the intro page on github to make sure I had installed the ReinforcementLearning package correctly, and got a strange error after the output

![image](https://user-images.githubusercontent.com/91661064/151405720-ddf6a20a-5aa6-407f-a94e-21ec3a9ed310.png)

Please let me know if you have any suggestions, I'm at a loss! I recently uninstalled Julia 1.6.3 and updated to 1.7.1, if that's relevant!

**Comment by kir0ul** [comment]
For the first part of your question about the `RandomWalk1D` environment, you need to call it as a function with the parentheses for the `test_runnable!()` function to work (I got bitten by the same problem... :sweat_smile:), otherwise I get the same error as you:
```
julia> RLBase.test_runnable!(RandomWalk1D())
Test Summary:                   | Pass  Total
random policy with RandomWalk1D | 2000   2000
Test.DefaultTestSet("random policy with RandomWalk1D", Any[], 2000, false, false)
```
It's probably better to assign it to a variable `env = RandomWalk1D()` as they do in the tutorial though:
```
julia> RLBase.test_runnable!(env)
Test Summary:                   | Pass  Total
random policy with RandomWalk1D | 2000   2000
Test.DefaultTestSet("random policy with RandomWalk1D", Any[], 2000, false, false)
```

**Comment by kir0ul** [comment]
Not sure about your `UndefVarError` with the `CartPoleEnv()`, I can just confirm it works for me on Julia v1.7.0:
```
julia> run(
                  RandomPolicy(),
                  CartPoleEnv(),
                  StopAfterEpisode(10),
                  TotalRewardPerEpisode()
              )
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀Total reward per episode⠀⠀⠀⠀⠀⠀⠀⠀⠀
            ┌────────────────────────────────────────┐
         30 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⢣⠀⠀⠀⠀⠀⠀⠀⠀│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⠀⠱⡀⠀⠀⠀⠀⠀⠀│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠤⠤⣀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠇⠀⠀⠀⠱⡀⠀⠀⠀⠀⠀│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠔⠊⠀⠀⠀⠀⠉⠒⠤⡀⠀⠀⠀⠀⡎⠀⠀⠀⠀⠀⠑⡄⠀⠀⠀⠀│
   Score    │⠀⠀⠀⠀⡤⠤⠤⠤⠤⠒⠒⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠢⡀⠀⡜⠀⠀⠀⠀⠀⠀⠀⠘⡄⠀⠀⠀│
            │⠀⠀⡠⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠲⠁⠀⠀⠀⠀⠀⠀⠀⠀⠘⢄⠀⠀│
            │⡠⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢆⠀│
            │⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢆│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
            │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
          0 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│
            └────────────────────────────────────────┘
            ⠀1⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀10⠀
            ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀Episode⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
TotalRewardPerEpisode([10.0, 15.0, 15.0, 16.0, 19.0, 17.0, 13.0, 24.0, 16.0, 8.0], 0.0, true)
```

**Comment by ryan-o-c** [comment]
> kir0ul

Thank you - the parentheses worked! I'm still having other issues creating my environment - you'll probably see more of my issues crop up here in the coming days! 

Also, somehow the second error hasn't come up again for me and seems to be gone - all's well that ends well I suppose!
