### ISSUE TITLE
Difficulty Creating a Custom Environment

### ISSUE THREAD

**Issue by ryan-o-c** [JuliaReinforcementLearning/ReinforcementLearning.jl#581]
Hi, I have more (probably stupid) questions!

I'm getting the error picture below saying "type env has no field state". I think there's something wrong with my state or state_space assignments, but I've tried a few things and am totally lost. I'll add a picture of my code and the error here too.

If it helps, the general idea of my environment is that I have a series of N=7 points (I call them squares in my comments) on a number line that I want to move around. I'm trying to keep it super simple, so the agent can pick any square and move it to the right 1 space (squares can overlap). It gets a reward at every step for doing so, and there's a step counter so that I have a termination condition.

I want to eventually build on this to the point where the squares are on a 2-D grid, and I have an agent that selects squares and another agent that decides what direction to move them. I'd like to feed more information in the observation to each agent - I will create a proper custom reward and I want them to learn how to move the squares into a configuration the reward deems useful. I'd also like to make N much larger, but given that I'm struggling with the very dumbed down version, I'm not too worried about it for now!

I hope someone can help - I would really appreciate it!

![image](https://user-images.githubusercontent.com/91661064/151843636-55dc9625-a691-4cf3-9cb3-0e636afca235.png)

![image](https://user-images.githubusercontent.com/91661064/151843711-6af3d67e-cc37-412c-943e-b63cdf898c27.png)

![image](https://user-images.githubusercontent.com/91661064/151843783-b136f27b-9a48-4db8-bb62-4f19c35cc7ac.png)

**Comment by kir0ul** [comment]
@ryan-o-c I'd suggest you paste a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your issue as code and not as images, it would increase the chances you get an answer.

**Comment by findmyway** [comment]
The error message already told you that, in the `reset!` function, you used `env.state` where the `:state` field is not defined. You probably mean `env.start_pos`?

**Comment by ryan-o-c** [comment]
Thank you both - I'll be sure to include a MRE of my code in any further posts (hopefully there won't be any need). I appreciate your patience, especially now that I realise how foolish my questions are. After changing my reset function to call x_pos instead of state, and fixing a few more simple errors, my environment is now running - thanks so much for your help!
