### ISSUE TITLE
Missing docs for how to implement a new algorithm

### ISSUE THREAD

**Issue by johannes-fischer** [JuliaReinforcementLearning/ReinforcementLearning.jl#582]
Currently there is no documentation for [how to implement a new algorithm](https://juliareinforcementlearning.org/docs/How_to_implement_a_new_algorithm/). Does there exist a draft of this somewhere? Or can you quickly outline the main steps involved? I'm considering implementing something like AlphaZero, so based on MCTS with additionally learned models.
So would I also frame this as a `QBasedPolicy` that seems to be used in most of the currently available algorithms in `ReinforcementLearningZoo` or implement something else like a `TreeBasedPolicy`?

**Comment by findmyway** [comment]
> Does there exist a draft of this somewhere?

Not yet.

> Or can you quickly outline the main steps involved? I'm considering implementing something like AlphaZero, so based on MCTS with additionally learned models.

Those algorithms will be quite different from the general workflow of `QBasedPolicy`. I'd recommend you take a look at the [`abstract_cfr_policy.jl`](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningZoo/src/algorithms/cfr/abstract_cfr_policy.jl) and [`deep_cfr.jl`](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningZoo/src/algorithms/cfr/deep_cfr.jl) files. As you'll see, this package doesn't provide that many reusable components for MCTS like algorithms. You need to define your own workflow and the `update!` logic.

I'd recommend coming up with a draft workable solution first, then we can see how to make it more generalized.😃
