### ISSUE TITLE
PPOCartPole fails, source of error included

### ISSUE THREAD

**Issue by jarbus** [JuliaReinforcementLearning/ReinforcementLearning.jl#605]
Interesting bit of behavior, found a workaround. Apparently, on the latest version of ReinforcementLearning.jl, PPO fails on the GPU for me, with the following error:

```
ERROR: LoadError: GPU compilation of kernel broadcast_kernel(CUDA.CuKernelContext, CUDA.CuDeviceMatrix{Float32, 1}, Base.Broadcast.Broadcasted{Nothing, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(relu), Tuple{Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{2}, Nothing, typeof(+), Tuple{Base.Broadcast.Extruded{Matrix{Float32}, Tuple{Bool, Bool}, Tuple{Int64, Int64}}, Base.Broadcast.Extruded{CUDA.CuDeviceVector{Float32, 1}, Tuple{Bool}, Tuple{Int64}}}}}}, Int64) failed
KernelError: passing and using non-bitstype argument
```

The traceback refers me to these lines:

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/fd96fe648044f5dc2a5dee53cfac64824de0fd54/src/ReinforcementLearningZoo/src/algorithms/policy_gradient/ppo.jl#L240-L241

PPO works as expected (with a massive performance drop) if I cast `flatten_batch(states_plus)` as an array:

```julia
    states_plus_values =
        reshape(send_to_host(AC.critic(Array(flatten_batch(states_plus)) |> to_device)), n_envs, :)
```

This error did not occur in previous versions of ReinforcementLearning.jl. The issue appears to be that the output of `flatten_batch(states_plus)` is not able to be sent to the GPU:

```julia
julia> flatten_batch(states_plus) |> to_device |> device
nothing
julia> Array(flatten_batch(states_plus)) |> to_device |> device
CUDA.CuDevice(0)
```

**Comment by jarbus** [comment]
On further inspection, the following workaround works better, as it doesn't make a copy of the state array, although not sure if there is a logical error, as I don't fully understand how CircularBuffers work
```julia
    states_flatten_on_device = flatten_batch(states_plus.buffer)
    states_plus_values = reshape(send_to_host(AC.critic(states_flatten_on_device)), n_envs, :)
```

**Comment by findmyway** [comment]
Thanks for reporting. I'm looking into it. Will fix it soon.

**Comment by findmyway** [comment]
The main relevant change is [the following line](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/606/files#diff-7930268720b9366b7726b2e1e44e38b3499ab78ab0cb137771dc5b2887965b57R58)

```julia
send_to_device(d::CuDevice, m::CircularArrayBuffer) = send_to_device(d, collect(m)) 
```

**Comment by findmyway** [comment]
@all-contributors please add @jarbus for bug

**Comment by jarbus** [comment]
Wow, incredible turnaround time. Thanks @findmyway!
