### ISSUE TITLE
How to run this source code in vscode?

### ISSUE THREAD

**Issue by hasegetc** [JuliaReinforcementLearning/ReinforcementLearning.jl#623]
* I cloned this repo, and add a test like this, bug it can't run it on vscode, so if I want to change the source code and debug it, how could I make it work?
```
import RL

 RandomPolicy(),
           CartPoleEnv(),
           StopAfterStep(1_000),
           TotalRewardPerEpisode()
 ```

**Comment by findmyway** [comment]
Hi @hasegetc ,

You can follow the instructions https://juliareinforcementlearning.org/docs/tips/#How-to-setup-local-development-environment? to set up the local development environment.

Note that you need to execute `using ReinforcementLearning`, not the alias of `RL`.

**Comment by hasegetc** [comment]
thanks a lot!
