### ISSUE TITLE
Support julia 1.4

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaReinforcementLearning/ReinforcementLearning.jl#63]
The current version is limited to 1.3. 

I tried master on julia 1.4 and the example seems to work fine (I have not ran the test suite). 

Would it be possible to relax the compatibility constraint on the julia version? 
Thanks!

**Comment by findmyway** [comment]
Hi @MaximeBouton ,

Do you mean the `julia="1.3"` in the `[compat]` section of `Project.toml`? If I understand [the doc](https://julialang.github.io/Pkg.jl/v1/compatibility.html#Caret-specifiers-1) correctly, it means `[1.3.0, 2.0.0)`. Am I right?

**Comment by MaximeBouton** [comment]
Yes you are right! sorry for noise, I must have a compat issue from another package thanks!
