### ISSUE TITLE
How to define a new environment?

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#64]
[The question was first asked on slack]

This part is still missing in the latest doc. 

The interfaces of `AbstractEnvironment` are not well organized. Need improve!

To define a single-player environment, the following interfaces must be implemented:

- [get_action_space(env)](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.get_action_space)
- [get_observation_space(env)](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.get_observation_space)
- [reset!(env)](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.reset!-Tuple{AbstractEnv})
- (env::YourEnv)(action)
- [observe (env)](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.observe)-> observation

Here an observation can be of any type, as long as the following interfaces are provided:

- [get_state(obs)](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.get_state)
- [get_reward(obs)](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.get_reward)
- [get_terminal(obs)](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.get_terminal)

If the actions in the action space are not always legal at each step, then the following interfaces must defined:

- [ActionStyle(obs)=FULL_ACTION_SET](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.ActionStyle)
- [get_legal_actions(obs)](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.get_legal_actions)
- [get_legal_actions_mask](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.get_legal_actions_mask)

To define multi-player environments, the following interfaces are also needed:

- [DynamicStyle](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.DynamicStyle)
- [get_num_players](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/rl_base/#ReinforcementLearningBase.get_num_players)
- env(player, action)
- observe(env, player)

**Comment by robertfeldt** [comment]
Thanks for this package @findmyway , it looks very promising!

Is there some example code for a case where not all actions are legal in some states? 

As a minimal/simple example of what I'd like to achieve is to have three states where:

1. In the first state there are only two actions that lead to either state 2 or (back to) state 1, and
2. In the second state the action space is continuous.

Looking at the code it seems I can achieve this with a TupleSpace of a DiscreteSpace(2) and a ContinuousSpace but I'm not sure how to implement the `get_legal_actions` etc. Great if there is an example, sorry if I missed it.

**Comment by findmyway** [comment]
> Is there some example code for a case where not all actions are legal in some states?

Ah, good question. There used to be (for example, [here](https://github.com/findmyway/LetsPlayHanabi/blob/483d9f4199113a01d921752dca1c4904ac906b7a/src/agents/rainbow_agent.jl#L146)). But I forgot to add them back 🤣. It's not very difficult, but do need some effort. I create an issue here https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/issues/60 to track the progress.

> As a minimal/simple example of what I'd like to achieve is to have two states where:
>
> 1. In the first state there are only two actions that lead to either state 2 or (back to) state 1, and
> 1. In the second state the action space is continuous.
>
> Looking at the code it seems I can achieve this with a TupleSpace of a DiscreteSpace(2) and a ContinuousSpace but I'm not sure how to implement the get_legal_actions etc. Great if there is an example, sorry if I missed it.

Yeah, you are right here. But this kind of environment is not very common, so no example yet.

I can quickly create one 😁:

```julia
mutable struct ExampleEnv <: AbstractEnv
    state::Int
    leaf_state_true_rewards::Vector{Float64}
    reward::Union{Nothing, Float64}
end

ExampleEnv(n) = ExampleEnv(0, rand(n), nothing)

function (env::ExampleEnv)(action)
    if env.state == 0
        env.state += action
    else
        env.reward = env.leaf_state_true_rewards[env.state] + rand() + action
    end
end

# the `NamedTuple{(:reward, :terminal, :state, :legal_actions)} is a known observation of FullActionStyle
# see https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/9e7281ccda9efd63f2b6b12b663cba393b50a279/src/interface.jl#L213
RLBase.observe(env::ExampleEnv) = (
    reward = isnothing(env.reward) ? 0.0 : env.reward,
    terminal = !isnothing(env.reward),
    state=isnothing(env.reward) ? env.state : length(env.leaf_state_true_rewards)+1,
    legal_actions = env.state == 0 ? DiscreteSpace(1:length(env.leaf_state_true_rewards)) : ContinuousSpace(0., 1.)
    )

function RLBase.reset!(env::ExampleEnv)
    env.state = 0
    env.reward = nothing
end
```

And now we can use a RandomPolicy:

```julia
dummy_action_space = DiscreteSpace(1:1)
p = RandomPolicy(dummy_action_space)
```
Usually, the action space is a fixed one, but based on your description, it is different in different states. So here we just initialize it with a dummy one.

Actually, while writing the code, I found a bug with the `RandomPolicy` 😢, so we need the following hotfix:

```julia
function (p::RandomPolicy)(obs, ::FullActionSet)
    legal_actions = get_legal_actions(obs)
    if legal_actions isa AbstractSpace || legal_actions isa AbstractVector
        rand(p.rng, legal_actions)
    else
        @error "unknown legal_actions: $legal_actions"
    end
end
```

And simulate once:
```julia
run(p, env)
observe(env)
# (reward = 0.1823846086438683, terminal = true, state = 3, legal_actions = ContinuousSpace{Float64}(0.0, 1.0))
```

**Comment by findmyway** [comment]
I'm closing this issue with https://juliareinforcementlearning.org/blog/how_to_write_a_customized_environment/
