### ISSUE TITLE
`ActionTransformedEnv` doesn't transform `legal_action_space_mask`

### ISSUE THREAD

**Issue by baedan** [JuliaReinforcementLearning/ReinforcementLearning.jl#642]
hi!  i'm new to julia and reinforcement learning, so apologies if this is not right, but it seems to me that `ActionTransformedEnv` doesn't transform `legal_action_space_mask`, and there's no option for doing so ([`ActionTransformedEnv.jl`](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/bf5c5756390378bb2a6ff8f36c73845c522bf66d/src/ReinforcementLearningEnvironments/src/environments/wrappers/ActionTransformedEnv.jl)).  but a lot of components of this package relies on `legal_action_space_mask`, not `legal_action_space`.  is this intended?

**Comment by findmyway** [comment]
Hi @baedan , welcome!

> but it seems to me that ActionTransformedEnv doesn't transform `legal_action_space_mask`

Indeed, that is missed unintentionally. Better to have it. PR is welcomed.

**Comment by baedan** [comment]
i'm not sure how best to go about this.  my first inclination is that either `legal_action_space_mask` or `legal_action_space` should be implemented by default by the other in the base case.  barring that, defining a `action_space_mask_mapping` in addition to a `action_space_mapping` feels awkward.  on that same note, defining a `action_space_mapping` in addition to an `action_mapping` also feels a bit awkward.  might be nicer to have a mask on the old `action_space` which defines the subset that would be mapped to the transformed one, using `action_mapping`.  i don't know if any of this is a big deal; just that it feels nice in terms of guaranteed consistency, haha.

would be happy to contribute though i'm not a seasoned programmer by any means.

**Comment by findmyway** [comment]
>  defining a action_space_mask_mapping in addition to a action_space_mapping feels awkward.

Agree. I think maybe in that case, people should just implement the `legal_action_space_mask` to that specific environment directly.

**Comment by baedan** [comment]
what about just adding this?

```julia
RLBase.legal_action_space_mask(env::ActionTransformedEnv) = map(action_space(env)) do action
    action in legal_action_space(env)
end
```

(any reason this isn't the default implementation for the base case?  is it efficiency?)

**Comment by findmyway** [comment]
This is a nice fallback. Would you like to add it in the following line?

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/51063056f32e64f68be3b7f32fe574a28ca4fbf4/src/ReinforcementLearningBase/src/interface.jl#L455

**Comment by baedan** [comment]
```julia
@multi_agent_env_api legal_action_space_mask(env::AbstractEnv, player = current_player(env)) = 
    map(action_space(env, player)) do action
        action in legal_action_space(env, player)
    end
```
does this look right?

and change the doc to this:

> Required for environments of [`FULL_ACTION_SET`](@ref). As a default implementation,
     [`legal_action_space_mask`](@ref) creates a mask of [`action_space`](@ref) with
     the subset [`legal_action_space`](@ref).

**Comment by findmyway** [comment]
yes, looks good to me

**Comment by baedan** [comment]
#644 done.  not sure what i should do with the news file so i'll leave it to you.
