### ISSUE TITLE
Roadmap of v0.9

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/ReinforcementLearning.jl#65]
# Reorganize code structure

1. Move RLBase, RLCore, RLEnvs, RLZoo, Docs into this package
2. Update docs
3. Update CUDA to v3
4. Evaluate all existing experiments
5. Make a report

**Comment by zahachtah** [comment]
Are there online learning algorithms implemented, i.e. agents that learn as they interact with the system over time instead of the episode training approach mostly used?

**Comment by findmyway** [comment]
Do you mean [on-policy](https://en.wikipedia.org/wiki/Reinforcement_learning#Comparison_of_reinforcement_learning_algorithms) algorithms?

A2C is added to RLZoo. But I haven't tested it in the Atari environments yet.
PPO is [almost ready](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/pull/14) but to make it comparable with the one in OpenAI baselines, [many tricks](https://openreview.net/forum?id=r1etN1rtPB) needs to be implemented.

**Comment by findmyway** [comment]
@JuliaRegistrator register

**Comment by findmyway** [comment]
@JuliaRegistrator register

**Comment by zahachtah** [comment]
> Do you mean [on-policy](https://en.wikipedia.org/wiki/Reinforcement_learning#Comparison_of_reinforcement_learning_algorithms) algorithms?
> 
> A2C is added to RLZoo. But I haven't tested it in the Atari environments yet.
> PPO is [almost ready](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/pull/14) but to make it comparable with the one in OpenAI baselines, [many tricks](https://openreview.net/forum?id=r1etN1rtPB) need to be implemented.

oh, so sorry, your reply slipped my attention!

No I mean online (or sequential) learning [link](https://en.wikipedia.org/wiki/Online_machine_learning)

**Comment by findmyway** [comment]
Ah, that part is not included yet.

**Comment by findmyway** [comment]
@JuliaRegistrator register

Release notes:

Make environments transparent to agents/policies. 
Mooncake release may be delayed.

**Comment by findmyway** [comment]
Strange 😢  Watch https://github.com/JuliaRegistries/Registrator.jl/issues/305

**Comment by findmyway** [comment]
@JuliaRegistrator register

**Comment by findmyway** [comment]
Life is full of uncertainties. Long story short, it was a hard time last week.

One important thing I learned recently was to ship products more frequently. So the next release will be tagged after https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/148 gets finished.
