### ISSUE TITLE
Base.copy not implemented for the TicTacToe environment

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaReinforcementLearning/ReinforcementLearning.jl#678]
The [TicTacToe environment](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningEnvironments/src/environments/examples/TicTacToeEnv.jl) does not implement `Base.copy`, making it impossible to use it with tree search out-of-the-box.

**Comment by findmyway** [comment]
Based on the default implementation of `Base.copy` for `AbstractEnv`:

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/c67a604336923ee9120d75dee74456759860fcda/src/ReinforcementLearningBase/src/interface.jl#L418

I think it should work
