### ISSUE TITLE
Broken link to src

### ISSUE THREAD

**Issue by trigaten** [JuliaReinforcementLearning/ReinforcementLearning.jl#693]
On this page: https://juliareinforcementlearning.org/docs/How_to_implement_a_new_algorithm/

In this paragraph, the [link](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningCore/src/policies/agents/agent.jl/) is broken.

"Agent comes with default implementations of Agent(stage, agent, env) that will probably fit what you need at most stages so that you don't have to write them again. Looking at the [source code](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningCore/src/policies/agents/agent.jl/), we can see that the default Agent calls are"

**Comment by findmyway** [comment]
Thanks! The doc is the stable version and the link points to the latest code in dev. You can find the related code in the `v0.10.1` tag https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/v0.10.1/src/ReinforcementLearningCore/src/policies/agents/agent.jl

We'll update the doc later.

**Comment by HenriDeh** [comment]
I fixed this when I updated the documentation
