### ISSUE TITLE
Can't checkout RLCore for development

### ISSUE THREAD

**Issue by HenriDeh** [JuliaReinforcementLearning/ReinforcementLearning.jl#704]
The master head has some compat issues between the RLXxx.jl packages. I'm trying to checkout RLCore to do some tests but I get the following issue when instantiating:
```
(ReinforcementLearningCore) pkg> instantiate
    Updating registry at `C:\Users\Henri\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: Unsatisfiable requirements detected for package ReinforcementLearningBase [e575027e]:
 ReinforcementLearningBase [e575027e] log:
 ├─possible versions are: 0.1.0-0.9.7 or uninstalled
 └─restricted to versions 0.10 by ReinforcementLearningCore [de1b191a] — no versions left
   └─ReinforcementLearningCore [de1b191a] log:
     ├─possible versions are: 0.9.0 or uninstalled
     └─ReinforcementLearningCore [de1b191a] is fixed to version 0.9.0-dev
```
I think this is because RLBase 0.10 was not released yet, but is a requirement for RLCore on the master head. 
When I print the RLCore status I find this:
```
(ReinforcementLearningCore) pkg> st
     Project ReinforcementLearningCore v0.9.0-dev
      Status `C:\Users\Henri\OneDrive - UCL\Doctorat\julia\ReinforcementLearning.jl\src\ReinforcementLearningCore\Project.toml`
  [79e6a3ab] Adapt v3.3.3
  [052768ef] CUDA v3.11.0
  [9de3a189] CircularArrayBuffers v0.1.10
  [31c24e10] Distributions v0.25.62
  [1a297f60] FillArrays v0.13.2
  [587475ba] Flux v0.12.10
  [d9f16b24] Functors v0.2.8
  [69de0a69] Parsers v2.3.2
  [92933f4c] ProgressMeter v1.7.2
  [189a3867] Reexport v1.2.2
  [e575027e] ReinforcementLearningBase v0.9.7
  [25e41dd2] ReinforcementLearningEnvironments v0.6.12
  [6486599b] ReinforcementLearningTrajectories v0.1.3
  [efcf1570] Setfield v1.0.0
  [2913bbd2] StatsBase v0.33.17
  [b8865327] UnicodePlots v2.12.4
  [9a3f8284] Random
  [10745b16] Statistics
```
Which means that RLXxxx packages are loaded from the general Julia registry, and do not use the local submodules. It used to be 
` [e575027e] ReinforcementLearningBase v0.9.7 '..\ReinforcementLearningBase'`
So something's wrong with the dependencies.

**Comment by findmyway** [comment]
Yes, I removed all the `Manifest.toml` files from the repo. So now the recommended development workflow is that:

1. Create a new temp folder for testing and start the Julia REPL there
2. `]dev /path/to/RL.jl/src/ReinforcementLearningBase`
3. `]dev /path/to/RL.jl/src/ReinforcementLearningEnvironments`
4. `]dev /path/to/RL.jl/src/ReinforcementLearningCore`
5. `]dev /path/to/RL.jl/src/ReinforcementLearningZoo`
6. `]dev /path/to/RL.jl/src`
7. `]dev /path/to/RL.jl/src/ReinforcementLearningExperiments`

Note that the order is important here.

We should update the *Tips for developers* section in docs later.

<hr>

The reason for removing all `Manifest.toml` files is that, Julia@v1.7 creates a new format of `Manifest.toml` file. I find it not easy to test the code on different versions under the same repo back and forth.

**Comment by baedan** [comment]
step 6 should be `]dev /path/to/RL.jl`, yeah?

**Comment by findmyway** [comment]
> step 6 should be `]dev /path/to/RL.jl`, yeah?

Yes, I updated the instructions slightly.

**Comment by HenriDeh** [comment]
> The reason for removing all Manifest.toml files is that, Julia@v1.7 creates a new format of Manifest.toml file. I find it not easy to test the code on different versions under the same repo back and forth.

That's inconvenient. I'm not sure I understand what the problem is but maybe we should ask on discourse if there's a solution to that, because this may discourage people from contributing to the package.

**Comment by HenriDeh** [comment]
Well for development it would make things much easier, but if this causes other issues then there's a dilemma to solve.

**Comment by HenriDeh** [comment]
Also, your instructions do not work:
- RLEnvironments is not in RLZoo's project, so the first line errors.
- Yet, if I start at the second line, I get this error at the 4th line:
```(ReinforcementLearningZoo) pkg> rm ReinforcementLearningCore
    Updating `C:\Users\Henri\OneDrive - UCL\Doctorat\julia\ReinforcementLearning.jl\src\ReinforcementLearningZoo\Project.toml`
  [de1b191a] - ReinforcementLearningCore
  No Changes to `C:\Users\Henri\OneDrive - UCL\Doctorat\julia\ReinforcementLearning.jl\src\ReinforcementLearningZoo\Manifest.toml`
[ Info: We haven't cleaned this depot up for a bit, running Pkg.gc()...
      Active manifest files: 9 found
      Active artifact files: 133 found
      Active scratchspaces: 13 found
     Deleted 12 package installations (7.647 MiB)
     Deleted 1 repo (18.508 MiB)
     Deleted 7 artifact installations (128.000 MiB)
     Deleted 1 scratchspace (0.000 byte)

(ReinforcementLearningZoo) pkg> ]dev src/ReinforcementLearningBase
ERROR: `]dev` is not a recognized command. Type ? for help with available commands

(ReinforcementLearningZoo) pkg> dev src/ReinforcementLearningBase
   Resolving package versions...
  No Changes to `C:\Users\Henri\OneDrive - UCL\Doctorat\julia\ReinforcementLearning.jl\src\ReinforcementLearningZoo\Project.toml`
  No Changes to `C:\Users\Henri\OneDrive - UCL\Doctorat\julia\ReinforcementLearning.jl\src\ReinforcementLearningZoo\Manifest.toml`

(ReinforcementLearningZoo) pkg> dev src/ReinforcementLearningCore
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ReinforcementLearningEnvironments [25e41dd2]:
 ReinforcementLearningEnvironments [25e41dd2] log:
 ├─possible versions are: 0.1.0-0.6.12 or uninstalled
 ├─restricted to versions * by ReinforcementLearningCore [de1b191a], leaving only versions 0.1.0-0.6.12
 │ └─ReinforcementLearningCore [de1b191a] log:
 │   ├─possible versions are: 0.9.0 or uninstalled
 │   └─ReinforcementLearningCore [de1b191a] is fixed to version 0.9.0-dev
 ├─restricted by compatibility requirements with Distributions [31c24e10] to versions: 0.2.0-0.6.12 or uninstalled, leaving only versions: 0.2.0-0.6.12
 │ └─Distributions [31c24e10] log:
 │   ├─possible versions are: 0.16.0-0.25.62 or uninstalled
 │   └─restricted to versions 0.24-0.25 by ReinforcementLearningCore [de1b191a], leaving only versions 0.24.0-0.25.62
 │     └─ReinforcementLearningCore [de1b191a] log: see above
 └─restricted by compatibility requirements with ReinforcementLearningBase [e575027e] to versions: 0.1.0-0.1.3 or uninstalled — no versions left
   └─ReinforcementLearningBase [e575027e] log:
     ├─possible versions are: 0.10.0 or uninstalled
     └─ReinforcementLearningBase [e575027e] is fixed to version 0.10.0-dev
```
I tried to look for a RLEnvironment dependency in the packages mentionned in the above message but there is none. So I'm stuck again :(

**Comment by HenriDeh** [comment]
Thanks. Though I got it working by doing `dev RLEnvs` first then RLCore.

**Comment by findmyway** [comment]
Hi @HenriDeh ,

I've made the necessary changes. The development experience should be the same as in prior releases. Let me know if you have any problems.
