### ISSUE TITLE
Code Readability

### ISSUE THREAD

**Issue by thomashopkins32** [JuliaReinforcementLearning/ReinforcementLearning.jl#740]
Hello, I am interested in using this package to learn and implement some popular RL algorithms. I am fairly new to Julia so please correct me if I am wrong.

Is it common in Julia modules to use `using [Module]` instead of `import [Module]`?
Coming from Python, is this similar to doing `from [module] import *` vs `import [module]`?

I find this relevant to this package in particular because I am finding it difficult to locate the source code for some functions. This includes when they belong to other Julia packages, other repos in JuliaReinforcementLearning, or even other packages within this repo.

A quick example:
In `A2C.jl` I want to view the definition and implementation of `select_last_dim`. It is used several times in this file but the only import at the top of the file is `using ChainRulesCore: ignore_derivatives`. Where would I find this definition?

This situation has occurred a couple of times and it can be frustrating. I think I am wasting a lot of time searching. Is there something simple that I am missing?

Why not just use `import [Module] as [M]` and qualify each function with its module source? Like `M.select_last_dim` or something.

**Comment by findmyway** [comment]
Hi @thomashopkins32 🤗 ,

The short answer is, this package was written before the `import [Module] as [M]` grammar was introduced in Julia ;) (And I'm kind of lazy to update it...)

I totally understand the frustration and have been working on it recently. For example, in the DQN related experiments (others are not updated yet), I tried my best to import names explicitly with `using Module: X,Y,Z`

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/c74f71711c11a36771700f21a94059ff367fbd35/src/ReinforcementLearningZoo/src/algorithms/dqns/iqn.jl#L3-L8

**Comment by ll7** [comment]
I am also new to Julia and can well understand these difficulties.

Regarding your example:
[A2C.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningZoo/src/algorithms/policy_gradient/A2C.jl) is part of the ReinforcementLearningZoo module, which is defined in [ReinforcementLearningZoo.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningZoo/src/ReinforcementLearningZoo.jl).

Zoo is `using` RLBase and RLCore. The best way to find out the location of `select_last_dim` is to start your julia REPL:

```julia
using ReinforcementLearning
@which select_last_dim
```

This should show you where the the method is located. Also helpful is the command line help `?`.

```julia
help?> select_last_dim
search: select_last_dim select_last_frame

  No documentation found.

  ReinforcementLearningCore.select_last_dim is a Function.

  # 1 method for generic function "select_last_dim":
  [1] select_last_dim(xs::AbstractArray{T, N}, inds) where {T, N} in ReinforcementLearningCore at /home/vscode/.julia/packages/ReinforcementLearningCore/s9XPF/src/utils/base.jl:18
```

**Comment by baedan** [comment]
hijacking this thread to report that, a difficulty with code readability/navigability is i haven't been able to get VSCode's julia extension's linter to work: names inside RL.jl work (mostly, though i think there might be weirdness going on still), but imported dependencies don't (except Base modules).  i'm not sure why this happens, and it could be user error, though i haven't encountered this problem with other modules and it persists after reinstalls/clearing cache.

wonder if anyone else has this occur and has a solution.  my guess is the somewhat unusual project structure confuses the language server.

**Comment by thomashopkins32** [comment]
> Hi @thomashopkins32 🤗 ,
> 
> The short answer is, this package was written before the `import [Module] as [M]` grammar was introduced in Julia ;) (And I'm kind of lazy to update it...)
> 
> I totally understand the frustration and have been working on it recently. For example, in the DQN related experiments (others are not updated yet), I tried my best to import names explicitly with `using Module: X,Y,Z`
> 
> https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/c74f71711c11a36771700f21a94059ff367fbd35/src/ReinforcementLearningZoo/src/algorithms/dqns/iqn.jl#L3-L8

Oh okay. Thanks for clearing that up! As I learn and work through some of these algorithms, I'll submit some PRs to help out with this effort.


> I am also new to Julia and can well understand these difficulties.
> 
> Regarding your example: [A2C.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningZoo/src/algorithms/policy_gradient/A2C.jl) is part of the ReinforcementLearningZoo module, which is defined in [ReinforcementLearningZoo.jl](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningZoo/src/ReinforcementLearningZoo.jl).
> 
> Zoo is `using` RLBase and RLCore. The best way to find out the location of `select_last_dim` is to start your julia REPL:
> 
> ```julia
> julia> using ReinforcementLearning
> 
> julia> @which select_last_dim
> ReinforcementLearningCore
> ```
> 
> This should show you where the the method is located. Also helpful is the command line help `?`.
> 
> ```julia
> help?> select_last_dim
> search: select_last_dim select_last_frame
> 
>   No documentation found.
> 
>   ReinforcementLearningCore.select_last_dim is a Function.
> 
>   # 1 method for generic function "select_last_dim":
>   [1] select_last_dim(xs::AbstractArray{T, N}, inds) where {T, N} in ReinforcementLearningCore at /home/vscode/.julia/packages/ReinforcementLearningCore/s9XPF/src/utils/base.jl:18
> ```

This is exactly the thing I was missing. Thanks!
