### ISSUE TITLE
MultiThreadEnv not available in ReinforcementLearningZoo

### ISSUE THREAD

**Issue by thomashopkins32** [JuliaReinforcementLearning/ReinforcementLearning.jl#741]
The definition for `MultiThreadEnv` exists under `src/algorithms/policy_gradient/multi_thread_env.jl` but that file is not included in `policy_gradient.jl` , `algorithms.jl`, or `ReinforcementLearningZoo.jl`. Is this intentional?

After trying to include it in `policy_gradient.jl`, I ran into some dependency issues with `MacroTools` and `EnrichedAction` not being defined. I think I solved `MacroTools` by adding `using MacroTools` and adding it to `ReinforcementLearningZoo/Project.toml`.

`EnrichedAction` appears to be defined in the archived `ReinforcementLearningZoo.jl` repository ([here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/patch.jl)). Should this also be defined in the ReinforcementLearningZoo package in this repo?

**Comment by findmyway** [comment]
> Is this intentional?

yes, policy gradient related algorithms are not ready yet in the master branch. 

You may read the source code at  https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/tree/v0.10.1 for the stable version.
