### ISSUE TITLE
Custom Environment Passes RLBase.test_runnable!(env) but infinite hangs and crashes when run.

### ISSUE THREAD

**Issue by Cfckoh** [JuliaReinforcementLearning/ReinforcementLearning.jl#757]
I implemented a custom environment with a continuous state space and either a continuous or discrete action space. When running RLBase.test_runnable() I get that the environment passed 2000 out of 2000 tests. However, it is a bit suspicious since the reported time to run the tests is 0.0s. Then when running the following lines

hook = TotalRewardPerEpisode(is_display_on_exit = false)
run(RandomPolicy(action_space(env)), env, StopAfterEpisode(10), hook)
plot(hook.rewards)

 to test the environment with a random policy the run line gets into what appears to be an infinite hang and kills the kernel. I've checked my RL.is_terminated() function to make sure episodes are terminating. Any other ideas for resolving the issue?

**Comment by findmyway** [comment]
That's hard to tell. Maybe print something at the end of an episode?

**Comment by Cfckoh** [comment]
The Kernel keeps crashing in my Jupyter notebook so I can't see any print statements. However I've ensured that episodes do terminate even going so far as to terminate and episode all the time after one action. I suppose where I am confused is that if I understand it correctly RLBase.test_runnable!() tests an environment with a random policy. So if the environment passes RLBase.test_runnable!() tests why would it crash when doing the same with a random policy manually using run()?

**Comment by findmyway** [comment]
`RLBase.test_runnable!()` only tests the environment by executing random policy at most `2000` steps by default. It is possible that the environment doesn't terminate within 2000 steps.

> ... kernel crashes ...

Could you share the stack trace? That would help to locate the error.

**Comment by Cfckoh** [comment]
I've hard capped my episodes to terminate well before 2000 steps so it should not be the issue Running in a Jupyter notebook I don't get a stack trace. I just get "The kernel appears to have died. It will restart automatically." I've gone ahead and reduced my environment to its simplest possible form and attached it below. It is an agent which spawns at the origin of a plane and walks until it gets close enough to the target at (50,50), until 500 steps have been passed, or if the agent walks out of  the state space. The state space is the xy-plane from -100 to 100. The action space is the direction of a step and is currently discretized into 100 possible directions.
[plane_walker.zip](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/files/9570094/plane_walker.zip)

**Comment by Cfckoh** [comment]
Problem resolved. Had to do with improperly resetting the environment. RLBase.test_runnable!() seems to not test RLBase.reset!()  the environment but creates a new environment from scratch each time?
