### ISSUE TITLE
Bounds Error at UPDATE_FREQ Step

### ISSUE THREAD

**Issue by ryan-o-c** [JuliaReinforcementLearning/ReinforcementLearning.jl#758]
Hello,

I've recreated a simple version of my project at the following link on my github:
https://github.com/ryan-o-c/RL-Env-Debugger/blob/main/Debugger.ipynb

The broad strokes are that I want to pass an image and vector to a CNN/Dense NN mix in my agent, and I seem to have managed this by passing the state as a flat vector and reshaping it inside the agent's NN architecture. However, when I reach the update stage, the generalised advantage function throws a bounds error that I don't quite understand. 

Please let me know if I can do anything else to more clearly outline the error - Any help is greatly appreciated!

(Small note on the code: the actions state and reward are greatly simplified for the sake of brevity, and so are essentially irrelevant (unless of course there is some reason they cause the error!). Also, the environment only "works" for n=5 - I simplified my code as much as possible while still ending at the same error in my more complex version of the environment)

**Comment by findmyway** [comment]
I spend some time debugging it. It seems the policy part has some problem:

```julia
AC.critic(flatten_batch(states_plus))

1×1 Matrix{Float32}:
 0.038754486
```

This should return a matrix of size `(1, batch_size)`. So you may need to check that part.


> The broad strokes are that I want to pass an image and vector to a CNN/Dense NN mix in my agent, and I seem to have managed this by passing the state as a flat vector and reshaping it inside the agent's NN architecture. 

Yeah, that's a bit awkward to do so in the current version. I promise this surely will be addressed in the next version (because I'm also working on a problem with different types of states involved).
