### ISSUE TITLE
Collect both number of steps and rewards in a single hook

### ISSUE THREAD

**Issue by kir0ul** [JuliaReinforcementLearning/ReinforcementLearning.jl#763]
I was wondering if it would make sense to have a single hook that collects both the number of steps per episode and the cumulated rewards? Which could look something like below:

```julia
Base.@kwdef mutable struct TotalRewardAndStepsPerEpisode <: AbstractHook
    steps::Vector{Int} = Int[]
    count::Int = 0
    rewards::Vector{Float64} = Float64[]
    reward::Float64 = 0.0
end
function (hook::TotalRewardAndStepsPerEpisode)(::PostActStage, agent, env)
    hook.count += 1
    hook.reward += reward(env)
end
function (hook::TotalRewardAndStepsPerEpisode)(::PostEpisodeStage, agent, env)
    push!(hook.steps, hook.count)
    hook.count = 0
    push!(hook.rewards, hook.reward)
    hook.reward = 0
end
```
I couldn't figure it out but maybe there's a way to do it using a [`ComposedHook`](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/src/ReinforcementLearningCore/src/core/hooks.jl#L34) instead?

Happy to try to make a PR if that's helpful :slightly_smiling_face:

**Comment by findmyway** [comment]
I'd suggest splitting them into independent hooks. That would make things easier to debug..

**Comment by kir0ul** [comment]
Just to clarify, those hooks already exist as [TotalRewardPerEpisode](https://juliareinforcementlearning.org/docs/rlcore/#ReinforcementLearningCore.TotalRewardPerEpisode) and [StepsPerEpisode](https://juliareinforcementlearning.org/docs/rlcore/#ReinforcementLearningCore.StepsPerEpisode). This is my naive attempt to get both info from the same hook, but I guess it would be cleaner to use `ComposedHook`, I just don't really understand how to use it...

**Comment by kir0ul** [comment]
Figured it out, that was actually as simple as `hook = ComposedHook(TotalRewardPerEpisode(), StepsPerEpisode())`... :grimacing:
