### ISSUE TITLE
Example run of Offline RL that totally depends on dataset without online environment

### ISSUE THREAD

**Issue by ppalmes** [JuliaReinforcementLearning/ReinforcementLearning.jl#765]
- the examples in offline rl still relies on the experiment to contain an online environment. is there an example where the run only includes an offline dataset for an agent to learn, i.e., `run(Experiment(agent,offline_dataset, stop_condition, hook))`

**Comment by jeremiahpslewis** [comment]
Closing all 'new feature' issues until refactor is complete.
