### ISSUE TITLE
Neural Network Approximator based policies not working

### ISSUE THREAD

**Issue by chandan21gupta** [JuliaReinforcementLearning/ReinforcementLearning.jl#770]
Hi
Nice work with the library. Easy to use.
I was experimenting with some deep reinforcement learning methods (mostly available on the project’s official website), however, none of them worked, due to one constant error I am facing :-
UndefVarError: params not defined
The traceback goes to the file src/policies/q_based_policies/learners/approximators/neural_network_approximator.jl
I believe this is because params is not defined, and it needs to be replaced with Flux.params. So will I need to make changes in the source code? Let me know.

**Comment by janstenner** [comment]
Hi! I also encountered that one and I found a workaround by running
`add OrdinaryDiffEq@5.71.2 SciMLBase@1.47.0 DiffEqBase@6.84.0 ReinforcementLearning@0.10.1`
in Pkg in the project.

After that, get a new workspace and try again.
Do not run update in Pkg - it will update the libraries mentioned in the command above and then things do not work anymore.

And also pls let me know if this helped.

**Comment by chandan21gupta** [comment]
Hi
I was actually able to solve the issue by changing the params function to Flux.params (attacking the exact problem). But yours sounds more reasonable considering no changes in the source code. Thanks for participating :)
