### ISSUE TITLE
Running experiments throws a "UndefVarError: params not defined" message

### ISSUE THREAD

**Issue by yosinlpet** [JuliaReinforcementLearning/ReinforcementLearning.jl#784]
Hi, I'm trying to run an experiment with SAC policy on a customized environment that passes the `is_runnable!(env)` test. 

However, after the following definition for the experiment:
```julia
using MyEnvStuff
using ReinforcementLearning
using StableRNGs
using Flux
using Flux.Losses
using IntervalSets
using CUDA

function RL.Experiment(::Val{:JuliaRL}, ::Val{:SAC}, ::Val{:MyEnv}, ::Nothing; save_dir=nothing, seed=123)
    envparams = EnvParams{Float64}(foo, bar, baz)
    env = MyEnv(envparams)

    rng = StableRNG(seed)
    init = glorot_uniform(rng)
    na = 1
    ns = N+3

    create_policy_net() = NeuralNetworkApproximator(model=GaussianNetwork(pre=Chain(Dense(ns, 30, relu, init=init),
                                                                                    Dense(30, 30, relu, init=init)),
                                                                          μ=Chain(Dense(30, na, init=init)),
                                                                          logσ=Chain(Dense(30, na, x -> clamp(x, typeof(x)(-10), typeof(x)(2)), init=init))),
                                                    optimizer=ADAM(0.003)) |> cpu

    create_q_net() = NeuralNetworkApproximator(model=Chain(Dense(ns + na, 30, relu; init=init),
                                                           Dense(30, 30, relu; init=init),
                                                           Dense(30, 1; init=init)),
                                               optimizer=ADAM(0.003)) |> cpu

    agent = Agent(policy=SACPolicy(policy=create_policy_net(),
                                   qnetwork1=create_q_net(),
                                   qnetwork2=create_q_net(),
                                   target_qnetwork1=create_q_net(),
                                   target_qnetwork2=create_q_net(),
                                   γ=0.99f0,
                                   τ=0.005f0,
                                   α=0.2f0,
                                   batch_size=64,
                                   start_steps=1000,
                                   start_policy=RandomPolicy(Space([-1.0 .. 1.0 for _ in 1:na]); rng=rng),
                                   update_after=1000,
                                   update_freq=1,
                                   automatic_entropy_tuning=true,
                                   lr_alpha=0.003f0,
                                   action_dims=na,
                                   rng=rng,
                                   device_rng=CUDA.functional() ? CUDA.CURAND.RNG() : rng),
                  trajectory=CircularArraySARTTrajectory(capacity=10000,
                                                         state=Vector{Float32} => (ns,),
                                                         action=Vector{Float32} => (na,)))

    stop_condition = StopAfterStep(100)
    hook = RewardsPerEpisode()
    Experiment(agent, env, stop_condition, hook, "# Play myEnv with SAC")
end
```
The call to 

E`JuliaRL_SAC_MyEnv`

throws the following error.
```
ERROR: LoadError: UndefVarError: params not defined
Stacktrace:
 [1] copyto!(dest::WARNING: both Losses and NNlib export "ctc_loss"; uses of it in module Flux must be qualified
NeuralNetworkApproximator{Chain{Tuple{Dense{typeof(relu), Matrix{Float32}, Vector{Float32}}, Dense{typeof(relu), Matrix{Float32}, Vector{Float32}}, Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}}}, Adam}, src::NeuralNetworkApproximator{Chain{Tuple{Dense{typeof(relu), Matrix{Float32}, Vector{Float32}}, Dense{typeof(relu), Matrix{Float32}, Vector{Float32}}, Dense{typeof(identity), Matrix{Float32}, Vector{Float32}}}}, Adam})
   @ ReinforcementLearningCore ~/.julia/packages/ReinforcementLearningCore/yeRLW/src/policies/q_based_policies/learners/approximators/neural_network_approximator.jl:40
 [2] #SACPolicy#233
   @ ~/.julia/packages/ReinforcementLearningZoo/tvfq9/src/algorithms/policy_gradient/sac.jl:87 [inlined]
 [3] Experiment(::Val{:JuliaRL}, ::Val{:SAC}, ::Val{:Fish}, ::Nothing; save_dir::Nothing, seed::Int64)
   @ Main ~/.julia/dev/Swimmers/fishenv.jl:59
 [4] Experiment
   @ ~/.julia/dev/Swimmers/fishenv.jl:9 [inlined]
 [5] Experiment(s::String)
   @ ReinforcementLearningCore ~/.julia/packages/ReinforcementLearningCore/yeRLW/src/core/experiment.jl:46
 [6] var"@E_cmd"(__source__::LineNumberNode, __module__::Module, s::Any)
   @ ReinforcementLearningCore ~/.julia/packages/ReinforcementLearningCore/yeRLW/src/core/experiment.jl:36
in expression starting at REPL[2]:1
```

I have the same issue when trying to execute experiments proposed in the docs.

Here are my pkg versions:
[e575027e] ReinforcementLearningBase v0.9.7
[158674fc] ReinforcementLearning v0.10.1
[052768ef] CUDA v3.13.1
[587475ba] Flux v0.13.4
[872c559c] NNlib v0.8.19

Is it a version issue? or am I doing something other wrong?

**Comment by rnilva** [comment]
Adding `using Flux: params` to `neural_network_approximator.jl` fixed the problem for me

**Comment by yosinlpet** [comment]
For some reason i cannot modify this file:

```
(@v1.8) pkg> dev ReinforcementLearningCore
Path `/xxxx/.julia/dev/ReinforcementLearning` exists and looks like the correct repo. Using existing path.
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ReinforcementLearning [158674fc]:
 ReinforcementLearning [158674fc] log:
 ├─possible versions are: 0.2.0-0.10.2 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.2.0-0.10.2
 ├─restricted by compatibility requirements with ReinforcementLearningCore [de1b191a] to versions: 0.2.0-0.3.0 or uninstalled, leaving only versions: 0.2.0-0.3.0
 │ └─ReinforcementLearningCore [de1b191a] log:
 │   ├─possible versions are: 0.9.1 or uninstalled
 │   └─ReinforcementLearningCore [de1b191a] is fixed to version 0.9.1
 └─restricted by compatibility requirements with Flux [587475ba] to versions: 0.4.0-0.10.2 or uninstalled — no versions left
   └─Flux [587475ba] log:
     ├─possible versions are: 0.4.1-0.13.13 or uninstalled
     ├─restricted to versions 0.13 by ReinforcementLearningCore [de1b191a], leaving only versions 0.13.0-0.13.13
     │ └─ReinforcementLearningCore [de1b191a] log: see above
     └─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.4.1-0.10.4, 0.13.12-0.13.13] or uninstalled, leaving only versions: 0.13.12-0.13.13
       └─CUDA [052768ef] log:
         ├─possible versions are: 0.1.0-4.0.1 or uninstalled
         └─restricted to versions 4 by ReinforcementLearningCore [de1b191a], leaving only versions 4.0.0-4.0.1
           └─ReinforcementLearningCore [de1b191a] log: see above

(@v1.8) pkg> status
Status `~/.julia/environments/v1.8/Project.toml`
⌅ [052768ef] CUDA v3.13.1
⌃ [587475ba] Flux v0.13.4
⌃ [f6369f11] ForwardDiff v0.10.34
⌃ [7ed4a6bd] LinearSolve v1.37.0
  [872c559c] NNlib v0.8.19
⌃ [91a5bcdd] Plots v1.38.5
⌃ [158674fc] ReinforcementLearning v0.10.1
  [295af30f] Revise v3.5.1
  [860ef19b] StableRNGs v1.0.0
Info Packages marked with ⌃ and ⌅ have new versions available, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`

(@v1.8) pkg> status --outdated
Status `~/.julia/environments/v1.8/Project.toml`
⌅ [052768ef] CUDA v3.13.1 (<v4.0.1): Flux, NNlibCUDA, ReinforcementLearningCore, ReinforcementLearningZoo
⌃ [587475ba] Flux v0.13.4 (<v0.13.13)
⌃ [f6369f11] ForwardDiff v0.10.34 (<v0.10.35)
⌃ [7ed4a6bd] LinearSolve v1.37.0 (<v1.38.0)
⌃ [91a5bcdd] Plots v1.38.5 (<v1.38.6)
⌃ [158674fc] ReinforcementLearning v0.10.1 (<v0.10.2)
```

**Comment by jeremiahpslewis** [comment]
@yosinlpet Can you try updating your environment (e.g. to RL.jl 0.10.2)?

**Comment by yosinlpet** [comment]
Yields the same result

**Comment by jeremiahpslewis** [comment]
Can you create a minimum working example without the `MyEnvStuff` stuff?

**Comment by yosinlpet** [comment]
https://juliareinforcementlearning.org/docs/experiments/experiments/Policy%20Gradient/JuliaRL_SAC_Pendulum/#JuliaRL\\_SAC\\_Pendulum

Following this just produces the same outcome

**Comment by jeremiahpslewis** [comment]
Thanks. Can you please try:

```julia
 Pkg.add(url="https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl.git"; subdir="src/ReinforcementLearningCore", rev="patch-v10.1.1")
```

I tried it in a clean env and it worked for me; if it fails, can you try it in a fresh environment?

...if it works, I'll tag a patch release with the fix.

**Comment by yosinlpet** [comment]
Seems to be working. Thanks a lot!

**Comment by jeremiahpslewis** [comment]
Great!

**Comment by jeremiahpslewis** [comment]
@JuliaRegistrator register subdir=src/ReinforcementLearningCore branch=patch-v10.1.1

**Comment by janstenner** [comment]
@jeremiahpslewis can you tell me roughly when we can expect this fix to be in a official Release of the whole RL.jl?

The way I understand it, it should have been included in the new release version of last friday.
It would REALLY be great to have this issue finally resolved in a non-workaround way.

**Comment by jeremiahpslewis** [comment]
@janstenner Once this PR is merged (https://github.com/JuliaRegistries/General/pull/79028#issuecomment-1456328046), you should be able to update your environment and the bug should go away.

If you want to contribute to RL.jl, you are warmly welcome to; at the moment there are many different opportunities...

- triaging issues
- filing PRs for these issues
- adding tests to libraries

I'm new to actively working on the project (though I've been using the project for a bit longer) and the user to contributor ratio could be rebalanced a bit to more contribution, so it's hard to make specific guarantees for what can or can't be expected from a software release.

What certainly is the case:

1. Any version which is previously tagged can be patched if someone identifies a bug and a fix
2. Any code on the main/master branch has passed CI/CD. Due to the limited number of tests in the project, this does not *yet* guarantee correctness or completeness. But that's the direction things can be headed if there is enough contributor support!
3. The project is caught in the midst of a major refactor (the file which had a bug in it doesn't exist on the main/master branch), it will be tricky (but is certainly possible) to complete the refactor. At the moment, I think it helps to tag sub-packages, e.g. RLCore / RLBase whenever updates are made, so that these packages can be used upstream, issues can be identified and test suites can be expanded. Once these packages have reached a sufficient level of feature-completeness, a new version of ReinforcementLearning.jl can be tagged. Until then, the latest versions of sub-packages reflect the refactor, the latest version of the overall packages reflects the last feature complete release of the system.

**Comment by jeremiahpslewis** [comment]
(If you don't see the release yet, try ```add ReinforcementLearningCore@v0.8.13``` in the pkg REPL.

**Comment by jeremiahpslewis** [comment]
(and a v0.8.14 will follow so that Flux isn't pinned to an earlier version)

**Comment by yosinlpet** [comment]
Is there a way to make it compatible with latest OrdinaryDiffEq versions? 
```
(XXX) pkg> status --outdated
Project XXX v0.1.0
Status `~/.julia/dev/XXX/Project.toml`
⌅ [8197267c] IntervalSets v0.5.4 (<v0.7.4): ReinforcementLearningEnvironments, ReinforcementLearningZoo
⌃ [7ed4a6bd] LinearSolve v1.34.1 (<v1.38.0)
⌃ [1dea7af3] OrdinaryDiffEq v6.11.2 (<v6.49.0)
⌅ [e575027e] ReinforcementLearningBase v0.9.7 (<v0.11.0): ReinforcementLearning, ReinforcementLearningCore, ReinforcementLearningEnvironments, ReinforcementLearningZoo
⌅ [de1b191a] ReinforcementLearningCore v0.8.13 (<v0.9.1): ReinforcementLearning, ReinforcementLearningZoo
```

If I update OrdinaryDiffEq to latest version, then ReinforcementLearningCore goes back to v0.8.12

**Comment by jeremiahpslewis** [comment]
@yosinlpet Yep, this could be done, you'd need to do the following and I can review it:

1. Checkout this branch, create a new branch on your fork from it: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/tree/patch-RLCore-v0.8.14
2. Update `src/ReinforcementLearningCore/Project.toml` with the compat bounds as you would like them , dev your branch and run the tests locally to make sure it yields the dependencies you want.
3. File a pull request against https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/tree/patch-RLCore-v0.8.14 as the upstream branch, I'll review it, merge it, and release a patch release.

**Comment by yosinlpet** [comment]
Thanks.
Even when forcing the version of OrdinaryDiffEq in Project.toml, it stays to version 6.11.2.
It throws an error when I force update it... but I cannot figure out how to solve it.

'''
(@v1.8) pkg> add OrdinaryDiffEq@v6.49.0
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package StaticArrayInterface [0d7ed370]:
 StaticArrayInterface [0d7ed370] log:
 ├─possible versions are: 1.0.0-1.3.0 or uninstalled
 ├─restricted by compatibility requirements with OrdinaryDiffEq [1dea7af3] to versions: 1.2.0-1.3.0
 │ └─OrdinaryDiffEq [1dea7af3] log:
 │   ├─possible versions are: 4.0.0-6.49.0 or uninstalled
 │   └─restricted to versions 6.49.0 by an explicit requirement, leaving only versions 6.49.0
 └─restricted by compatibility requirements with Compat [34da2185] to versions: uninstalled — no versions left
   └─Compat [34da2185] log:
     ├─possible versions are: 1.0.0-4.6.1 or uninstalled
     └─restricted by compatibility requirements with ReinforcementLearningCore [de1b191a] to versions: 3.0.0-3.46.1
       └─ReinforcementLearningCore [de1b191a] log:
         ├─possible versions are: 0.1.0-0.9.1 or uninstalled
         ├─restricted to versions 0.8 by ReinforcementLearning [158674fc], leaving only versions 0.8.0-0.8.13
         │ └─ReinforcementLearning [158674fc] log:
         │   ├─possible versions are: 0.10.2 or uninstalled
         │   └─ReinforcementLearning [158674fc] is fixed to version 0.10.2
         ├─restricted by compatibility requirements with ReinforcementLearningZoo [d607f57d] to versions: 0.8.2-0.8.13
         │ └─ReinforcementLearningZoo [d607f57d] log:
         │   ├─possible versions are: 0.1.0-0.6.0 or uninstalled
         │   ├─restricted to versions 0.5 by ReinforcementLearning [158674fc], leaving only versions 0.5.0-0.5.12
         │   │ └─ReinforcementLearning [158674fc] log: see above
         │   └─restricted by compatibility requirements with Setfield [efcf1570] to versions: [0.1.0-0.1.1, 0.5.1-0.6.0] or uninstalled, leaving only versions: 0.5.1-0.5.12
         │     └─Setfield [efcf1570] log:
         │       ├─possible versions are: 0.2.0-1.1.1 or uninstalled
         │       ├─restricted by compatibility requirements with LinearSolve [7ed4a6bd] to versions: 0.7.0-1.1.1
         │       │ └─LinearSolve [7ed4a6bd] log:
         │       │   ├─possible versions are: 0.1.0-1.38.0 or uninstalled
         │       │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-1.38.0
         │       │   ├─restricted by compatibility requirements with OrdinaryDiffEq [1dea7af3] to versions: 1.9.0-1.38.0
         │       │   │ └─OrdinaryDiffEq [1dea7af3] log: see above
         │       │   └─restricted by compatibility requirements with DocStringExtensions [ffbed154] to versions: [0.1.0-0.1.6, 1.20.0-1.38.0] or uninstalled, leaving only versions: 1.20.0-1.38.0
         │       │     └─DocStringExtensions [ffbed154] log:
         │       │       ├─possible versions are: 0.4.6-0.9.3 or uninstalled
         │       │       ├─restricted by compatibility requirements with OrdinaryDiffEq [1dea7af3] to versions: 0.8.0-0.9.3
         │       │       │ └─OrdinaryDiffEq [1dea7af3] log: see above
         │       │       └─restricted by compatibility requirements with DiffEqBase [2b5f629d] to versions: 0.9.0-0.9.3
         │       │         └─DiffEqBase [2b5f629d] log:
         │       │           ├─possible versions are: 3.13.2-6.121.1 or uninstalled
         │       │           └─restricted by compatibility requirements with OrdinaryDiffEq [1dea7af3] to versions: 6.116.0-6.121.1
         │       │             └─OrdinaryDiffEq [1dea7af3] log: see above
         │       ├─restricted by compatibility requirements with ReinforcementLearningCore [de1b191a] to versions: 0.6.0-0.8.2, leaving only versions: 0.7.0-0.8.2
         │       │ └─ReinforcementLearningCore [de1b191a] log: see above
         │       └─restricted by compatibility requirements with DiffEqBase [2b5f629d] to versions: 0.8.0-1.1.1, leaving only versions: 0.8.0-0.8.2
         │         └─DiffEqBase [2b5f629d] log: see above
         └─restricted by compatibility requirements with Setfield [efcf1570] to versions: [0.1.0-0.2.5, 0.8.4-0.9.1] or uninstalled, leaving only versions: 0.8.4-0.8.13
           └─Setfield [efcf1570] log: see above
'''

**Comment by filchristou** [comment]
Hello. My two cents on this:
- In latest release v0.10.2 the example I tried still throws the same error (https://juliareinforcementlearning.org/docs/experiments/experiments/DQN/JuliaRL_BasicDQN_CartPole/#JuliaRL\\_BasicDQN\\_CartPole). The main branch still uses 0.8.12, thus also fails.
- Could someone please explain to me why `ReinforcementLearning/Project.toml`'s `compat` expects `ReinforcementLearningCore = "0.8"`, but `JuliaReinforcementLearning/ReinforcementLearning.jl/src/ReinforcementLearningCore/Project.toml` has `version = "0.9.1"` ? I just checked the main branch and I would expect them to align. I find this nested module structure rather mind bending :sweat_smile:
- Given that there is still a rather extended collection of doc examples, have you thought wrapping them with [doctests](https://documenter.juliadocs.org/stable/man/doctests/) ? Such problems will then be minimized.
However, it will make the generation of docs much slower.

**Comment by jeremiahpslewis** [comment]
- The structure is mind bending, but especially so as we are currently in the awkward middle of a refactor. It's not wrong to think of the monorepo as a collection of related packages, which could equally well be in separate repositories. Each sub-package can depend on an arbitrary version of the other sub packages, as long as it's been registered and is `Pkg.add`'able. That said, once the refactor is complete, the `main` branch should reflect a consistent set of interoperable package versions, though this isn't technically required (albeit a very reasonable thing to have).
- The current refactor state means that serving two goals at once is tricky: making it possible for development to continue and always offering a working and stable version of the pkg. The `compat` bounds on the overall RL.jl reflect what *should* be a working combination of sub-package versions, unfortunately this seems to not fully be the case.
- Doctests sounds like a reasonable idea; my personal priority is having smaller unit and integration tests for each package, so we get fast feedback as to what isn't working as it should (even better if we do so **before** a PR is merged).

**Comment by jeremiahpslewis** [comment]
As far as a temporary fix goes, @filchristou can you try `Pkg.update()`? When I do that, I get `v0.8.13`.

**Comment by filchristou** [comment]
I still get `v0.8.12` in a new environment with julia v1.8.5
However my based environment is not totally clean, but it would be weird if that's the issue because it's rather minimal (not very different from the discussion [here](https://julialang.zulipchat.com/#narrow/stream/225542-helpdesk/topic/.E2.9C.94.20What.20packages.20do.20you.20install.20in.20root))

I am trying to find the source code for `./JuliaReinforcementLearning/ReinforcementLearning.jl/src/ReinforcementLearningCore/Project.toml` `v0.8.12` and `v.0.8.13` [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/commits/main/src/ReinforcementLearningCore/Project.toml), but I am confused because the history goes from `v0.8.11` in e90240c587ba22c68c01ae78b743f29a447b8314 to `v0.9.0-dev` in c67a604336923ee9120d75dee74456759860fcda

**Comment by filchristou** [comment]
So I tried again and the results are the same. However, if I explicitly do `Pkg.update("ReinforcementLearningCore")`  (I guess that's what you were doing @jeremiahpslewis  ?) and not just `Pkg.update()` I will get what we are after.
Here is how the manifest is updated:
![image](https://user-images.githubusercontent.com/27723218/224982821-542a68b9-01b1-4468-8f71-b33fdc5a93ca.png)

So, I guess because if `ReinforcementLearningCore` is `v0.8.13` then `Flux` must be decreased from `v0.13.4 ⇒ v0.12.10`, julia decides to keep `ReinforcementLearningCore` `v0.8.12`.
I don't know how the julia package manager decides the exact versioning but being both `ReinforcementLearningCore` and `Flux` "soft" constraints, it makes sense to select a patch lower in the one, to get a minor version higher in the other.
That changes if we specifically ask to update `ReinforcementLearningCore` or fix it to `v0.8.13`.

I guess to resolve it ReinforcementLearning.jl must have a compat of `ReinforcementLearningCore = "0.8.13"`.

**Comment by filchristou** [comment]
> I guess to resolve it ReinforcementLearning.jl must have a compat of ReinforcementLearningCore = "0.8.13".

That being said, given that there is a reason for `ReinforcementLearningCore@v0.8.13` to not support `@Flux@v0.13`

**Comment by jeremiahpslewis** [comment]
@filchristou Probably not, it’s just difficult to say with confidence given the limited number of tests. Want to check out the tag, update the compat bounds and see if there are issues? Then I can tag a `v0.8.13` with flux `v0.13` and bump RL.jl to require `v0.8.13`

**Comment by yosinlpet** [comment]
Any news on this?
