### ISSUE TITLE
Package Stabilization Plan

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaReinforcementLearning/ReinforcementLearning.jl#792]
Hey!

Right now it seems like the package is caught in the middle of a really important (but overwhelming refactor). Would the following approach be worth consideration?

- [x] 1. Add `compat` constraints to `ReinforcementLearning.jl`, tag a new `0.10.2` release
- [ ] 2. Tag new releases of `ReinforcementLearningBase` & `ReinforcementLearningCore`
    - [x] ReinforcementLearningBase.jl
    - [x] ReinforcementLearningCore.jl
    - [x] ReinforcementLearningEnvironments.jl
    - [x] ReinforcementLearningZoo.jl
    - [x] ReinforcementLearningExperiments.jl
- [ ] 3. Get `tabular` algorithms from `ReinforcementLearningZoo` working, release new version
- [ ] 4. Start chipping away at `ReinforcementLearningExperiments`, tag releases as experiments are ported
- [ ] 5. Once all code either updated or dropped, tag new release to `ReinforcementLearning.jl`

**Comment by HenriDeh** [comment]
Perhaps we could also make a v0.11 branch with the refactoring commits and keep a working master branch. And only merge the branch when v0.11 is ready.

**Comment by jeremiahpslewis** [comment]
This isn't up to date, but it's got the most information https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/614
