### ISSUE TITLE
How should ReinforcementLearning.jl be cited ?

### ISSUE THREAD

**Issue by felixchalumeau** [JuliaReinforcementLearning/ReinforcementLearning.jl#80]
Hi, 
I am wandering if there is a particular way this project should be cited in a scientific article!
Thanks

**Comment by jbrea** [comment]
I'd suggest

"Jun Tian et al., ReinforcementLearning.jl: A Reinforcement Learning Package for the Julia Language, https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl"

**Comment by felixchalumeau** [comment]
ok ! 
Then, what about adding a CITATION.bib file in the repo with something like : 
```
@misc{Tian2020Reinforcement,
  author       = {Jun Tian and other contributors},
  title        = {ReinforcementLearning.jl: A Reinforcement Learning Package for the Julia Language},
  year         = 2020,
  url          = {https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl}
}
```

To make it clear and easy to use in BibTex style bibliographies !

**Comment by findmyway** [comment]
Updated with https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/188
