### ISSUE TITLE
I get NNlib error when trying to load a model

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#82]
I also get `ERROR: LoadError: UndefVarError: NNlib not defined` when I try to load a model trained with ReinforcementLearning.jl.

```
using ReinforcementLearning

run(E`JuliaRL_BasicDQN_CartPole`)
agent = RLCore.load("/Users/andriy/Projects/physics-informed-nn/checkpoints/JuliaRL_BasicDQN_CartPole_2020_10_06_23_19_25", Agent)
```

and the error is:
```
[ Info: loading agent from /Users/andriy/Projects/physics-informed-nn/checkpoints/JuliaRL_BasicDQN_CartPole_2020_10_06_23_19_25
ERROR: LoadError: UndefVarError: NNlib not defined
```

**Comment by findmyway** [comment]
Thanks for reporting.

You need to bring the `NNlib` (and maybe some other necessary packages) into the MAIN first:

```julia
pkg > add NNLib

julia > using NNLib
```
<hr>
Loading a saved model is a bit tricky here. We are using `BSON.jl` for (de)serialization and it will not automatically load the module it encounters, see  [here](https://github.com/JuliaIO/BSON.jl/issues/30#issuecomment-473943757)

**Comment by drozzy** [comment]
I just wanted to see how my agent balances the pole. It would be awesome if the example/training played an episode or two of trained agent.
Is there an option for that?
Even if I manage to load it - I've no idea how to make it render :-)

**Comment by findmyway** [comment]
Good question.

This part is not well documented. I create an issue here https://github.com/JuliaReinforcementLearning/JuliaReinforcementLearning.github.io/issues/11 to track it.

The basic idea to do rendering is that we call the `display` function to show the environment after each step:

```julia
julia> e = E`JuliaRL_BasicDQN_CartPole`;

julia> Flux.testmode!(e.agent)  # we need to re-export the testmode! and trainmode later

julia> run(e.agent, e.env, StopAfterEpisode(1), DoEveryNStep((n, agent, env) -> (display(env);sleep(0.5);), 1)) 

julia> Flux.trainmode!(e.agent)

julia> run(e) 

julia> Flux.testmode!(e.agent)  # Now we test again to see the result after training

julia> run(e.agent, e.env, StopAfterEpisode(1), DoEveryNStep((n, agent, env) -> (display(env);sleep(0.5);), 1))
```

And of course, you can execute the same hook during training ;)

**Comment by drozzy** [comment]
Thanks. Another question, since I'm new to Julia, if I wanted to find that part in the source code, how would I go about it?
I mean - should I look for `display` in RLCore or other packages?

**Comment by findmyway** [comment]
You can use `@which` macro to find out where's the source code:

For example:

```julia
@which display(e.env)
```

The related source code here is: https://github.com/JuliaReinforcementLearning/ReinforcementLearningEnvironments.jl/blob/master/src/environments/classic_control/cartpole.jl#L141

**Comment by drozzy** [comment]
Thanks!
