### ISSUE TITLE
Logo image was not found

### ISSUE THREAD

**Issue by filchristou** [JuliaReinforcementLearning/ReinforcementLearning.jl#836]
Hey guys. I think there is a problem with showing the package logo in the README.md
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/main/README.md

Last tag that's working fine seems to be `v0.8.0`

Also the `Home` page of the docs misses a couple of images:
https://juliareinforcementlearning.org/docs/

**Comment by jeremiahpslewis** [comment]
Thanks for catching this, looks like the default branch rename -> `main` broke some hard coded links.

**Comment by natema** [comment]
Just a notice that many images and links are still broken (using `master`) in the docs.

**Comment by jeremiahpslewis** [comment]
@natema Thanks for the report! Would you be willing to submit a PR for fixing this?

**Comment by natema** [comment]
I'd be happy to, but I'm not sure of the nature of the problem yet. AFAIU, your PR #837 replaced `master` with `main` in the source, but there is no GitHub workflow to automatically build the docs. If that's correct, I'll rebuild them and do a PR, and maybe a second one to add the GitHub action.

**Comment by natema** [comment]
I confirm, the images in the docs look fine now.
