### ISSUE TITLE
update docs: Tips for developers

### ISSUE THREAD

**Issue by filchristou** [JuliaReinforcementLearning/ReinforcementLearning.jl#844]
Currently I think https://juliareinforcementlearning.org/docs/tips/ is outdated.
There are no `Manifest.toml`s to begin with.

I found issue #704 where a more current recommendation is made on how to develop RL.jl

However also [this recommendation](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/704#issuecomment-1165616064) didn't work for me:
```julia
(TestReinforcementLearningjl) pkg> st
Status `~/.julia/dev/TestReinforcementLearningjl/Project.toml`
  [e575027e] ReinforcementLearningBase v0.11.0 `../ReinforcementLearning/src/ReinforcementLearningBase`
  [de1b191a] ReinforcementLearningCore v0.9.1 `../ReinforcementLearning/src/ReinforcementLearningCore`
  [25e41dd2] ReinforcementLearningEnvironments v0.7.1 `../ReinforcementLearning/src/ReinforcementLearningEnvironments`
  [d607f57d] ReinforcementLearningZoo v0.6.0 `../ReinforcementLearning/src/ReinforcementLearningZoo`

(TestReinforcementLearningjl) pkg> dev ../ReinforcementLearning/
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ReinforcementLearningEnvironments [25e41dd2]:
 ReinforcementLearningEnvironments [25e41dd2] log:
 ├─possible versions are: 0.7.1 or uninstalled
 ├─restricted to versions 0.6 by ReinforcementLearning [158674fc] — no versions left
 │ └─ReinforcementLearning [158674fc] log:
 │   ├─possible versions are: 0.10.2 or uninstalled
 │   └─ReinforcementLearning [158674fc] is fixed to version 0.10.2
 └─ReinforcementLearningEnvironments [25e41dd2] is fixed to version 0.7.1

```

**Comment by jeremiahpslewis** [comment]
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/13e15fe43dd66362dc70aad0e256be203dd6ac2c/src/devmode.jl#L12

**Comment by jeremiahpslewis** [comment]
PR: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/845

**Comment by filchristou** [comment]
Sadly it's not working due to a dependency conflict.. 
![image](https://user-images.githubusercontent.com/27723218/225038624-920958c1-54d1-4866-aacb-a92e07c99b40.png)
can someone reproduce ?

**Comment by jeremiahpslewis** [comment]
Can you try cloning a fresh copy, activating a new environment within the base directory of that copy?

**Comment by filchristou** [comment]
I just did and I get the same error..

**Comment by HenriDeh** [comment]
The dependency tree of RL.jl gives me headaches. Perhaps the dev order in `activate_devmode!()` needs to change again.

**Comment by jeremiahpslewis** [comment]
The issue is that the RL.jl `Project.toml` is still oriented around a mix of past package versions, which are mutually conflicting. In #846 I bump the bounds to the current 'post refactor' versions of the packages. I won't tag a release of RL.jl, but we need this update to make the `devmode` work (and other alternatives like a second `Project.toml` file are even less appealing.

**Comment by filchristou** [comment]
Now I am getting quite a few `Error watching manifest`. 
![image](https://user-images.githubusercontent.com/27723218/225268677-d8dbeb3c-5f26-4d97-9039-793ecced9ae5.png)

However the environment looks fine 
![image](https://user-images.githubusercontent.com/27723218/225268893-47cc035b-c96b-4cd8-9308-5cbd881226b8.png)

are these errors expected ?

**Comment by jeremiahpslewis** [comment]
Try deleting the manifest?

**Comment by filchristou** [comment]
true. sorry. thanks a lot for the support!
