### ISSUE TITLE
ACME RL lib by deepmind

### ISSUE THREAD

**Issue by drozzy** [JuliaReinforcementLearning/ReinforcementLearning.jl#85]
Not sure if this is useful, I wasn't sure where to put this - so I'll just make a fake issue.

ACME by DeepMind has a really nice architecture in my opinion (after trying rllib, stable-baselines, and some others). 

https://github.com/deepmind/acme
https://arxiv.org/abs/2006.00979
https://deepmind.com/research/publications/Acme

Their conceptual model is easy to understand, for example, actor "observes" each step and some of their diagrams are pretty nice (see paper: https://arxiv.org/pdf/2006.00979.pdf)

**Comment by findmyway** [comment]
Thanks for the link.

I've skimmed it before and also agree that it's much better.  I'd be glad to discuss it with you after taking some time to absorb the essence.

(We can keep it open ;)

**Comment by findmyway** [comment]
I created a draft design here: https://github.com/JuliaReinforcementLearning/DistributedReinforcementLearning.jl

The core ideas are very close to those described in ACME. And I think the underlying actor model may be useful to implement algorithms like https://github.com/EricSteinberger/Deep-CFR , AlphaZero and many other interesting algorithms.
