### ISSUE TITLE
Rename update! to push!

### ISSUE THREAD

**Issue by jeremiahpslewis** [JuliaReinforcementLearning/ReinforcementLearning.jl#883]
All of our ! methods do some form of updating, so to avoid confusion, the current use of update for update!(hook, stage) and update!(policy, stage) could be renamed push! to increase clarity, stick with standard Julia conventions

**Comment by jeremiahpslewis** [comment]
@HenriDeh what are your thoughts?

**Comment by HenriDeh** [comment]
I guess we could, `push!` is meant to be used when something is added to a collection - and by the looks of it, this is what's happening everywhere update is used. Either something is pushed to the cache, to the trajectory, or to a hook.
