### ISSUE TITLE
Contribute Neural Fitted Q-iteration algorithm 

### ISSUE THREAD

**Issue by CasBex** [JuliaReinforcementLearning/ReinforcementLearning.jl#895]
Hi, I implemented Neural Fitted Q-iteration (NFQ) from [1] with the ReinforcementLearning.jl framework and would like to contribute to ReinforcementLearningZoo.jl. Currently it is in a separate project with version 0.10.2 of ReinforcementLearning.jl as dependency. 

I did not yet manage to integrate NFQ with the codebase here, as it seems to have changed quite a lot compared to the version available at the Julia package general registry. If anybody could provide some guidance with the pull request, I would be glad to contribute my implementation.

[1] Riedmiller, M. (2005). Neural Fitted Q Iteration – First Experiences with a Data Efficient Neural Reinforcement Learning Method. In: Gama, J., Camacho, R., Brazdil, P.B., Jorge, A.M., Torgo, L. (eds) Machine Learning: ECML 2005. ECML 2005. Lecture Notes in Computer Science(), vol 3720. Springer, Berlin, Heidelberg. https://doi.org/10.1007/11564096_32

**Comment by HenriDeh** [comment]
Hello, there is "how to implement an algorithm" guide in the docs here: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/main/docs/src/How_to_implement_a_new_algorithm.md. This is the up to date version that follows the new refactored api.

**Comment by HenriDeh** [comment]
Don't hesitate to ask questions if you need.

**Comment by jeremiahpslewis** [comment]
@CasBex One important note: you will want to import the sub-packages `ReinforcementLearningCore` and `ReinforcementLearningBase` directly, as the overarching package `ReinforcementLearning` is pinned to older versions of RLCore and RLBase until the refactor is complete.

@HenriDeh skimming the link you posted, I think we need to make a few tweaks to the doc, I'll send a PR your way.

**Comment by jeremiahpslewis** [comment]
See: https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/896/files
