### ISSUE TITLE
Vectorized environments

### ISSUE THREAD

**Issue by sash-a** [JuliaReinforcementLearning/ReinforcementLearning.jl#908]
Hi there, in my spare time I've been making a [CleanRL](https://github.com/vwxyzjn/cleanrl) inspired library in julia ([CleanRL.jl](https://github.com/sash-a/CleanRL.jl)) and of course I've been using a fair amount of this library, however I find that a vectorized environment wrapper is lacking. As someone who's job it is to work with RL in jax I've seen the [impressive benefits](https://chrislu.page/blog/meta-disco/) of `vmap` first hand so it would be quite nice to have this in julia also. 

I do see there is a `MultiThreadedEnv`. I have [used it](https://github.com/sash-a/CleanRL.jl/blob/feat/parallel-envs/src/algorithms/ppo.jl#L67) and seen some good speedup, however I _think_ the speedup from vectorizing (or both parallelizing and vectorizing) `step` and `reset`  would be more impressive.

I assumed `@turbo`/`vmap` from LoopVectorizations would be a simple replacement for the `@sync` calls in the `MultiThreadEnv`. However I can't seem to get this to work. I'd be happy to contribute this wrapper if 1. people thought it would be useful to have both a `MultiThreadEnv` and `VectorizedEnv` wrapper and 2. if someone could point me in the right direction as to how to implement it. Below is a way to replicate the error I'm seeing when trying to implement this, can't find too much online about it.

```julia
using ReinforcementLearning
using LoopVectorization

n = 10
envs = [CartPoleEnv() for _ in 1:n]
acts = rand.(action_space.(envs))

x = zeros(length(state_space(first(envs))), n)

@turbo for i in 1:n
  reset!(envs[i])
  x[:, i] = state(envs[i])
end
```

```
Error: ERROR: LoadError: Don't know how to handle expression.
reset!
```

If I switch the reset for: `envs[i](acts[i])` I get a different error:

```
ERROR: LoadError: TypeError: in typeassert, expected Symbol, got a value of type Expr
```

I did see some minor success when using `LoopVectorizations.vmap` although I couldn't use it with the env's `__call__` (not sure what it's called in julia) as I couldn't find out how to pass that method around. So I had to copy the `_step` method out of cart pole and `vmap` that, which is of course not ideal and only saw minor speed improvements.

I have a theory as to why this is happening, but this is my first time using `LoopVectorizations.jl` so was hoping to get some advice here first. Maybe this thread is better suited to an issue in `LoopVectorizations.jl`, but would still appreciate any thoughts/advice you have and if you can point me in the right direction of how to fix this, I'm happy to open a PR and contribute this wrapper.

**Comment by HenriDeh** [comment]
Hello, thanks for wanting to contribute. In my opinion, vectorized environments are most welcome, so if you want to make a PR we'll help as much as we can. 

Regarding LV, I personnaly never used it, (I don't know about you @jeremiahpslewis ?), so I can't really help. I think a post on discourse or a question on slack is more likely to reach to more people.

**Comment by Mytolo** [comment]
Have you tried to replace reset! with RLBase.reset!(env[i]) ? It might not work, but it can also the source of the issue here. I would love to have vectorized environments. Have you thought of how to solve trajectory issues for them? Or do you assume that the policy takes care of this? For the latter, one would need to reimplement / extend policies s.t. they are able to sample from vectorized Environments? 

At All: How is this currently implemented for MultiThreadEnvs?
