### ISSUE TITLE
Loading a Gym Environment 

### ISSUE THREAD

**Issue by EliottEccidio** [JuliaReinforcementLearning/ReinforcementLearning.jl#912]
Hi,
I am trying to work with you Gym env wrapper but when I call  GymEnv("HalfCheetah-v3") I have the following error :
```julia
ERROR: Gym environment HalfCheetah-v3 not found.

Run `ReinforcementLearningEnvironments.list_gym_env_names()` to find supported environments.
```
If we follow the stack trace it comes from the PyCall : gym.make(name) of the gym.jl file.
Moreover, when I tried ReinforcementLearningEnvironments.list_gym_env_names() I had the error:
```julia
ERROR: type Dict has no field all
```
It comes from the fact that you can't list all the ele,ents of a dictionnary using .all() anymore in the code of the gym.jl file :
```julia
[x.id for x in gym.envs.registry.all() if split(x.entry_point, ':')[1] in modules]
```
Maybe replacing it by :
```python 
[x.id for x in list(gym.envs.registry.keys()) if split(x.entry_point, ':')[1] in modules]
```
_Note: "HalfCheetah-v3" is in the dictionnary_

**Comment by Mytolo** [comment]
Essentially, there are a few things to adjust here:
- action and observation space domains use ZeroTo Type which is not present any more
- On my side RLEnvs.list_gym_envs() is working properly. Which version of RLJL do you use? The code you pasted seem not up to date with the upstream.

**Comment by EliottEccidio** [comment]
I was using RLJL v0.10.2 and v0.10.1. With thses two versions I have the rror maybe I processed wrongly I don't know I am still quite new to Julia.

**Comment by Mytolo** [comment]
Can you try the current repository version? I could not test it properly since i do not have a linux machine a.t.m. But i tested it with mujoco and it worked. Also try to use Julia >= 1.9 (current release).

**Comment by EliottEccidio** [comment]
Still not working for me with Julia 1.9.1 and RL.jl v0.10.2. Can you describe to me your environement how did youn launch it with Mujoco ?
