### ISSUE TITLE
Devmode is not working

### ISSUE THREAD

**Issue by Mytolo** [JuliaReinforcementLearning/ReinforcementLearning.jl#918]
I recognized lately that the compat version in the Project.toml files are not suited in order to call activate_devmode!() from `src/devmode.jl`.
In my opinion it may be beneficial for developers trying to get into contribution to have a Project.toml.dev or something like this in order to get the Project working. That way, julia handles all dependencies on its own and everybody has the same library state w.r.t the repository state.

What do you think about this?

**Comment by HenriDeh** [comment]
Doesn't it devs the local packages and ignores project.toml ? If you use the main branch.

**Comment by Mytolo** [comment]
Well it does not ignore the Project.toml. In my case it results in package resolve issues and i have to adjust the compat entries to the version in the repo.

**Comment by joelreymont** [comment]
@Mytolo You need to dev each sub-package individually, without importing the umbrella package.

 Personally, I would remove the top-level `activate_devmode!` function.
