### ISSUE TITLE
Generating trajectories with trained policy

### ISSUE THREAD

**Issue by rlrs** [JuliaReinforcementLearning/ReinforcementLearning.jl#92]
I'm trying to fill a trajectory (probably an `ElasticCompactSATrajectory`, although it seems undocumented) with on-policy observations from a trained QBasedPolicy. However I can't quite seem to get it right, perhaps because I don't quite get the behavior of batched environments as in A2C, or just lack of documentation on some of the things I'm using. 
Any advice on how to do this right?

**Comment by findmyway** [comment]
Hi @rlrs ,

Apologize that the doc is still missing...

I added an example usage in https://github.com/JuliaReinforcementLearning/JuliaReinforcementLearning.github.io/issues/13 .

For a batched environment, the `get_state`, `get_actions`, `get_reward`, `get_terminal` will return a batched result:

```
julia> using ReinforcementLearning

julia> env = MultiThreadEnv([
           CartPoleEnv(; T = Float32)
           for i in 1:4
       ])

julia> get_state(env)
4×4 Array{Float32,2}:
 -0.0251845   0.021126     0.00896491  -0.0231287
 -0.0374918  -0.0489418    0.034771     0.0117968
  0.031438    0.0346162   -0.030231     0.0106028
  0.0440059  -0.00303372   0.0192631   -0.0106544

julia> get_actions(env)
VectSpace{Array{DiscreteSpace{UnitRange{Int64}},1}}(DiscreteSpace{UnitRange{Int64}}[DiscreteSpace{UnitRange{Int64}}(1:2), DiscreteSpace{UnitRange{Int64}}(1:2), DiscreteSpace{UnitRange{Int64}}(1:2), DiscreteSpace{UnitRange{Int64}}(1:2)])

julia> get_reward(env)
4-element Array{Float32,1}:
 1.0
 1.0
 1.0
 1.0

julia> rand(get_actions(env)) |> env

julia> get_terminal(env)
4-element Array{Bool,1}:
 0
 0
 0
 0
```

So to use the `ElasticCompactSARTSATrajectory`, we need to initialize it correctly:

```julia
julia> traj = ElasticCompactSARTSATrajectory(;
       state_type = Float32,
       state_size = (4,4),
       action_type = Int,
       action_size = (4,),
       reward_type = Float32,
       reward_size = (4,),
       terminal_type = Bool,
       terminal_size = (4,)
       )

julia> policy = RandomPolicy(env)

julia> agent = Agent(;policy=policy, trajectory=traj)

julia> run(agent, env, StopAfterStep(200))

julia> traj[:action]
4×10 view(::ElasticArrays.ElasticArray{Int64,2,1,Array{Int64,1}}, :, 1:10) with eltype Int64:
 2  2  2  1  2  1  2  1  2  2
 1  2  1  1  1  1  1  1  2  2
 1  1  2  2  2  1  1  2  2  2
 1  2  2  2  2  2  2  1  1  1

julia> traj[:state]
4×4×10 view(::ElasticArrays.ElasticArray{Float32,3,2,Array{Float32,1}}, :, :, 1:10) with eltype Float32:
...
```

**Comment by rlrs** [comment]
Hey, thanks for the quick reply. It seems that the trajectories aren't updated in test mode, but I don't want to train the policy further, just obtain state-action trajectories.
I think this is a relatively common thing to do, so we should make it pretty straightforward. Perhaps a hook that populates a trajectory would be a good fit?

**Comment by rlrs** [comment]
Something like this works and seems pretty idiomatic for the library. I'm not sure about the PostEpisodeStage case, does that action actually get executed or can we just push the terminal state?

```
struct TrajectoryHook <: AbstractHook
    trajectory :: AbstractTrajectory
end

function (hook::TrajectoryHook)(::PreActStage, agent, env, action)
    push!(hook.trajectory; state = get_state(env), action = action)
end

function (hook::TrajectoryHook)(::PostActStage, agent, env)
    if !haskey(hook.trajectory, :reward) || !haskey(hook.trajectory, :terminal)
        return
    end
    push!(hook.trajectory; reward = get_reward(env), terminal = get_terminal(env))
end

function (hook::TrajectoryHook)(::PostEpisodeStage, agent, env)
    action = agent.policy(env)
    push!(agent.trajectory; state = get_state(env), action = action)
end
```

Usage like:
```
rolloutExpert = Agent(
    policy = RandomPolicy(env),
    trajectory = ElasticCompactSATrajectory(; state_type = Float32, state_size = (ns, N_ENV), action_type = Int, action_size=(N_ENV,))  # this doesn't get used
)
testmode!(rolloutExpert)
trajHook = TrajectoryHook(ElasticCompactSATrajectory(; state_type = Float32, state_size = (ns, N_ENV), action_type = Int, action_size=(N_ENV,)))
run(rolloutExpert, env, StopAfterStep(3), trajHook)

# imitate on collected data
@show trajHook.trajectory[:state]
@show trajHook.trajectory[:action]
```
>trajHook.trajectory[:state] = Float32[0.04856997 0.027148524 0.05152898 0.060928762 0.0531355 -0.055133417 -0.027149366 0.07186705 0.07791631 0.059662204 0.056829285 0.06810346 0.068526134 0.065013304 0.04067753 0.06614202; -0.051850937 0.025934882 0.18085082 -0.22200404 -0.010212004 0.35366347 0.14907931 0.03586383 0.025702756 -0.19170679 0.039804563 0.23137985 -0.23357525 0.2248271 0.22677888 -0.007695404; -0.00078665535 -0.010054223 -0.0021742117 -0.0038272324 -0.00033870433 0.025303045 0.039314087 -0.0006714915 -0.003452004 -0.012874313 -0.018479386 0.0010617087 -0.0008990195 -0.00026287313 0.025952399 -0.0037451363; 0.0796436 0.030674657 -0.25275406 0.3294259 0.03140065 -0.3260798 -0.22270565 -0.03897451 -0.02845934 0.3200577 0.06968408 -0.3283772 0.3315053 -0.31535804 -0.3066485 0.01117144]

>Float32[0.04753295 0.027667223 0.055145994 0.05648868 0.05293126 -0.04806015 -0.02416778 0.07258432 0.07843036 0.05582807 0.057625376 0.07273106 0.06385463 0.06950985 0.045213107 0.065988116; 0.14328228 -0.16904144 -0.014239999 -0.026827827 0.1849148 0.15819058 -0.046581857 -0.15924847 -0.16936952 0.0035961112 0.23518649 0.03624282 -0.038440533 0.029708903 0.031296913 -0.20276344; 0.0008062166 -0.00944073 -0.0072292928 0.0027612853 0.00028930866 0.01878145 0.034859974 -0.0014509817 -0.0040211906 -0.006473159 -0.017085705 -0.0055058347 0.0057310862 -0.0065700337 0.01981943 -0.0035217076; -0.21328743 0.32016847 0.03924225 0.03553852 -0.2613891 -0.025525998 0.08211467 0.25349647 0.26313242 0.02334268 -0.22877137 -0.035359655 0.038539033 
-0.02275806 -0.0058951383 0.30267036]
>trajHook.trajectory[:action] = [2 1; 1 2; 1 1; 2 2; 2 1; 1 2; 1 2; 1 2; 1 2; 2 1; 2 1; 1 1; 2 2; 1 1; 1 2; 1 2]

I do notice that with StopAfterStep(3) we end up with 2 states and 2 actions, but not the final state.

**Comment by findmyway** [comment]
> Hey, thanks for the quick reply. It seems that the trajectories aren't updated in test mode, but I don't want to train the policy further, just obtain state-action trajectories.
> I think this is a relatively common thing to do, so we should make it pretty straightforward. Perhaps a hook that populates a trajectory would be a good fit?

Yes, I also have the same need only very recently. I don't have an elegant solution to it yet. Created an issue here to track it https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/issues/156

> I do notice that with StopAfterStep(3) we end up with 2 states and 2 actions, but not the final state.

Yes, that's by design.

You can access all the 3 states and actions with `traj[:full_tate]` and `traj[:full_action]`, or access the later 2 with `traj[:next_state]` and `traj[:next_action]`.

**Comment by findmyway** [comment]
> I'm not sure about the PostEpisodeStage case, does that action actually get executed or can we just push the terminal state?

`PostEpisodeStage` will be executed after `PostActState`:

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/df518b60103277adfb0a49f30902b96dcc16b9c2/src/core/run.jl#L27-L31

In current implementation, we push the last state and the corresponding action (which is a dummy one just serves as a placeholder ) of an episode. In the `PreEpisode` stage, we pop out the last state and the dummy action. New state and action will be pushed in the following up `PreActStage`.

I think I may need to make a GIF to show these steps clearly...
