### ISSUE TITLE
Purpose and scope of sub-packages

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#93]
Creating this issue to discuss and track the scopes of all the sub-packages involved, like `RLBase`, `RLCore`, `RLEnvs`, `RLZoo` etc.. So that anyone who is unsure of what the focus of a package is, can easily refer to one place to understand the design decisions.

Plus tips for how to read the source code.

**Comment by findmyway** [comment]
The README in both ReinforcementLearning.jl and ReinforcementLearningCore.jl are updated.

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl#scope-of-each-package

https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl#code-structure
