### ISSUE TITLE
ReinforcementLearning vs Reinforce

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaReinforcementLearning/ReinforcementLearning.jl#94]
Hi, I've been implementing my RL logic in `ReinforcementLearning.jl`, but I noticed there is also `Reinforce.jl` which has almost the same api, but is much less mature. Is there any difference between the two?

**Comment by findmyway** [comment]
Hi @DhruvaSambrani ,

Glad to hear that you're working on something in this package.

Though these two packages share some similar APIs, they diverge in a lot of places.

Born from a package focusing on tabular reinforcement learning algorithms, I think the main difference is we have an ambitious goal to create a versatile package in Julia to tackle different kinds of tasks in reinforcement learning. This means we have to come up with a set of unified interfaces for many different fields including tabular rl, deep rl, multi-agent rl, model based rl... And it already makes many APIs very different from other packages. 

Things are still evolving and we don't know how far we'll go.
