### ISSUE TITLE
Hook RewardsPerEpisode broken

### ISSUE THREAD

**Issue by CasBex** [JuliaReinforcementLearning/ReinforcementLearning.jl#945]
The `RewardsPerEpisode` hook stores the history of rewards in a weird way. The array `hook.rewards` contains `n` entries after `n` episodes, and all entries are identical. All entries seem to be a concatenation of all past episodes without any indication when an episode finishes.

Below script should show what I mean:
```julia
using ReinforcementLearningBase
using ReinforcementLearningCore
using ReinforcementLearningEnvironments

n = 10
policy = RandomPolicy()
env = RandomWalk1D()
stop_condition = StopAfterEpisode(n)
hook = RewardsPerEpisode()
reset_condition = ResetAtTerminal()

result = run(policy, env, stop_condition, hook, reset_condition)

@show count.(!=(0), result.rewards) # .== n == 10 but should be ones(n)
@show all(==(result.rewards[1]), result.rewards) # should be false (most of the time)
@show result.empty_vect == result.rewards[1]
```
dependencies in `Project.toml` below
```
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
ReinforcementLearningCore = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
```

**Comment by HenriDeh** [comment]
Weird, are you working on the main branch ? @jeremiahpslewis made quite the test suite for hooks.

**Comment by jeremiahpslewis** [comment]
Can you do `Pkg.status()` and share the results?

**Comment by CasBex** [comment]
```  
  [e575027e] ReinforcementLearningBase v0.12.1 `~/.julia/dev/ReinforcementLearning/src/ReinforcementLearningBase`
  [de1b191a] ReinforcementLearningCore v0.12.2 `~/.julia/dev/ReinforcementLearning/src/ReinforcementLearningCore`
  [25e41dd2] ReinforcementLearningEnvironments v0.8.4 `~/.julia/dev/ReinforcementLearning/src/ReinforcementLearningEnvironments`
```

**Comment by jeremiahpslewis** [comment]
Thanks! I think I see the issue, will put together a PR soon.

**Comment by jeremiahpslewis** [comment]
@CasBex thanks for this bug report, detailed, clear and definitely correct! Do you mind checking out this PR to confirm the issue is resolved? https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/953
