### ISSUE TITLE
TD3 Policy unable to handle environments with multidimensional action spaces

### ISSUE THREAD

**Issue by gggoes** [JuliaReinforcementLearning/ReinforcementLearning.jl#951]
I built a custom RL environment and tested it with some RL algorithms, namely DDPG, TD3 and SAC. Results were pretty good overall, just SAC somehow fails to converge (though I believe that is still an open issue). Initially, I had ns=3 and na=1, that is, my action was at first a scalar value (not a vector made of 1 element). 

I then changed the environment to ns=9 and na=3, so now my action is a vector of 3 elements. DDPG has no trouble running it, but TD3 was unable to. I found this behaviour quite surprising, as DDPG and TD3 are very similar algorithms (TD3 is an improvement of DDPG). Here is the error I got.

```
ERROR: LoadError: BoundsError: attempt to access 3-element Vector{Float32} at index []
Stacktrace:
  [1] throw_boundserror(A::Vector{Float32}, I::Tuple{})
    @ Base ./abstractarray.jl:703
  [2] checkbounds
    @ ./abstractarray.jl:668 [inlined]
  [3] _getindex
    @ ./abstractarray.jl:1273 [inlined]
  [4] getindex(::Vector{Float32})
    @ Base ./abstractarray.jl:1241
  [5] WARNING: both Losses and NNlib export "ctc_loss"; uses of it in module Flux must be qualified
(::TD3Policy{NeuralNetworkApproximator{Chain{Tuple{Dense{typeof(hardtanh), Matrix{Float32}, Flux.Zeros}, Dense{typeof(hardtanh), Matrix{Float32}, Flux.Zeros}, Dense{typeof(hardtanh), Matrix{Float32}, Flux.Zeros}}}, ADAM}, NeuralNetworkApproximator{TD3Critic, ADAM}, NeuralNetworkApproximator{Chain{Tuple{Dense{typeof(hardtanh), Matrix{Float32}, Flux.Zeros}, Dense{typeof(hardtanh), Matrix{Float32}, Flux.Zeros}, Dense{typeof(hardtanh), Matrix{Float32}, Flux.Zeros}}}, ADAM}, NeuralNetworkApproximator{TD3Critic, ADAM}, PDControl{Float32}, StableRNGs.LehmerRNG})(env::ThrusterEnv{Float32})
    @ ReinforcementLearningZoo ~/.julia/packages/ReinforcementLearningZoo/tvfq9/src/algorithms/policy_gradient/td3.jl:125
```

I also made sure my buffer was set correctly. 

`
        trajectory = CircularArraySARTTrajectory(
            capacity = buffer_capacity,
            state = Vector{Float32} => (ns,),
            action = Vector{Float32} => (na,),
        ),`

I believe I was able to track down the cause of the problem. In function (p::DDPGPolicy)(env, player::Any = nothing), DDPG does:

```
        D = device(p.behavior_actor)
        s = DynamicStyle(env) == SEQUENTIAL ? state(env) : state(env, player)
        s = Flux.unsqueeze(s, dims=ndims(s) + 1)
        actions = p.behavior_actor(send_to_device(D, s)) |> vec |> send_to_host
        c =
            clamp.(
                actions .+ randn(p.rng, p.na) .* repeat([p.act_noise], p.na),
                -p.act_limit,
                p.act_limit,
            )
        p.na == 1 && return c[1]
        c
```
So if na=1, it returns a scalar, otherwise it returns a vector of size na. Since clamp is written element-wise, it has no problem dealing with vectors.

TD3 works a little bit different with (p::TD3Policy)(env)

```
        D = device(p.behavior_actor)
        s = state(env)
        s = Flux.unsqueeze(s, dims=ndims(s) + 1)
        action = p.behavior_actor(send_to_device(D, s)) |> vec |> send_to_host
        clamp(action[] + randn(p.rng) * p.act_noise, -p.act_limit, p.act_limit)
```

The clamp function is unable to handle vector inputs larger than one, as clamp is not working element-wise and thus I believe TD3 can't handle na>1. Clamp is line 125 in td3.jl, which is [5] in the error above. Unlike DDPG, TD3 has no na (number of actions) field. I think it might be helpful to add it. 

Fixing this behaviour seems doable to me, but again I am not sure if I am missing anything. Maybe update!(p::TD3Policy, batch::NamedTuple{SARTS}) needs some reworking as well? I am running Julia 1.8.2, the RL package is 0.10.1.

Feedback is welcome.

**Comment by HenriDeh** [comment]
Your analysis of the problem sounds reasonable. You could clone a local branch _at the release tag_ and try to see if your fix does it. 

The RL package is undergoing a massive refactor (has been for a long time, and it's not close to be done), so very little maintenance is done on algorithms on the released version. They are almost all broken on the main branch due to not having been refactored yet. If you feel like it, you can get acquainted with the refactor and the inner workings of the package and try to fix DDPG and TD3 on the main branch instead. This is a bigger commitment for you but in that case we'll be able and happy to help.

**Comment by gggoes** [comment]
Thank you for the reply @HenriDeh 

I will check my fix on a local branch as suggested and push it if it works. The solution seems to be pretty straightforward. I've also checked the SAC code after reading its paper, but still no idea on why it is broken.

As soon as I have the time I'll take a look at the refactor. Any tips on where to start or general recommendations would be appreciated.

**Comment by HenriDeh** [comment]
The best way in is the tutorial: (https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/main/docs/src/How_to_implement_a_new_algorithm.md). 

Wait for #955 to be merged so it's up to date.
