### ISSUE TITLE
Can implement this ARZ algorithm ?

### ISSUE THREAD

**Issue by zsz00** [JuliaReinforcementLearning/ReinforcementLearning.jl#965]
deepmind propose AutoRobotics-Zero (ARZ) a method based on AutoML-Zero that discovers zero-shot
adaptable policies from scratch.

Discovering Adaptable Symbolic Algorithms from Scratch
https://arxiv.org/pdf/2307.16890.pdf

If can help implement this ARZ algorithm ?

**Comment by HenriDeh** [comment]
Hello, the package is undergoing a refactoring at the moment and implementing new algorithms is not the priority.
Of course you are most welcome if you wish to contribute to the package. In that case tell us and we will guide you.
