### ISSUE TITLE
Use JLSO for (de)serialization?

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/ReinforcementLearning.jl#97]
Over [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/df518b60103277adfb0a49f30902b96dcc16b9c2/src/components/agents/agent.jl#L33) in `RLCore`, the policy and agent_meta are saved using `BSON` while the trajectory is saved using `JLD`.

I was wondering why is this so? Why not use only `BSON`, say?

**Comment by findmyway** [comment]
https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/pull/55

We may switch to [JLSO.jl](https://github.com/invenia/JLSO.jl) in the future.

**Comment by findmyway** [comment]
Closing this issue since serialization related APIs are removed in RLCore
